April React Team Blog
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #105
Opened 2021-04-29 08:08 UTC by poiu694

2021-Spring-React April Blog
1. React Hook
2. Practice with TODO-LIST

2021-04-29 15:28 UTC, MOBUMIN requested changes
Markdownlint 준수해주세용 ~!

2021-04-30 05:37 UTC, poiu694 commented
> Markdownlint 준수해주세용 ~!

헉 넵!!! 내일 안으로 끝내겠습니다 ㅠㅠ

2021-05-01 11:30 UTC, MOBUMIN approved these changes, later dismissed
LGTM :)

2021-05-03 13:23 UTC, LeeMir requested changes
글 내용이 좋네요!! 중간에 제가 헷갈리는? 부분들이 있어서 Comment 달아봤는데 이 부분만 답해주시면 merge하겠습니다 :)

2021-05-03 13:23 UTC, LeeMir commented on _posts/2021-04-29-ReactHook.md
> +  dispatch({type: 'DEC'}) // Decrement
semicolon..? 😎

2021-05-03 13:23 UTC, LeeMir commented on _posts/2021-04-29-ReactHook.md
> +![1619681704501](../assets\images\post-React-Hook/Todolist.png)
혹시 Path가 / \가 섞인 이유가 있을까요?

로컬에서는 잘 보이는데 서버에 올라가면 보일지 모르겠네요 😃

2021-05-03 13:23 UTC, LeeMir commented on _posts/2021-04-29-ReactHook.md
> +        e.preventDefault()
semicolon..? 😎 (2)

2021-05-03 13:23 UTC, LeeMir commented on _posts/2021-04-29-ReactHook.md
> +![1619678285863](../assets\images\post-React-Hook/LocalStorage.png)
혹시 Path가 / \가 섞인 이유가 있을까요? (2) 😁

2021-05-03 13:23 UTC, LeeMir commented on _posts/2021-04-29-ReactHook.md
> +const handleSubmit = (e) =>{
여기 부분 Tab 간격이 좀 더 떨어진 이유가 있을까요??

2021-05-03 14:31 UTC, poiu694 commented
@LeeMir 전체적으로 수정했습니다!

2021-05-03 14:39 UTC, LeeMir approved these changes
고생하셨습니다 :)
LGTM!!

2021-05-03 14:44 UTC, merged