2021-spring-web-beginner April Post
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #107
Opened 2021-04-30 07:54 UTC by r4k0nb4k0n

- [x] Typing game 주제로 글 작성
- [x] `markdownlint-cli`로 린트 점검

리뷰 부탁드립니다. 감사합니다 🙇

2021-05-01 12:20 UTC, MOBUMIN submitted a review, later dismissed
랭킹 기능도 구현해주시나요? ㅎㅎ!
완벽하네욤
LGTM :)

2021-05-04 14:50 UTC, LeeMir requested changes
정말 멋지십니다.. 😎

Comment는 File에 따로 달았습니다!

2021-05-04 14:50 UTC, LeeMir commented on _posts/2021-04-29-typing-game.md
> +@Taehee Lee 님의 기능 제안으로 Fake input을 통해 Fake caret도 화살표 키를 통해 움직이는 것을 구현할 에정입니다.
Typo 😎

2021-05-04 14:50 UTC, LeeMir commented on _posts/2021-04-29-typing-game.md
> +![Primitive Typing Game Demo](https://github.com/microsoft/Web-Dev-For-Beginners/raw/main/4-typing-game/images/demo.gif)
gif 파일이 여백 부분이 모두 흰색이라 조금 어색해서 그런데
`>![Primitive Typing Game Demo](https://github.com/microsoft/Web-Dev-For-Beginners/raw/main/4-typing-game/images/demo.gif)`로 해보는건 어떨까요? 😎

2021-05-04 18:02 UTC, r4k0nb4k0n commented on _posts/2021-04-29-typing-game.md
> +@Taehee Lee 님의 기능 제안으로 Fake input을 통해 Fake caret도 화살표 키를 통해 움직이는 것을 구현할 에정입니다.
`53638cb    Fix typo` commit으로 해결했습니다. 매의 눈 감사합니다 🙇

2021-05-04 18:03 UTC, r4k0nb4k0n commented on _posts/2021-04-29-typing-game.md
> +![Primitive Typing Game Demo](https://github.com/microsoft/Web-Dev-For-Beginners/raw/main/4-typing-game/images/demo.gif)
`5dd09e7    Use blockquote to GIF` commit 으로 해결했습니다. 좋은 제안 감사합니다 🙇

2021-05-04 18:05 UTC, r4k0nb4k0n commented
> 랭킹 기능도 구현해주시나요? ㅎㅎ!
> 완벽하네욤
> LGTM :)

랭킹 기능은 좀 시간이 걸리겠지만 한번 해보겠습니다! 격려의 리뷰 감사합니다 🙇

2021-05-04 18:05 UTC, r4k0nb4k0n commented
> 정말 멋지십니다..
> 
> Comment는 File에 따로 달았습니다!
> 숨겨져있는게 있더군요 😎

코드 리뷰의 신이 여기 있었네요 😎  꼼꼼한 리뷰 감사합니다! 🙇

2021-05-04 23:53 UTC, LeeMir approved these changes
>코드 리뷰의 신이 여기 있었네요 😎 꼼꼼한 리뷰 감사합니다! 🙇

ㅎㅎ 감사합니다😄 merge하겠습니다!
LGTM :)

2021-05-04 23:53 UTC, merged