picture_error
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #112
Opened 2021-05-03 13:32 UTC by maybeluna

이 사진을 수정하는 것 같은데 맞나요?
수정했습니다 :) 수고많으십니다. 언제나 블로그 글을 위해서 힘써주셔서 고맙습니다 !!! 😁

2021-05-03 13:54 UTC, LeeMir requested changes
수정해주신 부분은 원래도 잘 보이는 사진이었습니다..!

다만 10월, 11월, 12월에 올려주신 markdown 파일 모두 썸네일(최상단에 image 태그 부분)을 brother.net에서 가져오고 계신데, 확인해보니 더 이상 존재하지 않아 이미지가 깨진 것 같아요! 그 부분 해결 부탁드립니다 :)
썸네일 사진을 `post-INTRO-XXX` 폴더에 첨부하신 후 그 주소를 연결하셔도 좋고, github이나 다른 클라우드 서비스를 이용해 url을 연결하셔도 좋습니다 😎😎😎

>수고많으십니다. 언제나 블로그 글을 위해서 힘써주셔서 고맙습니다 !!! 😁
감사합니다!! 😀😀

2021-05-03 14:55 UTC, maybeluna commented
새로수정했습니다 :)

2021-05-04 13:28 UTC, LeeMir approved these changes
잘 나오네요! 수정해주셔서 감사합니다!! 👍

2021-05-04 14:36 UTC, MOBUMIN approved these changes
빠른 수정 감사합니다!

2021-05-04 14:36 UTC, merged