For practicing
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #116
Opened 2021-05-05 08:02 UTC by hyehyeonmoon

연습용으로 제가 PR을 만들어 보았습니다!

2021-05-05 08:06 UTC, hyehyeonmoon reviewed
markdownlint 오류나는 부분 제거해주세요

2021-05-05 08:06 UTC, hyehyeonmoon commented on _posts/2021-05-05-For_practicing.md
> +</p>
이 부분이 markdownlint에서 오류가 나는 부분인데....preview에서는 문제없이 나와서..혹시 이런 경우에는 제거하는 게 맞을까요..?
```suggestion
```

2021-05-05 13:56 UTC, LeeMir commented
markdown에서는 html 태그를 잘 안씁니다!
겉 보기에는 은데 markdownlint에서 오류로 인식하는 이유도
html 태그로 할 수 있는 일을 대부분 다 markdown 문법으로 쓸 수 있기 때문이에요!
(markdown으로 통일하면 가독성 측면에서 더 좋은 것 같아요 👍)

예를 들어, 사진을 넣는다고 하면 markdown에서는
`![tag](../assets/images/post-practice/practice-title.png)` 이라고 씁니다!
tag라고 쓴 부분에는 이 이미지를 나타내는 설명?을 짧게 쓰면 좋구요! _(ex: thumb)_
만약 크기 조절을 한다면 `![tag](../assets/images/post-practice/practice-title.png){: width="220" height="190"}` 을 쓸 수 있습니다! 그런데 정렬까지는 지원하지 않아서 그 때는 혜현님이 해주신 것 처럼 html 태그나 css를 사용해야합니다..!

그리고 `<br>`태그를 사용하면 개행이 되는 것은 맞으나 이 역시 markdown에서는 잘 쓰지 않아요.
markdown에서 강제 개행하는 방법으로는 `enter`를 입력하거나 문단 끝에 `space bar`를 두 번 입력하면 되는데, 아마 아무리 띄려고 해도 한 줄? 공백까지 가능한 것으로 기억해요!

제가 아는 한에서 최대한 comment 달아봤는데, markdown 사용하는 방법에 대해서는 구글링하시거나 _posts 폴더에 있는 .md파일들 보시면 더 자세히 아실 수 있을거에요!

PR 확인해봤는데 올려주신 이미지 파일은 .PNG인데 경로로 지정할 때 .png로 하게 되면 로컬에서는 보이는데 merge되어 서버에 적용되게 되면 해당 파일을 못찾아서 이미지가 깨지더라구요! 이 부분 한 번 확인 부탁드립니다!!
(파일 확장자를 .png로 바꾸거나 경로 지정할 때 .PNG로 사용하시면 될 거에요!)

2021-05-06 04:40 UTC, hyehyeonmoon commented
상세한 설명 감사합니다! 말씀하신 부분 수정해서 다시 올려보겠습니다!

2021-05-07 10:31 UTC, MOBUMIN requested changes
직접 PR 까지 해보시다니 멋집니다 bb

2021-05-07 10:31 UTC, MOBUMIN commented on _posts/2021-05-05-For_practicing.md
> + 처음 "PR"이란 단어도 들었고, 처음 Visual code도 깔아봤다. Github으로 처음 협업을 해보는데 좀 재밌다..ㅎㅎ역시 기초 공부할 떄가 가장 재미있는 것 같다. 요구된 공부를 다 하고 드디어 PR review를 할 수 있나 싶었는데 막상 보니까 잘 모르는 게 많았다. 뭔가 잘못 건드려서 꼬이는 순간 걷잡을 수 없이 커질 것 같아 직접 PR
```suggestion
 처음 "PR"이란 단어도 들었고, 처음 Visual Studio Code도 깔아봤다. Github으로 처음 협업을 해보는데 좀 재밌다..ㅎㅎ 역시 기초 공부할 때가 가장 재미있는 것 같다. 요구된 공부를 다 하고 드디어 PR review를 할 수 있나 싶었는데 막상 보니까 잘 모르는 게 많았다. 뭔가 잘못 건드려서 꼬이는 순간 걷잡을 수 없이 커질 것 같아 직접 PR을 날리고 내 PR을 내가 리뷰해 보는 과정을 해보기로 했다. 이게 마음이 편하다....
```

오타가 있네용!!

2021-05-07 10:31 UTC, MOBUMIN commented on _posts/2021-05-05-For_practicing.md
> +![tag](../assets/images/post-practice/practice-title.PNG)
![image](https://user-images.githubusercontent.com/57705512/117436250-c109bd80-af69-11eb-810a-769fe1a64b16.png)

대표 이미지가 포스트 상단에 떠서 대표이미지랑 같은 이미지라면 여기에 없어도 될 것 같아요!

2021-05-07 10:31 UTC, MOBUMIN commented on _posts/2021-05-05-For_practicing.md
> + 여기까지 오는데 간단하게 겪었던 과정들을 이야기해 보려 한다. (사실 내 PR을 내가 review를 하려면 뭐든 써야 해서 쓰려한다....적어도 이미지 하나, 링크 하나 정도는 들어가야 오류가 어디서 나는지 내가 알 테니..)
여기 괄호 안의 말이 약간 잘 이해가 안 가서 다듬어 주시면 좋을 것 같아요 :)

2021-05-07 10:31 UTC, MOBUMIN commented on _posts/2021-05-05-For_practicing.md
> +위의 공부를 한 시간들을 합치면 하루 좀 넘게 한 것 같다. 새로운 개념들이 많이 들어오고 설치도 많이 했는데 내용이 어렵지 않아서 오히려 재미있었다.(약간 현실도피도 있었고...)아직 blog 운영은 생활코딩 강의와 실습으로는 잘 모르겠다. 그래서 이번 PR과 마찬가지로 직접 블로그를 이번 학기 끝나기 전에 만들어 보는 것을 목표로 세웠다. 그리고 vi
```suggestion
위의 공부를 한 시간들을 합치면 하루 좀 넘게 한 것 같다. 새로운 개념들이 많이 들어오고 설치도 많이 했는데 내용이 어렵지 않아서 오히려 재미있었다.(약간 현실도피도 있었고...) 아직 blog 운영은 생활코딩 강의와 실습으로는 잘 모르겠다. 그래서 이번 PR과 마찬가지로 직접 블로그를 이번 학기 끝나기 전에 만들어 보는 것을 목표로 세웠다. 그리고 VScode로 markdownlint 사용해서 md파일 작성하니까 너무 편하다. 👍
```

2021-05-07 10:31 UTC, MOBUMIN commented on _posts/2021-05-05-For_practicing.md
> +tags: ["Review"]
제가 예전에 Git 이라는 태그를 썼었는데, Git 태그를 사용하는 건 어떤가요? ㅎㅎ

2021-05-08 13:01 UTC, hyehyeonmoon commented on _posts/2021-05-05-For_practicing.md
> +tags: ["Review"]
오타 하나하나 상세하게 수정하는 꼼꼼함...배웠습니다! 사실 처음에는 제가 쓰고 제가 고치려고 연습용으로 PR을 날린 거라 짧게 썼는데 상세하게 수정해 주셔서...blog에 올리고 싶어 더 신경써서 모두수정하고 길게 썼습니다! 감사합니다!

2021-05-09 15:30 UTC, LeeMir reviewed
merge하려고 했는데 아직 오타가 많네요!! 한 번 전체적으로 훑어주시겠어요?
맞춤법 오류 일단 눈에 보이는 것은 comment로 남겼습니다..!

그리고, 대소문자도 통일하면 더 깔끔할 것 같아요 ㅎㅎ
> PR Review / PR review / PR리뷰
> Blog / blog / BLog
> Visual Studio code / VScode / visual code(?)

2021-05-09 15:30 UTC, LeeMir commented on _posts/2021-05-05-For_practicing.md
> +그래서 직접 PR을 작성해서 날리고 수정해보고 블로그에 올리는 과정을 경험해 보기로 했다. 그리고 현재 여러 번 피드백을 받으며 고치는 과정 중에서 이론으로 배웠던 것보다 훨씬 많은 것을 알게되었고 (감히 말하건데..) PR review를 할 수 있을 것 같다!
헷갈려서 맞춤법 찾아봤는데 -건대가 맞대요!

```suggestion
그래서 직접 PR을 작성해서 날리고 수정해보고 블로그에 올리는 과정을 경험해 보기로 했다. 그리고 현재 여러 번 피드백을 받으며 고치는 과정 중에서 이론으로 배웠던 것보다 훨씬 많은 것을 알게되었고 (감히 말하건대..) PR review를 할 수 있을 것 같다!
```

2021-05-09 15:30 UTC, LeeMir commented on _posts/2021-05-05-For_practicing.md
> +이번 공부과정을 통해 배운 가장 큰 수확은 PR을 날릴 수 있다는 것과 VScode로 markdownlint 사용해서 md파일 작성하하는 것이 너무 편하다는 것을 배운 것이다. 👍
```suggestion
이번 공부과정을 통해 배운 가장 큰 수확은 PR을 날릴 수 있다는 것과 VScode로 markdownlint 사용해서 md파일 작성하는 것이 너무 편하다는 것을 배운 것이다. 👍
```

2021-05-09 15:30 UTC, LeeMir commented on _posts/2021-05-05-For_practicing.md
> +위의 공부를 한 시간들을 합치면 (PR 완성까지 합치면) 이틀 좀 넘게 한 것 같다. 새로운 개념들이 많이 들어오고 설치도 많이 했는데 내용이 어렵지 않아서 오히려 재미있었다. 아직 blog 운영은 생활코딩 강의와 실습으로는 잘 모르겠다. PR을 직접한 것과 같이 블로그를 직접 만들어보면 많이 알 수 있을 것 같다.
markdownlint : 문장 끝에 띄어쓰기 있으면 안돼요!
```suggestion
위의 공부를 한 시간들을 합치면 (PR 완성까지 합치면) 이틀 좀 넘게 한 것 같다. 새로운 개념들이 많이 들어오고 설치도 많이 했는데 내용이 어렵지 않아서 오히려 재미있었다. 아직 blog 운영은 생활코딩 강의와 실습으로는 잘 모르겠다. PR을 직접 한 것과 같이 블로그를 직접 만들어보면 많이 알 수 있을 것 같다.
```

2021-05-09 15:30 UTC, LeeMir commented on _posts/2021-05-05-For_practicing.md
> +하지만 Github로 제대로 된 협업을 하는 것은 이번이 처음이었기에  PR이라는 용어조차 생소했다. 그래서 수빈 님이 친절히 알려주신 PR날리는 법 강의를 다시 보며 구글링을 통해 PR의 개념에 대해 공부했다. 모든 공부가 끝나고 이제 드디어 PR Review를 할 수 있을 줄 알았는데...웬걸 막상 하려 하니 감이 안 잡혔다.
```suggestion
하지만 Github로 제대로 된 협업을 하는 것은 이번이 처음이었기에 PR이라는 용어조차 생소했다. 그래서 수빈 님이 친절히 알려주신 PR날리는 법 강의를 다시 보며 구글링을 통해 PR의 개념에 대해 공부했다. 모든 공부가 끝나고 이제 드디어 PR Review를 할 수 있을 줄 알았는데...웬걸 막상 하려 하니 감이 안 잡혔다.  
```

2021-05-09 15:30 UTC, LeeMir commented on _posts/2021-05-05-For_practicing.md
> +HTML&CSS에 대해 기본적인 개념을 공부해야 했다. 생활코딩으로 첫 시작을 하면 좋다고 하셔서 생활코딩에서 "Html&Internet"과 "CSS" 과정을 1.5배속으로 들었다.^^ Atom도 깔아보고 WAMP도 깔아보면서 실습까지 함께 하니 그 동안 언뜻 보았던 코드들이 무엇을 의미하는지 알 수 있었고, 개념도 확실히 이해할 수 있었다.
```suggestion
HTML&CSS에 대해 기본적인 개념을 공부해야 했다. 생활코딩으로 첫 시작을 하면 좋다고 하셔서 생활코딩에서 "Html&Internet"과 "CSS" 과정을 1.5배속으로 들었다.^^ Atom도 깔아보고 WAMP도 깔아보면서 실습까지 함께하니 그동안 언뜻 보았던 코드들이 무엇을 의미하는지 알 수 있었고, 개념도 확실히 이해할 수 있었다.  
```

2021-05-09 15:30 UTC, LeeMir commented on _posts/2021-05-05-For_practicing.md
> +하지만 실제로 Jekyll을 설치하고 블로그를 꾸민다거나 이슈를 찾으려 하니 "음...그래서 어떻게 하지..?"하는 생각이 들면서 아직 부족함을 느꼈다. 그래서 Jekyll을 이용해 개인 블로그를 만들어 보기로 스스로 결정했다. 직접 만들어 보면 분명 더 구조와 방식을 잘 이해하고 이것이 UOS DSC 블로그 운영에 분명 도움이 될 것이다.
DSC UOS가 더 좋을 것 같아요!
```suggestion
하지만 실제로 Jekyll을 설치하고 블로그를 꾸민다거나 이슈를 찾으려 하니 "음...그래서 어떻게 하지..?"하는 생각이 들면서 아직 부족함을 느꼈다. 그래서 Jekyll을 이용해 개인 블로그를 만들어 보기로 스스로 결정했다. 직접 만들어 보면 분명 더 구조와 방식을 잘 이해하고 이것이 DSC UOS 블로그 운영에 분명 도움이 될 것이다.
```

2021-05-09 23:18 UTC, hyehyeonmoon commented on _posts/2021-05-05-For_practicing.md
> +하지만 실제로 Jekyll을 설치하고 블로그를 꾸민다거나 이슈를 찾으려 하니 "음...그래서 어떻게 하지..?"하는 생각이 들면서 아직 부족함을 느꼈다. 그래서 Jekyll을 이용해 개인 블로그를 만들어 보기로 스스로 결정했다. 직접 만들어 보면 분명 더 구조와 방식을 잘 이해하고 이것이 UOS DSC 블로그 운영에 분명 도움이 될 것이다.
대소문자 통일하고 맞춤법 검사기 돌렸습니다! 상세하게 리뷰해주셔서 감사해요! 다음에는 더 주의하도록 하겠습니다!

2021-05-10 04:35 UTC, LeeMir approved these changes
멋지십니다 😎 
LGTM 👍 👍 👍

2021-05-11 07:21 UTC, MOBUMIN approved these changes
고생하셨어요!! ψ(｀∇´)ψ

2021-05-11 07:22 UTC, merged