Team Kaggle 5월 PR입니다!
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #128
Opened 2021-05-26 15:19 UTC by hyehyeonmoon

한국어 맞춤법 검사기 돌려서 맞춤법은 이탈자 없을 것 같습니다! 맥락이나 혹시 오류 발생 등등 문제가 있으면 리뷰 남겨주시길 부탁드립니다.^^

2021-06-01 17:08 UTC, rxdcxdrnine commented on _posts/2021-05-25-Review_of_Dev_matching.md
> +이틀 동안 합쳐서 5시간 잔 것 같다. 공부한 시간 반절, 오류 잡는 시간 반절이었다. Dev-Matcing을 끝낸 소감은 아래와 같다.
오탈자를 발견했습니다!

2021-06-22 10:44 UTC, yuniwisdom requested changes

2021-06-22 10:44 UTC, yuniwisdom commented on _posts/2021-05-25-Review_of_Dev_matching.md
> +최종 목표는 Multi-label clasification, Multi-class classification 두 task를 모두 다룰 수 있고, Efficient Net+OOF를 task에 적용하는 것이었다.
```suggestion
최종 목표는 Multi-label classification, Multi-class classification 두 task를 모두 다룰 수 있고, Efficient Net+OOF를 task에 적용하는 것이었다.
```

2021-06-22 10:44 UTC, yuniwisdom commented on _posts/2021-05-25-Review_of_Dev_matching.md
> +이 일을 계기로 딥러닝 실행에 있어 중요한 문제인 Memory를 인식하게 되었고, epoch, batch_siz 등의 값에 따라 시간과 용량이 얼마나 달라지는지를 감을 잡을 수 있었다.
```suggestion
이 일을 계기로 딥러닝 실행에 있어 중요한 문제인 Memory를 인식하게 되었고, epoch, batch_size 등의 값에 따라 시간과 용량이 얼마나 달라지는지를 감을 잡을 수 있었다.
```
오탈자 발견했습니다! ㅎㅎ 딥러닝에 대해 공부해보고 싶어지는 글이에요 멋진 경험 공유 감사합니다😊

2021-06-26 06:32 UTC, hyehyeonmoon commented on _posts/2021-05-25-Review_of_Dev_matching.md
> +이틀 동안 합쳐서 5시간 잔 것 같다. 공부한 시간 반절, 오류 잡는 시간 반절이었다. Dev-Matcing을 끝낸 소감은 아래와 같다.
수정했습니다!^^

2021-06-26 06:32 UTC, hyehyeonmoon commented on _posts/2021-05-25-Review_of_Dev_matching.md
> +이 일을 계기로 딥러닝 실행에 있어 중요한 문제인 Memory를 인식하게 되었고, epoch, batch_siz 등의 값에 따라 시간과 용량이 얼마나 달라지는지를 감을 잡을 수 있었다.
수정했습니다!^^

2021-06-26 08:08 UTC, MOBUMIN approved these changes
와와 엄청 열심히 하셨네요bbb

2021-06-27 10:36 UTC, yuniwisdom approved these changes

2021-06-29 07:15 UTC, merged