Spring-Web-React Post May 2021
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #131
Opened 2021-05-31 09:27 UTC by sejkimm

2021-06-26 08:46 UTC, MOBUMIN requested changes
좋은 내용 감사합니다~!!
수정 요청 사항 몇 가지 적어봤습니다 :)

2021-06-26 08:46 UTC, MOBUMIN commented on _posts/2021-05-28-VirtualDOM.md
> +image: assets/images/post-virtualDOM/thumb.PNG
썸네일 이미지가 없어서 안보여요!

2021-06-26 08:46 UTC, MOBUMIN commented on _posts/2021-05-28-VirtualDOM.md
> +authors: [sejkimm]
블로그 author페이지 등록이 안 되어 있으신듯 하네요.....ㅠㅠ

_data 폴더에 author.yml 파일에 정보 적어주세요!

2021-06-26 08:46 UTC, MOBUMIN commented on _posts/2021-05-28-VirtualDOM.md
> +이러한 변환은 브라우저의 렌더링 엔진에서 발생한다. 렌더링 엔진은 브라우저의 구성 요소이며, 클라이언트가 브라우저에 요청한 타입의 문서를 화면의 표현하는 기능을 한다. 이 과정에서 문서를 DOM으로 변환하게 되는데, 세부적인 동작의 예시(Webkit 렌더링 엔진)는 다음과 같다.
```suggestion
이러한 변환은 브라우저의 렌더링 엔진에서 발생한다. 렌더링 엔진은 브라우저의 구성 요소이며, 클라이언트가 브라우저에 요청한 타입의 문서를 화면에 표현하는 기능을 한다. 이 과정에서 문서를 DOM으로 변환하게 되는데, 세부적인 동작의 예시(Webkit 렌더링 엔진)는 다음과 같다.
```

2021-06-26 08:46 UTC, MOBUMIN commented on _posts/2021-05-28-VirtualDOM.md
> +트리 편집 거리 문제에 대한 좋은 알고리즘중 하나는 Zhang and Shasha의 알고리즘으로 알려져 있다. 해당 알고리즘을 간단하게 소개하면, 정렬된 트리에 대해 keyroots를 트리의 루트 노드와 왼쪽 형제가 있는 노드의 집합으로 정의한다. 노드 v가 keyroots에 포함되는 경우 v에 대한 서브트리는 재귀적으로 전체 트리에 대한 문제와 같은 방
| <- 이 특수문자가 마크다운에서는 테이블을 만드는 특수문자라 블로그에서 이상하게 보입니다!
`&#124;` 이거로 바꿔쓰시면 해당 문자를 사용할 수 있습니다.
vscode에서 드래그 후 Ctrl + F2 혹은 Ctrl+Shift+L 누르면 드래그한 텍스트와 같은 모든 텍스트에 커서를 만들어 수정가능합니다!!

2021-06-27 05:18 UTC, sejkimm commented
세심한 리뷰 감사합니다. 관련 이슈 수정했습니다.

2021-06-27 06:49 UTC, MOBUMIN approved these changes
LGTM :)

2021-06-30 11:28 UTC, min6choi approved these changes
LGTM!

2021-06-30 11:28 UTC, merged