maybeluna web beginner team
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #138
Opened 2021-06-28 07:34 UTC by maybeluna

web beginner 팀 김수빈 클론코딩 웹사이트 관련해서 블로그 포스팅 했습니다 :)

2021-07-04 05:44 UTC, yuniwisdom requested changes

2021-07-04 05:44 UTC, yuniwisdom commented on _posts/2021-06-28-Web_Beginner.md
> +![youtube_mobile](assets/images/post-Web-Beginner/clonecoding_myoutube.PNG)
```suggestion
![youtube_mobile](../assets/images/post-Web-Beginner/clonecoding_myoutube.PNG)
```

2021-07-04 05:44 UTC, yuniwisdom commented on _posts/2021-06-28-Web_Beginner.md
> +// 전체 패딩을 0으로
이건 margin을 패딩으로 잘못쓰신걸까요?
```suggestion
// 전체 패딩을 '0'으로
``` 여기 0만 쓰면 오류로 떠서 '0'이렇게 표현하면 오류로 안뜹니다!

2021-07-04 05:44 UTC, yuniwisdom commented on _posts/2021-06-28-Web_Beginner.md
> +![bmax_pc](assets/images/post-Web-Beginner/clonecoding_pcbmax.PNG)
```suggestion
![bmax_mobile](../assets/images/post-Web-Beginner/clonecoding_mbmax.PNG)
![bmax_pc](../assets/images/post-Web-Beginner/clonecoding_pcbmax.PNG)
```

2021-07-04 05:44 UTC, yuniwisdom commented on _posts/2021-06-28-Web_Beginner.md
> +    display: none; // 모바일 버전 버튼 pc 상에서 감추기
```suggestion
    display: none; /* 모바일 버전 버튼 pc 상에서 감추기 */
```여기선 한줄 주석을 사용하면 오류로 뜨네요 :) 이 주석 사용하면 될 것 같아요

2021-07-04 05:44 UTC, yuniwisdom commented on _posts/2021-06-28-Web_Beginner.md
> +    nev button{ // 모바일 버전 버튼 나타내기
```suggestion
    nev button{ /* 모바일 버전 버튼 나타내기 */
```
클론코딩으로 멋진 웹사이트 만드는거 저도 해보고 싶어요 ㅎㅎ 글 가독성 좋게 너무 잘쓰셨어요👍👍

2021-07-06 13:31 UTC, maybeluna commented on _posts/2021-06-28-Web_Beginner.md
> +    nev button{ // 모바일 버전 버튼 나타내기
윤지님 다 수정했습니다 :) 답변 친절하게 해주셔서 감사해요!!!

2021-07-06 13:38 UTC, yuniwisdom approved these changes, later dismissed
LGTM!!👍

2021-07-08 09:54 UTC, yuniwisdom approved these changes
수빈님 브랜치에 잘못 커밋한걸 모르고 파일을 지워버려서 ㅎㅎ.. 해결했습니다!

2021-07-09 10:40 UTC, LeeMir requested changes
좋은 글인 것 같아요!
크게 문제가 되는 부분은 아닌데, 코드 블럭에서 코드 통일성이 있으면 더 좋을 것 같아 몇 개 comment 남겼습니다!

그리고 이것도 사실 개인 차이이긴한데, 저는 css에서 중괄호 쓸 때 중괄호와 앞 글자 사이에 띄워주는게 보기 편하더라구요! 예를 들면
```css
nev {
    display: flex;
}
```
이렇게요!
나중에 협업하실 때 eslint 같은 툴을 쓸 수도 있어서, 처음에 습관을 잘 들여놓으시면 그 때가서 도움이 될겁니다 👍

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +    margin:0;
```suggestion
    margin: 0;
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +    font-size:x-large;
```suggestion
    font-size: x-large;
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +    color:dodgerblue
```suggestion
    color: dodgerblue;
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +    padding: 2px
```suggestion
    padding: 2px;
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +        display:inline ;
```suggestion
        display: inline; 
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +    }
```suggestion
}
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +    }
```suggestion
}
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +이것을 통해 positon의 relative, absolute를 언제 가장
```suggestion
이것을 통해 position의 relative, absolute를 언제 가장
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +        display:inline ;
```suggestion
        display: inline; 
```

2021-07-09 10:40 UTC, LeeMir commented on _posts/2021-06-28-Web_Beginner.md
> +자유자재로 변하는 웹사이트를 만드는 것은 아직 서툴어서
저도 헷갈렸던 부분인데, "서툴러서"가 맞는 표현이라고 하더라구요! :)

2021-11-05 09:52 UTC, closed without merging