[10월 FrontEnd Blog] React-Fiber-Architecture
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #160
Opened 2021-10-22 04:37 UTC by poiu694

처음에 옛날에 작업 했던 폴더라고 생각했는데 아니더라고요..!

잘못 push를 넣어서 로그를 지저분하게 만들었어요 ㅠㅠ 죄송합니다

2021-10-28 13:46 UTC, LeeMir requested changes
크 처음에 markdownlint 적용된 것을 보고 한 번 놀라고 😮
사진이 다 잘 나오는 것을 보고 두 번 놀랐습니다. 😮😮

그런데 상민님 맨날 영어 자료만 보시더니 쓰신 글이 분명 한글인데 영어 자료 같이 읽히네요 😆😆
어색한 부분들에 Comment 남겼습니다!
자료도 얼마 없는 어려운 내용 정리하느라 고생하셨어요!!

2021-10-28 13:46 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +다른 장점으로는 fiber tree를 통해서 memory allocation과 garbage collection에서 시간을 아낄 수 있습니다.
fiber tree의 업데이트 과정이 나오다가 갑자기 `다른 장점으로는~~`이 튀어나오니까 어색하네요..!
좀 더 부드럽게 연결하면 좋을 것 같아요!

2021-10-28 13:46 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +   4. list의 children인 button부터 작업이 돼야 하니까 list에 mark만 해놓습니다.
![image](https://user-images.githubusercontent.com/42960217/139258045-b567fc72-8ad1-4af9-b81e-903ddb9c2167.png)
이 부분 실제 렌더링 모습입니다.
- 숫자 리스트는 간격이 좁고 그 하위인 점 리스트는 간격이 넓은 게 어색한 것 같네요! 앗 의도하신거라면 상관 없을 것 같기도 해요!
- 그리고 문맥도 조금 어색했는데요, `다음에 다룰 작업을 hostRoot(위 사진 참고)라 하고 시간은 12.3ms가 남았다고 가정을 해보겠습니다.`라고 하면 좀 더 이해가 잘 될 것 같습니다.
- 그림에는 HostRoot라고 나와있는데 글의 hostRoot를 HostRoot로 바꾸실 의향이 있으신가용
- 숫자 리스트를 인용문 안에 넣는 건 어떠신가요! 리스트 크기가 커서 본문과 구분이 좀 더 잘되면 좋을 것 같아요!

2021-10-28 13:46 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +commit phase에서는 실제로 반영합니다.
영상에 나오는 것 같긴 한데, 글에서는 `phase`라는 단어가 처음 등장했네요..!
`phase`에 대한 설명이 조금 부족한 것 같기도 합니다.

`commit phase에서는 실제로 반영합니다.`라는 말이 뭔가 되게 영어 문장 같네요

2021-10-28 13:46 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +우리는 기존의 reconciler를 stack reconciler라고 부릅니다.
저도 찾아봤는데 정확히 react 15.x까지 stack이고 16.x부터 fiber라네요! 이 부분 언급이 되면 좋을 것 같아요!

2021-10-28 13:46 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +6. **Offscreen** : prep for display / scroll
각 단계 별로 예시를 드는 등 설명이 조금 더 잘 됐으면 좋겠어요!
관련 자료를 찾아보려고 했는데 잘 안나오더라구요 😭

2021-10-28 13:46 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +우리는 이런 과정이 있기 때문에 애니메이션이 끊기지 않고 부드럽게 볼 수 있습니다.
rAF와는 다른가요?? (궁금) 🤔

2021-10-28 15:24 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +   4. list의 children인 button부터 작업이 돼야 하니까 list에 mark만 해놓습니다.
> 숫자 리스트를 인용문 안에 넣는 건 어떠신가요! 리스트 크기가 커서 본문과 구분이 좀 더 잘되면 좋을 것 같아요!

제 마음대로 고쳤는데 얘기해주신게 혹시 이게 맞을까요 ?!

2021-10-28 15:24 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +commit phase에서는 실제로 반영합니다.
수정했습니다 !

2021-10-28 15:24 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +다른 장점으로는 fiber tree를 통해서 memory allocation과 garbage collection에서 시간을 아낄 수 있습니다.
수정했습니다 !

2021-10-28 15:25 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +우리는 기존의 reconciler를 stack reconciler라고 부릅니다.
옹 되게 좋은 것 같아요! 바로 수정했습니다 !

2021-10-28 15:25 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +6. **Offscreen** : prep for display / scroll
ㅠㅠ 저도 간략하게만 알고 있어서 조금만 넣어봤습니다 !

2021-10-28 15:29 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +우리는 이런 과정이 있기 때문에 애니메이션이 끊기지 않고 부드럽게 볼 수 있습니다.
rAF가 requestAnimationFrame이 맞나요 ?!

requestAnimationFrame은 다음 애니메이션 프레임에서 호출될 "우선순위 높은 함수"만을 예약해주는 것으로 알고 있습니다 !

렌더링이 분할되서 작동하지 않고 호출 스택에만 의존하는 경우 스택이 비어 있을 때까지 계속 작업을 해주기 때문에 애니메이션이 부드럽게 안보이는 경우가 생긴다고 하더라고요 !

그래서 fiber에서는 분할 + 우선순위를 통해서 이를 해결한다고 합니다 !

2021-10-28 15:30 UTC, poiu694 commented
중간고사기간이라 동영상을 그냥 배끼듯이 해서 번역투가 짱 많네요.>! ㅜㅠㅜㅠ

번거롭게 해서 죄송합니다. 나름대로 고쳐봤어요 !

2021-10-28 15:40 UTC, LeeMir submitted a review, later dismissed
확실히 글이 전반적으로 읽기 편해졌네요 :)
빠른 픽스 최고네요..👍 고생하셨어요!
Approve하겠습니다 LGTM~

- - -

> 제 마음대로 고쳤는데 얘기해주신게 혹시 이게 맞을까요 ?!

ㄴ 기존 리스트를 통째로 인용문에 넣자는 뜻이었는데, 이것도 보기 좋은 것 같아요 :D 

혹시 더 고치고 싶은 부분 있으실까 해서 바뀐 부분 캡쳐 첨부합니다!

![image](https://user-images.githubusercontent.com/42960217/139288974-8c212703-bf39-4f70-af35-b352f8d49a5e.png)

2021-11-03 00:48 UTC, SHEELE41 requested changes

2021-11-03 00:48 UTC, SHEELE41 commented on _posts/2021-10-22-react-fiber-architecture.md
> +그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁
```suggestion
그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁

```
제가 글 작성했을 때는 문서의 끝을 알리기 위해 마지막에 개행 한 번 추가해주는 것이 좋다는 리뷰가 있었는데 차이가 있는지는 잘 모르겠네요 ㅎㅎ 부담이 안 되신다면 해주시는 것도 괜찮을 것 같습니다!
이 외에는 다 좋아 보여서 변경 사항 적용되면 Approve 하겠습니다! LGTM!

2021-11-03 03:48 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁
로컬에는 들어가있는데, 여기서는 왜 안들어가있죠..?! 그래서 diff가 안생겨서 커밋을 할 수가 없네요..!

원인 파악하고 푸쉬해 놓겠습니다 !

2021-11-03 03:55 UTC, poiu694 commented
웹 깃헙에서 suggestion을 바꾸면서 반영이 안 된 줄 알았는데, 되있어서 이상한 짓 했네요 ㅎㅎ

수정완료 했습니다 !

2021-11-03 05:18 UTC, LeeMir commented on _posts/2021-10-22-react-fiber-architecture.md
> +그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁
@SHEELE41

상민님 글이 EOL이 원래 있었는데 이러면 EOL이 두 줄이 되는 꼴이라서 markdownlint가 어긋나는데 괜찮나요?
예전 종규님 글도 아마 EOL이었던 것 같더라구요!!

2021-11-03 06:03 UTC, SHEELE41 commented on _posts/2021-10-22-react-fiber-architecture.md
> +그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁
@LeeMir @poiu694 지금 상민님께서 최종 수정해주신 내용 받아서 돌려보니까 한 줄로 나오는데 내용 반영 된 건가요?

2021-11-03 06:10 UTC, poiu694 commented on _posts/2021-10-22-react-fiber-architecture.md
> +그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁
저는 로컬에서 블랭크 2개로 되어있습니다 !

<img width="500" alt="image" src="https://user-images.githubusercontent.com/43488305/140016197-9872c100-46bf-4d65-aabe-a8ae8cecefd6.png">

2021-11-03 06:15 UTC, SHEELE41 commented on _posts/2021-10-22-react-fiber-architecture.md
> +그렇게 리액트 fiber를 통해 마법같은 렌더링과 Virtual DOM이 어떻게 업데이트 되는지를 확인할 수 있었습니다 😁😁
아 그럼 markdownlint에 맞게 한 줄로 가는 게 맞을 것 같습니다 ㅠㅠ 죄송합니다 왜 깃헙에서 다르게 보였을까요

2021-11-03 06:24 UTC, SHEELE41 approved these changes

2021-11-03 06:25 UTC, SHEELE41 commented
LGTM!

2021-11-03 06:45 UTC, LeeMir approved these changes

2021-11-03 06:49 UTC, merged