about-pls
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #161
Opened 2021-10-22 13:05 UTC by keepproceeding

안녕하세요.

당월 data-ml 팀 블로그 내용 작성을 맡게된 오원진입니다.
차원축소 기법 중 하나인 PLS에 대해 소개하고자 합니다.

2021-10-30 12:09 UTC, YubeenSon requested changes
늦은 리뷰 죄송합니다!!
찬찬히 다 읽어봤고 몇몇 부분 수정 부탁드립니다!

2021-10-30 12:09 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> + 올 여름방학때 수료했던 데이터 청년 캠퍼스 교육과정에서는 교육 후 분석 프로젝트를 진행하여 우수작을 선정하고 장관상부터 여러 협회장상을 수상하는 기회를 제공합니다. ~~장관상이 목표였던~~ 저는 프로젝트 전에 여러 ML 알고리즘과 분석 방법론을 고민했었는데 PLS는 그 중 하나였습니다. 따라서 이번 기회에 제가 공부했던 PLS에 대해 소개해드리고자 합니
올 여름 방학때 수료했던 교육 과정에서는 ~~ 제공합니다.
서술어 호응 맞춰서 과거형으로 수정 부탁드립니다!

2021-10-30 12:09 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> +**PLS 용어**는 선형 조합으로 추출된 변수(기존 PCA의 Eigen Vector를 의미)가 설명하지 못하는 부분에 지속적으로 LSE를 사용하는 것에서 유래합니다.
여기 보면서 PLS, LSE 등 처음 나오는 약어는 옆에 원래의 긴 표현(EX. PLS(Partial Least...)도 같이 적어주면 처음 읽는 사람도 이해가 쉬울 것 같아요 :)

2021-10-30 12:09 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> +아래 예제로 이해해봅시다.
이 부분에서 `## 예제`형식으로 끊어 가도 좋을 것 같아요!

2021-10-30 12:09 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> +t_1이 Y_1를 어느정도로 설명 가능한지 파악하기 위해 OLS 회귀 분석을 사용합니다. 그리고 Y_1와 Y_1hat의 차이(잔차)를 Y_2로 놓습니다.
마크다운에서도 hat 표현이 가능합니다!
https://uwgdqo.tistory.com/9
링크 참조하셔서 hat부분 수정 부탁드립니다

2021-10-30 12:09 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> +---
구분선이 들어가는 기준이 있을까요..? 궁금해서 여쭤봅니다!

2021-10-30 14:01 UTC, keepproceeding commented on _posts/2021-10-22-about-pls.md
> +---
단변량 모형에서 다변량 모형으로 설명하는 부분이 달라져서 구분했어요!

2021-10-30 17:54 UTC, YubeenSon requested changes
변수들이 정말 깔끔해졌네요 :)!!!
bold 적용 오류 부분과 구분선 부분만 다시 수정 부탁드립니다!

2021-10-30 17:54 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> +**PLS(Partial Least Squares)**는 PCA와 다르게 Y와의 공분산이 높은 k 개의 선형 조합 변수를 추출하는 방식입니다.
이 부분 Preview로 보니까 마지막 괄호로 인해 bold처리 되지 않고 **이 그냥 노출되고있어요
확인 부탁드려요!

2021-10-30 17:54 UTC, YubeenSon commented on _posts/2021-10-22-about-pls.md
> +---
뒷부분에서 구분선이 많이 쓰여서 앞부분과의 통일성을 위해 단변량 모형과 다변량 모형은 `### 제목3` 형태로 구분하는걸 추천드려요
앞에서 예제에서 `## 제목2`를 썼으니까 제목 타입으로 내용을 구분하는게 좋을 것 같아요!

2021-10-31 05:04 UTC, keepproceeding commented on _posts/2021-10-22-about-pls.md
> +---
확인했습니다~!

2021-11-01 08:13 UTC, happiesoo41 approved these changes
LGTM

2021-11-01 10:03 UTC, YubeenSon approved these changes
고생 많으셨습니다:)!

2021-11-03 00:53 UTC, SHEELE41 approved these changes
LGTM

2021-11-03 00:54 UTC, merged