[10월 backend blog] Nest.js Redux-saga with Socket.IO
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #162
Opened 2021-10-24 09:51 UTC by rxdcxdrnine

10월 백엔드 팀 블로그 작성합니다.
주제는 Nest.js 와 Redux-saga 로 Socket.IO 를 이용한 소켓 통신 구현하기입니다.
프론트엔드 지분이 많지만... 백엔드 팀 블로그 글 맞습니다.

2021-10-28 03:56 UTC, poiu694 reviewed
배울게 많은 글이네요 ! 좋은 글 감사합니다 !

2021-10-28 03:56 UTC, poiu694 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +현재 진행하고 있는 프로젝트에서 자바스크립트 웹 프레임워크로 React.js 와 상태 관리 라이브러리로 Redux 및 Redux-saga, Node.js 서버사이드 프레임워크로 Nest.js 를 사용해 Socket.IO API 을 이용한 소켓 통신 기반 서비스를 개발하고 있습니다. 두 프레임워크 모두 이번 프로젝트를 통해 처음 사용하게 되었는데, 왜 이
> 현재 진행하고 있는 프로젝트에서 자바스크립트 웹 프레임워크로 React.js

리액트가 라이브러리가 되었다고 하네요 !

2021-10-28 03:56 UTC, poiu694 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +하지만 Nest.js 는 다릅니다. controller, service, module 각 클래스들와, Nest.js 에서 제공하는 filter, pipe, guard 등의 클래스들은 모두 다 역할을 가지고 있습니다. 클래스들를 사용하는 데 있어 Spring 과 같이 IoC (Inversion of Control), DI (Depdency Injection
> Socket.IO 를 사용하고자 한다면, 애플리케이션을 시랭할 index.js 로부터

시랭도 머랭같아서 좋긴 한데, 실행이 좀 더 어울려보이네요 !

2021-10-28 04:14 UTC, rxdcxdrnine commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +하지만 Nest.js 는 다릅니다. controller, service, module 각 클래스들와, Nest.js 에서 제공하는 filter, pipe, guard 등의 클래스들은 모두 다 역할을 가지고 있습니다. 클래스들를 사용하는 데 있어 Spring 과 같이 IoC (Inversion of Control), DI (Depdency Injection
수정했습니다!

2021-10-28 04:14 UTC, rxdcxdrnine commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +현재 진행하고 있는 프로젝트에서 자바스크립트 웹 프레임워크로 React.js 와 상태 관리 라이브러리로 Redux 및 Redux-saga, Node.js 서버사이드 프레임워크로 Nest.js 를 사용해 Socket.IO API 을 이용한 소켓 통신 기반 서비스를 개발하고 있습니다. 두 프레임워크 모두 이번 프로젝트를 통해 처음 사용하게 되었는데, 왜 이
수정했습니다!

2021-10-28 04:25 UTC, poiu694 submitted a review, later dismissed
LGTM :) :+1: :+1:

2021-10-29 10:42 UTC, suin0730 commented
스프링에 관심 있는 저에게 귀중한 글이네요😁
창구님 글을 보니 nest.js에 마음이 열렸습니다!
좋은 글 감사합니다ㅎㅎ

2021-11-02 14:23 UTC, super-corini commented
어디서 많이 본 프로젝트 같은데 낯선 곳에서 익숙한 향기가 나네요...
기술 유출범입니다. 따끔하게 Approve해주세요 ㅡㅡ

2021-11-02 14:50 UTC, harper2835 reviewed
.

2021-11-02 14:50 UTC, harper2835 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +이전까지 프로젝트를 진행할 때 주로 서버 개발에 참여하면서 Python Django/Flask, Node.js Express, Java Spring 등 여러 언어의 서버사이드 프레임워크를 사용하였습니다. 현재는 가급적이면 현업에서 많이 사용하는 Spring 프레임워크를 기반으로 개발하고자 하지만, 프로젝트를 진행할 때마다 팀 내 상황에 맞춰 언어와 프레임
아래 문장 나누면 좋을 것 같습니다!
> 이번 프로젝트를 진행하는데 있어서도 함께 참여하는 팀원들이 Spring 에 대한 경험은 없었지만 JS 와 Express.js 에 대한 경험들이 있었고, 소켓 통신을 구현하는데 사용할 Socket.IO API 의 경우 기본적으로 Node.js 서버를 지원하며 documentation 도 모두 JS 기반으로 작성되어있어, Socket.IO 라이브러리를 안정적이고 효율적으로 사용할 수 있을 것이라고 생각했기 때문에 최종적으로 서버 개발 환경으로 Node.js 를 선택하게 되었습니다.

2021-11-02 14:50 UTC, harper2835 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +React.js 에서 어플리케이션이 복잡해질수록 컴포넌트에 데이터를 props 로만 넘겨주기 힘들기 때문에, redux 와 같은 SPA (Single Page Application) 전역 상태 관리 라이브러리를 사용합니다. redux 를 사용하는 경우, 상태를 업데이트할 때 비동기 처리를 위한 복잡한 로직을 쉽게 핸들링하기 위해 redux 의 미들웨어를
이 문장도 나누면 좋을 것 같아요!

> 현재 프로젝트에서는 클라이언트에서 서버와 통신할 때 Socket.IO 뿐만 아니라 REST API 를 사용하는데, REST API 를 이용한 데이터 fetch 시 Promise 를 활용한 비동기 처리를 활용하고, Socket.IO 의 client API 사용 시 callback 함수를 활용하여 상태 업데이트 로직을 구성하기 위해 redux 의 미들웨어에 대한 필요성을 느꼈습니다.

2021-11-02 15:03 UTC, suin0730 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +이전까지 프로젝트를 진행할 때 주로 서버 개발에 참여하면서 Python Django/Flask, Node.js Express, Java Spring 등 여러 언어의 서버사이드 프레임워크를 사용하였습니다. 현재는 가급적이면 현업에서 많이 사용하는 Spring 프레임워크를 기반으로 개발하고자 하지만, 프로젝트를 진행할 때마다 팀 내 상황에 맞춰 언어와 프레임
아래 문장 쪼개면 더 읽기 쉬울 것 같아요..! lint로 글자수 확인해도 좋을 것 같습니다ㅎㅎ

>  이번 프로젝트를 진행하는데 있어서도 함께 참여하는 팀원들이 Spring 에 대한 경험은 없었지만 JS 와 Express.js 에 대한 경험들이 있었고, 소켓 통신을 구현하는데 사용할 Socket.IO API 의 경우 기본적으로 Node.js 서버를 지원하며 documentation 도 모두 JS 기반으로 작성되어있어, Socket.IO 라이브러리를 안정적이고 효율적으로 사용할 수 있을 것이라고 생각했기 때문에 최종적으로 서버 개발 환경으로 Node.js 를 선택하게 되었습니다.

2021-11-02 15:03 UTC, suin0730 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +React.js 에서 어플리케이션이 복잡해질수록 컴포넌트에 데이터를 props 로만 넘겨주기 힘들기 때문에, redux 와 같은 SPA (Single Page Application) 전역 상태 관리 라이브러리를 사용합니다. redux 를 사용하는 경우, 상태를 업데이트할 때 비동기 처리를 위한 복잡한 로직을 쉽게 핸들링하기 위해 redux 의 미들웨어를
이 문장도요!!

> 현재 프로젝트에서는 클라이언트에서 서버와 통신할 때 Socket.IO 뿐만 아니라 REST API 를 사용하는데, REST API 를 이용한 데이터 fetch 시 Promise 를 활용한 비동기 처리를 활용하고, Socket.IO 의 client API 사용 시 callback 함수를 활용하여 상태 업데이트 로직을 구성하기 위해 redux 의 미들웨어에 대한 필요성을 느꼈습니다.

2021-11-02 15:03 UTC, suin0730 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +featured: false
featured 옵션 true로 변경 부탁드립니다!

2021-11-03 01:02 UTC, SHEELE41 requested changes

2021-11-03 01:02 UTC, SHEELE41 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +현재 프로젝트에서 클라이언트와 서버 모두 소켓 통신 부분만 담당하고 있기 때문에, Socket.IO API 를 사용하는 모듈만 독립적으로 관리하는 것이 필수적이었다고 생각합니다. 이제 위와 같이 Nest.js 의 gateway 와 React.js 에서 redux-saga 를 통해 Socket.IO 와 관련된 코드를 별도의 모듈에서 종속성 문제 없이 깔끔하
```suggestion
현재 프로젝트에서 클라이언트와 서버 모두 소켓 통신 부분만 담당하고 있기 때문에, Socket.IO API 를 사용하는 모듈만 독립적으로 관리하는 것이 필수적이었다고 생각합니다. 이제 위와 같이 Nest.js 의 gateway 와 React.js 에서 redux-saga 를 통해 Socket.IO 와 관련된 코드를 별도의 모듈에서 종속성 문제 없이 깔끔하게 관리할 수 있게 되었습니다. Nest.js 에서는 Service 클래스에 비즈니스 로직을 구성하고 gateway 에서 Service 클래스를 주입받아 메서드를 호출하며, React.js 에서는 소켓 통신을 처리하는 saga 함수가 선언된 모듈과 분리된 비동기 처리 saga 함수 모듈을 관리하고 있습니다.

```
별 거 아니긴 한데 문서 마지막에 한 줄 띄워주세요~

2021-11-03 01:07 UTC, iju1633 commented
제가 잘 몰랐던 Redux-sage에 대한 흥미로운 주제였습니다, 개인적으로 http 통신과 소켓 통신의 차이에 대해서도 알게된 계기가 되었네요. 좋은 글 감사합니다!

2021-11-03 01:27 UTC, iju1633 reviewed
제가 잘 몰랐던 Redux-sage에 대한 흥미로운 주제였습니다, 개인적으로 http 통신과 소켓 통신의 차이에 대해서도 알게된 계기가 되었네요. 좋은 글 감사합니다!

2021-11-03 06:04 UTC, SHEELE41 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +현재 프로젝트에서 클라이언트와 서버 모두 소켓 통신 부분만 담당하고 있기 때문에, Socket.IO API 를 사용하는 모듈만 독립적으로 관리하는 것이 필수적이었다고 생각합니다. 이제 위와 같이 Nest.js 의 gateway 와 React.js 에서 redux-saga 를 통해 Socket.IO 와 관련된 코드를 별도의 모듈에서 종속성 문제 없이 깔끔하
아 혹시 로컬에서는 제대로 EOL이 들어가 있나요?

2021-11-03 06:17 UTC, SHEELE41 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +현재 프로젝트에서 클라이언트와 서버 모두 소켓 통신 부분만 담당하고 있기 때문에, Socket.IO API 를 사용하는 모듈만 독립적으로 관리하는 것이 필수적이었다고 생각합니다. 이제 위와 같이 Nest.js 의 gateway 와 React.js 에서 redux-saga 를 통해 Socket.IO 와 관련된 코드를 별도의 모듈에서 종속성 문제 없이 깔끔하
제대로 EOL이 들어가 있으면 넣지 말아주세요 Github 웹에서는 다르게 보이는 것 같습니다.

2021-11-03 06:22 UTC, iju1633 commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +현재 프로젝트에서 클라이언트와 서버 모두 소켓 통신 부분만 담당하고 있기 때문에, Socket.IO API 를 사용하는 모듈만 독립적으로 관리하는 것이 필수적이었다고 생각합니다. 이제 위와 같이 Nest.js 의 gateway 와 React.js 에서 redux-saga 를 통해 Socket.IO 와 관련된 코드를 별도의 모듈에서 종속성 문제 없이 깔끔하
<img width="960" alt="1" src="https://user-images.githubusercontent.com/43805087/140016687-737edd32-c0f3-42e9-b0fa-0594a5be6d33.PNG">

EOF 체크를 위해 스크롤한 것을 캡쳐한 화면입니다. 작성자님께서 판단하셔서 commit해주시면 될 거 같습니다!

2021-11-03 10:12 UTC, rxdcxdrnine commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +이전까지 프로젝트를 진행할 때 주로 서버 개발에 참여하면서 Python Django/Flask, Node.js Express, Java Spring 등 여러 언어의 서버사이드 프레임워크를 사용하였습니다. 현재는 가급적이면 현업에서 많이 사용하는 Spring 프레임워크를 기반으로 개발하고자 하지만, 프로젝트를 진행할 때마다 팀 내 상황에 맞춰 언어와 프레임
수정했습니다!

2021-11-03 10:12 UTC, rxdcxdrnine commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +React.js 에서 어플리케이션이 복잡해질수록 컴포넌트에 데이터를 props 로만 넘겨주기 힘들기 때문에, redux 와 같은 SPA (Single Page Application) 전역 상태 관리 라이브러리를 사용합니다. redux 를 사용하는 경우, 상태를 업데이트할 때 비동기 처리를 위한 복잡한 로직을 쉽게 핸들링하기 위해 redux 의 미들웨어를
수정했습니다!

2021-11-03 10:12 UTC, rxdcxdrnine commented on _posts/2021-10-24-Nestjs-Redux-Saga-with-SocketIO.md
> +featured: false
수정했습니다!

2021-11-03 10:15 UTC, iju1633 approved these changes
LGTM :) 👍 👍

2021-11-03 10:34 UTC, SHEELE41 approved these changes
LGTM

2021-11-03 10:34 UTC, merged