모바일팀 10월 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #163
Opened 2021-10-24 14:15 UTC by EGGHEADIARY

10월 모바일팀 블로그 포스팅입니다. 
주제는 안드로이드 아키텍처 구성요소, 역할 알아보기 입니다.

2021-10-26 05:52 UTC, SHEELE41 requested changes
잠깐 확인하면서 수정이 필요한 부분을 적어두었습니다.
중복된 사항에 대해서는 적지 않았으니 참고 바랍니다.

2021-10-26 05:52 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +##intro
```suggestion
## intro
```
#문자 뒤에는 항상 띄어쓰기를 넣어주세요!
Preview를 통해 확인하실 수 있으시겠지만 제목으로 인식을 못합니다 :)

2021-10-26 05:52 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +![viewmodel-lifecycle](https://user-images.githubusercontent.com/90834683/138596571-f284c0eb-92d0-4eee-9187-1932986bef79.png)
사진 링크를 직접 생성하셨군요!
블로그 Repository의 assets 폴더를 이용한 사진 업로드 방법이 아마 contributing.md 파일에 나와 있을 테니 참고 부탁드립니다!

2021-10-27 10:57 UTC, kstew16 commented on _posts/2021-10-24-mobile_AAC.md
> +tags: ["mobile"]
```suggestion
tags: ["Mobile"]
```

2021-10-27 10:57 UTC, kstew16 commented on _posts/2021-10-24-mobile_AAC.md
> +tags: ["mobile"]
태그명 시작 문자를 대문자로 작성해주세요

2021-10-27 10:58 UTC, kstew16 commented on _posts/2021-10-24-mobile_AAC.md
> +image: ![android logo](https://user-images.githubusercontent.com/90834683/138595431-8d89ef7d-b1f4-4a60-afab-cf8035016236.png)
```suggestion
image: ![android logo](https://user-images.githubusercontent.com/90834683/138595431-8d89ef7d-b1f4-4a60-afab-cf8035016236.png)
description: "간단한 설명"
```

2021-10-27 10:59 UTC, kstew16 commented on _posts/2021-10-24-mobile_AAC.md
> +image: ![android logo](https://user-images.githubusercontent.com/90834683/138595431-8d89ef7d-b1f4-4a60-afab-cf8035016236.png)
이미지 아랫줄에 description: "포스팅에 대한 간단한 설명"을 추가해 주세요

2021-10-28 01:44 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +##AAC가 뭘까요
```suggestion
그래서 이번 10월 모바일 포스팅을 통해 안드로이드 개발의 큰 그림, 요즘 트렌드 등을 알 수 있으면 좋겠다는 생각이 듭니다.
##AAC가 뭘까요
```
줄 바꿈은 한 번이나 여러 번이나 차이가 없습니다!

2021-10-28 01:45 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +
```suggestion
(https://velog.io/@hwi_chance/Android-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-AAC)

```
마지막에는 문서의 끝을 알리기 위한 개행 한번 빼고는 다 지워주세요!

2021-10-28 03:43 UTC, EGGHEADIARY commented on _posts/2021-10-24-mobile_AAC.md
> +![viewmodel-lifecycle](https://user-images.githubusercontent.com/90834683/138596571-f284c0eb-92d0-4eee-9187-1932986bef79.png)
contributing.md 파일에 repository assets 폴더 이용한 사진 업로드 방법이 안나와있는 거 같습니다!

2021-10-29 00:33 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +![viewmodel-lifecycle](https://user-images.githubusercontent.com/90834683/138596571-f284c0eb-92d0-4eee-9187-1932986bef79.png)
별건 아니고 커밋할 때 이미지 파일에 대한 커밋도 같이 올리는 거니까 다른 분들 PR(File Changed) 보시면 이해 가실거에요!

2021-10-30 23:20 UTC, EGGHEADIARY commented
피드백해주신 거 바탕으로 고쳤습니다. 고쳐졌을까요..?

2021-11-02 10:40 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +(https://velog.io/@hwi_chance/Android-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-AAC)
```suggestion
(https://velog.io/@hwi_chance/Android-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-AAC)

```
마지막에는 한 줄 띄워주셔야 합니다.

2021-11-03 01:17 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +(https://velog.io/@hwi_chance/Android-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-AAC)
```suggestion
1. [안드로이드 아키텍처 구성요소](https://developer.android.com/topic/libraries/architecture?hl=ko)

2. [[Android] 안드로이드 아키텍쳐 컴포넌트(AAC) - LiveData, Databinding, Room, ViewModel]
(https://4z7l.github.io/2020/09/21/android-aac.html)

3. [[Android] 안드로이드 AAC](https://velog.io/@hwi_chance/Android-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-AAC)
```
미처 신경을 못쓰고 있었는데 링크가 제대로 안 들어가 있는 것 같습니다!

2021-11-03 06:11 UTC, SHEELE41 requested changes
추가 변경 사항

2021-11-03 06:11 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +## AAC가 뭘까요
```suggestion
## AAC가 뭘까요

```
제목 아래 한 줄 띄워주세요 (다른 제목들도)

2021-11-03 06:11 UTC, SHEELE41 commented on _posts/2021-10-24-mobile_AAC.md
> +
```suggestion

```
띄어쓰기 없애주세요 markdownlint 한번 돌려보시고 하이라이트 뜨는 부분 다 적용해주시면 됩니다.

2021-11-04 05:11 UTC, SHEELE41 approved these changes
LGTM!

2021-11-04 08:00 UTC, kstew16 approved these changes

2021-11-04 08:06 UTC, kstew16 approved these changes
LGTM!

2021-11-04 08:23 UTC, kstew16 approved these changes

2021-11-04 08:25 UTC, kstew16 approved these changes
LGTM!

2021-11-04 08:32 UTC, merged