모바일팀 11월 블로그 작성 초고입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #169
Opened 2021-11-14 06:35 UTC by kstew16

2021-11-20 14:51 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
>  ![android-four-major-components](../assets/images/post-mobile-four-major-components-of-AOS/components.png){: width="434" height="400" align="center"}
![image](https://user-images.githubusercontent.com/24821303/142730760-bfa86ec3-60d3-4420-901d-ec962b0cecbf.png)
몇몇 이미지 뒤에 코드가 따라 붙는데 확인 부탁드립니다.

2021-11-20 14:55 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
>  ![activity-stack](../assets/images/post-mobile-four-major-components-of-AOS/activity-stack.png){:align="center"}
![image](https://user-images.githubusercontent.com/24821303/142730877-a734cb35-a96e-44b7-a77a-22157d9d0fc9.png)
이건 사진 자체가 아예 깨지는데 되도록이면 commit 하신 파일 확장자는 소문자로 수정 부탁드립니다. (PNG -> png)

2021-11-20 15:00 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
>        <br>앱이 설치될 때 패키지 관리자가 브로드캐스트를 등록하게 됩니다.
HTML 요소는 쓰지 않을 것을 권장합니다.

2021-11-20 15:05 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
> +안드로이드 어플리케이션은 위에 서술한 구성 요소들을 기술한 코드와 함께 이미지, 오디오 등의 다양한 리소스를 함께 가지고 있습니다.
어플리케이션이라는 발음은 없습니다. 앱 혹은 애플리케이션으로 수정 부탁드려요!

2021-11-20 15:15 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
>  예를 들어 프로젝트의 레이아웃 경로에 포함된 ```activity_main.xml``` 파일은 액티비티의 동작이 아닌 스타일과 색상, 레이아웃 등을 정의하게 됩니다.
요즘은 꼭 그런 것 같지만은 않은 것 같아 보여요... 
```xml
<TextView
   android:text="@{user.lastName}"
   android:layout_width="wrap_content"
   android:layout_height="wrap_content"
   android:visibility="@{user.isAdult ? View.VISIBLE : View.GONE}"/>
```
Databinding이 등장하면서 액티비티와 레이아웃 간의 관계가 너무 가까워졌는데 좀 더 좋은 문장이 있을 것 같네요!

2021-11-20 15:20 UTC, SHEELE41 requested changes
간단하게 리뷰해봤습니다.
중복된 문제는 생략했어요!

2021-11-22 00:24 UTC, kstew16 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
>  ![android-four-major-components](../assets/images/post-mobile-four-major-components-of-AOS/components.png){: width="434" height="400" align="center"}
이거 제 쪽에서 확인이 안 되네요. 일단 다시 한 번 올려 볼게요. 삭제한 것도 있고 하니

2021-11-23 02:05 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
> +  [Android Developers - Application Fundamentals](https://developer.android.com/guide/components/fundamentals)
불필요한 띄어쓰기는 제거해주세요!

2021-11-23 02:10 UTC, SHEELE41 commented on _posts/2021-11-14-mobile-four-major-components-of-AOS.md
> +  개발자가 생성한 액티비티는```AndroidManifest.xml``` 에 ```<activity>``` 요소를 등록한 뒤 인텐트를 생성하여 ```startActivity(Intent)``` 를 통해서 호출할 수 있습니다.
```suggestion
  개발자가 생성한 액티비티는`AndroidManifest.xml` 에 `<activity>` 요소를 등록한 뒤 인텐트를 생성하여 `startActivity(Intent)` 를 통해서 호출할 수 있습니다.
```
인라인 코드는 ` 를 한번만 써 주세요.

2021-11-25 12:02 UTC, EGGHEADIARY commented
늦게 확인하게 되었네요 ㅠ.. 이미지도 잘 보이고, 글도 굉장히 정리가 잘 된 거 같습니다!

2021-11-25 13:42 UTC, SHEELE41 approved these changes
다 수정된 것 같습니다! LGTM!

2021-11-25 13:53 UTC, EGGHEADIARY approved these changes
LGTM !

2021-11-25 14:07 UTC, merged