2021-11-20-AlexNet.md
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #170
Opened 2021-11-21 12:55 UTC by aerojohn1223

2021-11-21 13:34 UTC, SHEELE41 requested changes
사진 파일이 다 빠져있네요 나중에 추가 commit 부탁드립니다 :)
경로도 로컬 기준이 아닌 레포지토리 기준으로 변경 부탁드려요

2021-11-25 07:31 UTC, YubeenSon requested changes
수정 부탁드립니다!

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet.md
> +---
새로운 파일을 만드셨다면 이 파일을 삭제하시고 이 파일명을 남아있는 파일의 파일명으로 바꿔주세요( = changed라는 말을 빼주세요!)

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_imagesincluded.md
> +---
이 파일도 삭제해주세요

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +tags: [딥러닝, CNN, AlexNet]
배열 안의 단어들 ""처리해주세요! ("딥러닝")

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +이 논문에서 사용하는 데이터셋은 ILSVRC에서 제공한 ILSVRC-2010 데이터셋이다. 1000개의 카테고리로 구성되어 있으며, 각 카테고리마다 약 1000개의 사진으로 이루어져 있는 데이터셋이다. 총 약 120만개의 데이터로 구성되어 있다고 한다. 이 중 5만개의 이미지는 validation set로, 그리고 15만개의 이미지는 test set로 활
`만 개의` 형식으로 모두 띄어쓰기 적용해주세요!

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +CIFAR-10 데이터셋에서 ReLU 비선형 활성화함수를 사용했을 때 5번의 이터레이선으로 트레이닝 에러 레이트 25%를 달성할 수 있었던 반면, tanh 비선형 활성화함수를 사용했을 때는35번이 넘는 이터레이션 횟수로 트레이닝 에러 레이트 25%를 달성할 수 있었던 것을 알 수 있습니다.
`때는 35번이`이 형식으로 띄어쓰기 적용해주세요!

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +이렇게 함으로써 1개의 GPU를 사용한 모델들보다 top-1 error rate과 top-5 error rate를 1.7% 그리고 1.2% 줄였다. 또한, 2개의 GPU를 사용한 모델이 한개의 GPU를 사용했을 때보다 학습시간이 조금 더 짧았다.
1.7% 크기만큼 줄였다는 것인가요, 1.7%가 되었다는 뜻인가요?
전자가 맞다면 퍼센트포인트로 변경해주세요!(1.7%p)

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +Local Response Normalization을 사용하여 top1 error rate에서는 1.4%, top5 error rate에서는 1.2%를 줄였다. 또한, CIFAR-10 데이터셋에서 4개의 레이어로 이루어진 CNN에서 정규화 없이 13%의 error rate이 발생했지만, 정규화를 했을 때 error rate는 11%였습니다.
이 부분도 바로 위의 질문과 같습니다. 줄였다는 표현이라면 퍼센트포인트로 바꿔주세요!

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +Overlapping pooling을 했을 때 top1 error rate가 0.4% 줄었고, top5 error rate를 0.3% 줄였다. Overlapping pooling은 오버피팅의 가능성을 조금 감소시키기도 했다.
여기도 있습니다..!!

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +연구에서는 Validation error가 개선되지 않을 때 learning rate을 10으로 나누었다. 초기 learning rate은 0.01이었지만, 3번 변경하여 0.00001이 최적이었음.
얘 혼자만 끝맺음이 ~음인데 다른 문장들과 통일해주세요!

2021-11-25 07:31 UTC, YubeenSon commented on _posts/2021-11-20-AlexNet_images_changed.md
> +ILSVRC 2012에서는 top1에서 40.7을, 그리고 top5에서는 18.2를 달성하였다.
여기도 단위가 퍼센테이지인가요??

2021-11-27 04:59 UTC, ms9648 commented on _posts/2021-11-27-AlexNet.md
> +연구에서는 Validation error가 개선되지 않을 때 learning rate을 10으로 나누었다. 초기 learning rate은 0.01이었지만, 3번 변경하여 0.00001이 최적이었.
문장 마무리가 덜 되었어요!

2021-11-29 09:02 UTC, YubeenSon approved these changes
글 작성하느라 수고 많으셨습니다:)

2021-11-29 09:53 UTC, ms9648 commented
.

2021-11-29 09:53 UTC, ms9648 approved these changes

2021-11-29 09:54 UTC, ms9648 approved these changes

2021-11-29 09:55 UTC, ms9648 approved these changes

2021-11-29 10:04 UTC, ms9648 approved these changes

2021-11-29 10:07 UTC, ms9648 approved these changes

2021-11-29 10:08 UTC, EGGHEADIARY approved these changes
확인했습니다

2021-11-29 10:09 UTC, ms9648 approved these changes
확인했습니다.

2021-11-29 12:18 UTC, SHEELE41 approved these changes
LGTM

2021-11-29 12:18 UTC, merged