2021-11-22-JDBC-JPA.md
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #171
Opened 2021-11-22 11:45 UTC by jminie-o8o

백엔드 팀 블로그 글입니다. 늦어서 죄송합니다 ㅠㅠㅠ

2021-11-22 11:53 UTC, jminie-o8o commented
아 또한 이미지 파일은 커밋이 되지 않아서 따로 추가해놨습니다!

2021-11-23 02:11 UTC, iju1633 requested changes
코드도 첨부해주셔서 이해가 쉽게 되었어요 :)

문장과 문장 사이의 연결만 좀 자연스러워지면 될 것 같아요! comment로 남겨놨습니다 👍

2021-11-23 02:11 UTC, iju1633 commented on _posts/2021-11-22-JDBC-JPA.md
> +- DB와 사용자를 연결시키는 코드를 작성할 때, 데이터베이스의 종류마다 함수명이나 명령문이 다른 경우가 있다 그런 내용들을 단일화 해주고 작업을 편리하게 해주기 위해 JDBC를 사용한다.
DB와 사용자를 연결시키는 코드를 작성할 때, 데이터베이스의 종류마다 함수명이나 명령문이 다른 경우가 있다.
 그런 내용들을 단일화 해주고 작업을 편리하게 해주기 위해 JDBC를 사용한다.

위와 같이 문장을 구분해주시면 좋을 것 같아요!

2021-11-23 02:11 UTC, iju1633 commented on _posts/2021-11-22-JDBC-JPA.md
> +모든 DB에 접근하는 것이 가능하다.
위 문장과 이어주세요 :)

2021-11-23 02:15 UTC, SHEELE41 commented
> 아 또한 이미지 파일은 커밋이 되지 않아서 따로 추가해놨습니다!

이미지 파일은 어디에 추가되어 있는 것인가요...?
만약 fork한 본인 레포지토리에 추가해둔 것이라면 작동하지 않습니다.
이미지 파일 추가하고 commit & push 한번 더 하면 자동으로 이 PR에 commit 추가되니 파일 추가 부탁드립니다!

2021-11-23 02:22 UTC, SHEELE41 requested changes
중복되는 항목에 대해서는 Comment를 생략하였습니다.
확인 부탁드려요!

2021-11-23 02:22 UTC, SHEELE41 commented on _posts/2021-11-22-JDBC-JPA.md
> +<br>
HTML 요소는 사용하지 말아주세요!

2021-11-23 02:22 UTC, SHEELE41 commented on _posts/2021-11-22-JDBC-JPA.md
> +#### 단점
```suggestion
##### 단점
```
장점과 단점의 제목 레벨이 다른데 맞춰주세요!

2021-11-23 02:22 UTC, SHEELE41 commented on _posts/2021-11-22-JDBC-JPA.md
> +
md에서는 몇 줄을 띄우든 동일합니다. 불필요한 줄바꿈은 없애주세요!

2021-11-23 12:32 UTC, jminie-o8o commented
이미지 파일은 계속해서 커밋이 되지 않습니다ㅠ 어떻게 해야 할까요? 커밋할 때 add 자체가 되지 않아요 ㅠ  구글링을 해도 로컬내 저장돼 있는 이미지 파일 자체는 커밋을 지원하지 않는다는 글만 보여서요!ㅠ 그래서 깃허브 자체에 review에다가 첨부를 해놓긴 했는데 해결방법이 있을까요?

2021-11-24 02:43 UTC, SHEELE41 commented
> 이미지 파일은 계속해서 커밋이 되지 않습니다ㅠ 어떻게 해야 할까요? 커밋할 때 add 자체가 되지 않아요 ㅠ 구글링을 해도 로컬내 저장돼 있는 이미지 파일 자체는 커밋을 지원하지 않는다는 글만 보여서요!ㅠ 그래서 깃허브 자체에 review에다가 첨부를 해놓긴 했는데 해결방법이 있을까요?

리뷰에 어떻게 첨부를 해두셨다는 것인지 잘 이해가 가지 않습니다.
git status 명령어를 사용하여 파일이 add 되지 않은 것인지, 혹은 변경 사항 자체로 인식을 못하는 것인지 확인한 후 git add 명령어를 이용하여 파일을 commit 대상에 추가해주세요.
자세한 것은 블로그팀 코어멤버분들께 DM으로 여쭤보시면 잘 알려주실겁니다.

2021-11-24 06:52 UTC, suin0730 requested changes
jpa 없이 jdbc만 사용하면 어떻게 코드를 짜야 하는지  알 수 있어서  도움이 많이 됐습니다! 감사합니다ㅎㅎ 마이너한 부분들만 수정해주시면 좋을 것 같아요!

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +##### 장점
장단점은 마크다운 수준이 #### 아닐까요?

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +- 쿼리문을 통해 데이터베이스를 다룰 수 있는 일반 개발자들은 Oracle 또는 MY SQL의 여러가지 프로그램을 통해 DB에 직접 명령을 내려 데이터를 처리한다.
MY SQL -> MySQL로 변경 부탁드려요

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +- 사용자들이 데이터베이스와 간편히 작업할 수 있도록 만들어진 UI는 코드로 작성된다. 이때 코드 레벨에서 데이터베이스를 사용하기 위한 라이브러리 즉, 쿼리 실행도구 API가 필요한데 이중 Java에서 사용하는 것이 JDBC이다.
첫 문장이 이해되지 않습니다..! 사용자들이 데이터베이스 작업을 간편하게 하기 위해 UI가 만들어졌고, 이 UI는 코드라는 의미인가요? 수동표현 빼고 문장 수정 부탁드려요!

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +여기서 Dao 란 Data Access Object)의 줄임말로 실제로 DB에 접근하는 객체이다.
Data Access Object 뒤에 괄호가 갑자기 닫힙니다!

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +회원가입때와 jdbcTemplate 의 update 메소드를 통해 회원정보를 수정해준다.
회원가입때와 같이..? 라는 의미인가요? 수정 부탁드립니다!

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +- Connection 과 같은 공유 리소르를 제대로 릴리즈 해주지 않으면 시스템 자원이 바닥나는 버그가 발생할 수도 있다.
공유 리소스 오타 수정 부탁드려요!

2021-11-24 06:52 UTC, suin0730 commented on _posts/2021-11-22-JDBC-JPA.md
> +같은 트랜잭션안에서는 같은 엔티티를 반환하기 때문에 데이터 베이스와의 통신 횟수를 줄일 수 있다. 또한, 트랜잭션을 commit하기 전까지 메모리에 쌓고 한번에 SQL을 전송한다.
ㅎㅎ...데이터베이스 붙여주세요

2021-11-24 12:23 UTC, jminie-o8o commented
JDBC를 이용하는 이유는 문장이 다 어색한 것 같고 뒤에 어차피 장단점이 있어서 그냥 제외했습니다!
또 이미지 파일 제가 add를 안찍어 줬더라고요..ㅎㅎ 다시 커밋했습니다!
감사합니다!

2021-11-24 12:27 UTC, jminie-o8o commented
제가 깃허브에 아직 미숙합니다 ㅠ 번거롭게해서 죄송합니다!

2021-11-24 12:29 UTC, iju1633 approved these changes

2021-11-25 07:10 UTC, suin0730 approved these changes

2021-11-25 07:15 UTC, suin0730 approved these changes

2021-11-25 07:17 UTC, suin0730 approved these changes

2021-11-25 13:41 UTC, SHEELE41 approved these changes
저는 딱히 고칠 점이 더 보이지 않네요. LGTM! 고생하셨습니다!

2021-11-25 14:16 UTC, iju1633 approved these changes
LGTM 👍 👍

2021-11-26 00:19 UTC, merged