11월 FE팀 블로그포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #172
Opened 2021-11-24 04:05 UTC by 0inhae0

2021-11-26 10:59 UTC, LeeMir requested changes
고생하셨습니다 👍
심오했던 주제에서 내용을 잘 뽑아내셨네요 ㅎㅎ

잘 쓰셨는데, 블로그 글의 경우 우리가 아닌 다른 사람이 충분히 볼 수 있기 때문에 글 끝에 작성하시면서 참고하셨던 자료들을 같이 올려주시면 다른 분들이 좀 더 이해하기 편할 것 같습니다!

그리고 몇 가지 markdownlint에서 벗어난 부분이 좀 있어서 코멘트 남겼습니다!
VSCode 확장에서 `markdownlint`를 설치하시면 자동으로 어디가 틀렸는 지 잡아주는데요, 한 번 설치해보시는 것도 좋을 것 같습니다! 😄

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +![1200px-WebAssembly_Logo.svg](../assets/images/post-WASM/1200px-WebAssembly_Logo.svg.png)
블로그 보시면 썸네일로 설정한 이미지는 글 상단에 자동으로 첨부가 돼요~!
의도하신 건가요? 👀

![image](https://user-images.githubusercontent.com/42960217/143564879-b2b5dcba-6a5f-4dca-91b1-f39c53772d5c.png)

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +자바스크립트는 인터프리트(interprete) 언어로, 파일을 로딩하려면 브라우저는 `.js` 파일의 텍스트들을 모두 읽어들여야하지만, 웹어셈블리에서는 이미 컴파일되어 있고 이진파일로 된 `wasm`파일만 인터넷을 통해 전송하기 때문에 브라우저에서 로드하는 속도가 더 빠릅니다.
> `wasm` 파일만 인터넷을 통해

.wasm을 적으려고 하신 것 같아요!

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +[출처] 노마드 코더 Nomad Coders
```suggestion
![WasmAndJS.svg](../assets/images/post-WASM/WasmAndJS.PNG)
_[출처] 노마드 코더 Nomad Coders_
```
로 바꾸시면 사진의 주석 형태로 삽입됩니다! `CONTRIBUTING.md`의 `2. 블로그 포스트 작성하기` 참고해주세요!

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +* \* LLVM - 현재 웹어셈블리를 가장 잘 지원하는 컴파일러 도구 모음
```suggestion
* \* LLVM - 현재 웹어셈블리를 가장 잘 지원하는 컴파일러 도구 모음
```

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +자바스크립트는 인터프리트(interprete) 언어로, 파일을 로딩하려면 브라우저는 `.js` 파일의 텍스트들을 모두 읽어들여야하지만, 웹어셈블리에서는 이미 컴파일되어 있고 이진파일로 된 `wasm`파일만 인터넷을 통해 전송하기 때문에 브라우저에서 로드하는 속도가 더 빠릅니다.
```suggestion
자바스크립트는 인터프리트(interprete) 언어로, 파일을 로딩하려면 브라우저는 `.js` 파일의 텍스트들을 모두 읽어들여야하지만, 웹어셈블리에서는 이미 컴파일되어 있고 이진파일로 된 `wasm`파일만 인터넷을 통해 전송하기 때문에 브라우저에서 로드하는 속도가 더 빠릅니다.
```

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +또한, 웹어셈블리는 앱의 보안 측면에서도 강점을 가지고 있습니다. 각 웹어셈블리 어플리케이션은 자체 샌드박스에서 실행되기 때문에, 시스템 내에서 하나라도 변경할 시 무조건 API 또는 다른 의도적인 방법을 통해야만 합니다.
```suggestion
또한, 웹어셈블리는 앱의 보안 측면에서도 강점을 가지고 있습니다. 각 웹어셈블리 어플리케이션은 자체 샌드박스에서 실행되기 때문에, 시스템 내에서 하나라도 변경할 시 무조건 API 또는 다른 의도적인 방법을 통해야만 합니다.
```

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +웹어셈블리는 현재 주요 브라우저들에서 제공이 되고 있는, 자바스크립트 이외의 LLVM에서 제공하는 C, C++, Rust 등의 언어로 만든 저수준 코드들을 사용하여 컴파일할 수 있는 것입니다. 이 때, 하드웨어 기기의 코드에 직접 맵핑되는 것이 아닌 개념상의 기계를 위한 언어입니다.
```suggestion
웹어셈블리는 현재 주요 브라우저들에서 제공이 되고 있는, 자바스크립트 이외의 LLVM에서 제공하는 C, C++, Rust 등의 언어로 만든 저수준 코드들을 사용하여 컴파일할 수 있는 것입니다. 이 때, 하드웨어 기기의 코드에 직접 맵핑되는 것이 아닌 개념상의 기계를 위한 언어입니다.
```

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +끝~~!
```suggestion
끝~~!

```
EOL

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +tags: ["WASM"]
태그는 자유지만, `Web`을 추가해주시면 더 좋을 것 같아요~

2021-11-26 10:59 UTC, LeeMir commented on _posts/2021-11-24-WASM.md
> +2015년부터 개발된 기술로 2017년에 처음으로 발표되었습니다. 현재는 W3C WebAssembly Working group과 Community Group에서 웹 표준으로 개발 되고 있습니다.
별건 아닌데 `group` `Group` 통일하면 더 좋을 것 같아요!

2021-11-26 11:50 UTC, poiu694 reviewed
고생하셨습니다 !

정리하시기 어려웠을 법한 주제인데 정말 정리 잘 해주셨어요 :)

가볍게 몇몇개 코멘트 달아놨습니다 ! 확인해주세요.
+ 저도 문법을 잘 몰라서 확인 못했는데 ㅎㅎ,, 맞춤법 검사기 같은 것으로 띄어쓰기도 전체적으로 봐주시면 좋을 것 같아요 !!

2021-11-26 11:50 UTC, poiu694 commented on _posts/2021-11-24-WASM.md
> +WASM을 사용하면 자바스크립트 이외의 언어(ex. C, C++, Rust 등)를 사용하여 프로그램을 작성한 다음 런타임 이전에 웹어셈블리로 컴파일 할 수 있습니다. 따라서 로드 및 실행이 매우 빠른 웹, 앱을 얻을 수 있습니다.
> 자바스크립트 이외의 언어(ex. C, C++, Rust 등)

ex는 콩글리시 느낌이 있어서 e.g. C, C++ Rust 등 으로 바꾸면 좋을 것 같아요 !

2021-11-26 11:50 UTC, poiu694 commented on _posts/2021-11-24-WASM.md
> +웹어셈블리는 다른 어셈블리 언어들과는 달리 직접적으로 물리적인 기계에 맵핑되기 보다는 개념상의 기계를 위한 언어입니다. 즉, 자바스크립트 언어보다는 훨씬 직접적으로 기계 코드와 맵핑되지만 특정 하드웨어 기기 코드에 맵핑되는 것은 아닙니다.
> 외래어 표기법에 따른 ‘mapping'의 올바른 표기는 ’매핑‘입니다. 

Mapping은 국립 국어원에서 '매핑'이라고 쓰는게 맞다고 하네요 !
혹시 의도하신게 아니라면 바꾸어 주셔도 좋을 것 같아요 :)

2021-11-26 11:50 UTC, poiu694 commented on _posts/2021-11-24-WASM.md
> +예를 들어, 자바스크립트는 포토샵, 프리미어 프로와 같이 사진/영상 작업(image processing)을 하기에는 매우 어렵고 느리다는 단점을 가집니다. 그러나 웹어셈블리 덕분에 포토샵 등을 브라우저에서 바로 돌릴 수 있게 되어 컴퓨터에 프로그램을 설치하지 않을 수 있게 될 것입니다. 또한 , 사진/영상작업 툴 이외에도 게임을 브라우저로 실행시킬 수 있
> 또한 ,

공백 의도하신것 같기도 한데 다른 반점쓰신 부분과 통일되게 붙여도 좋을 것 같아요 !

2021-11-26 11:50 UTC, poiu694 commented on _posts/2021-11-24-WASM.md
> +현재까지는 아직 자바스크립트를 사용하지 않고 웹어셈블리로만 웹 혹은 앱을 제작하기에는 부족한 부분이 있지만, 이를 차차 발전해나간다면 성능면에서나 사용범위면에서나 프론트엔드 개발자들에게 충분히 매력적인  코드로써 작용할 수 있다고 생각합니다.
```suggestion
현재까지는 아직 자바스크립트를 사용하지 않고 웹어셈블리로만 웹 혹은 앱을 제작하기에는 부족한 부분이 있지만, 이를 차차 발전해나간다면 성능면에서나 사용범위면에서나 프론트엔드 개발자들에게 충분히 매력적인 코드로써 작용할 수 있다고 생각합니다.

2021-11-29 03:27 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +![1200px-WebAssembly_Logo.svg](../assets/images/post-WASM/1200px-WebAssembly_Logo.svg.png)
앗 아뇨! 수정하겠습니다!!

2021-11-29 03:27 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +자바스크립트는 인터프리트(interprete) 언어로, 파일을 로딩하려면 브라우저는 `.js` 파일의 텍스트들을 모두 읽어들여야하지만, 웹어셈블리에서는 이미 컴파일되어 있고 이진파일로 된 `wasm`파일만 인터넷을 통해 전송하기 때문에 브라우저에서 로드하는 속도가 더 빠릅니다.
수정하겠습니다~!

2021-11-29 03:28 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +[출처] 노마드 코더 Nomad Coders
오호 감사합니다~!~!

2021-11-29 03:30 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +tags: ["WASM"]
넵!

2021-11-29 03:30 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +2015년부터 개발된 기술로 2017년에 처음으로 발표되었습니다. 현재는 W3C WebAssembly Working group과 Community Group에서 웹 표준으로 개발 되고 있습니다.
앗 그러네요! 수정하겠습니다~!

2021-11-29 03:31 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +WASM을 사용하면 자바스크립트 이외의 언어(ex. C, C++, Rust 등)를 사용하여 프로그램을 작성한 다음 런타임 이전에 웹어셈블리로 컴파일 할 수 있습니다. 따라서 로드 및 실행이 매우 빠른 웹, 앱을 얻을 수 있습니다.
아하! 수정하겠습니다~!

2021-11-29 03:31 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +웹어셈블리는 다른 어셈블리 언어들과는 달리 직접적으로 물리적인 기계에 맵핑되기 보다는 개념상의 기계를 위한 언어입니다. 즉, 자바스크립트 언어보다는 훨씬 직접적으로 기계 코드와 맵핑되지만 특정 하드웨어 기기 코드에 맵핑되는 것은 아닙니다.
오 알겠습니당

2021-11-29 03:31 UTC, 0inhae0 commented on _posts/2021-11-24-WASM.md
> +예를 들어, 자바스크립트는 포토샵, 프리미어 프로와 같이 사진/영상 작업(image processing)을 하기에는 매우 어렵고 느리다는 단점을 가집니다. 그러나 웹어셈블리 덕분에 포토샵 등을 브라우저에서 바로 돌릴 수 있게 되어 컴퓨터에 프로그램을 설치하지 않을 수 있게 될 것입니다. 또한 , 사진/영상작업 툴 이외에도 게임을 브라우저로 실행시킬 수 있
의도한거 아니예요 ㅠ.ㅠ 알겠습니다!

2021-11-30 10:51 UTC, 0inhae0 commented
11월 포스팅

2021-11-30 13:23 UTC, LeeMir approved these changes
LGTM 👍

2021-11-30 13:24 UTC, ms9648 approved these changes

2021-11-30 13:25 UTC, merged