DA/ML팀 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #179
Opened 2022-01-23 07:02 UTC by ms9648

2022-01-30 13:26 UTC, YubeenSon requested changes
매우 기네요..!! 작성하느라 수고 많으셨어요
두 부분 확인 부탁드립니다!

2022-01-30 13:26 UTC, YubeenSon commented on _posts/2022-01-22-Youtube-Algorithm.md
> +위 식은 softmax 함수로, 특정 시간 t에 유저 U가 C라는 context를 가지고 있을 때 각각의 동영상 vi를 볼 확률을 정의한 것입니다.
vi 말고 첨자로 표시가 가능할거에요!아래첨자로 변경 부탁드려요!

2022-01-30 13:26 UTC, YubeenSon commented on _posts/2022-01-22-Youtube-Algorithm.md
> +![image](../assets/images/post-Youtube-Algorithm/selection_bias.png){:.align-right}
vscode 마크다운으로 확인해보면 `{:.align-right}`부분이 그대로 노출되는데 확인 부탁드려요!

2022-01-31 03:44 UTC, ms9648 commented on _posts/2022-01-22-Youtube-Algorithm.md
> +![image](../assets/images/post-Youtube-Algorithm/selection_bias.png){:.align-right}
블로그 구동해보면 노출이 안되긴 한데, 기능이 제대로 작동하지 않는것같으니 삭제하겠습니다!

2022-01-31 05:29 UTC, YubeenSon requested changes
한 부분만 수정 부탁드립니다..!!

2022-01-31 05:29 UTC, YubeenSon commented on _posts/2022-01-22-Youtube-Algorithm.md
> +위 식은 softmax 함수로, 특정 시간 $$ t $$ 에 유저 $$ U $$ 가 $$ C $$라는 context를 가지고 있을 때 각각의 동영상 $$ v_i $$를 볼 확률을 정의한 것입니다.
vscode 마크다운 미리보기로 보니까 각각의 기호가 한 줄을 차지하고 있더라구요
$$ t $$ 가 아니라 $ t $ 이렇게 하나로 감싸면 한 줄 안에 작성 가능할거에요!

2022-01-31 06:55 UTC, ms9648 commented on _posts/2022-01-22-Youtube-Algorithm.md
> +위 식은 softmax 함수로, 특정 시간 $$ t $$ 에 유저 $$ U $$ 가 $$ C $$라는 context를 가지고 있을 때 각각의 동영상 $$ v_i $$를 볼 확률을 정의한 것입니다.
앗 감사합니다. 수정했습니다. 더불어 softmax함수에 오타가 나서 하나 수정했습니다!

2022-02-03 11:44 UTC, YubeenSon approved these changes
늦어서 죄송합니다ㅠㅠ
고생 많으셨습니다!!

2022-02-03 13:17 UTC, merged