12월 FE 블로그 PR
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #180
Opened 2022-01-23 16:59 UTC by JihamSong

2022-01-24 05:16 UTC, poiu694 commented
필력이 너무 좋네요.....

고생하셨습니다 !

2022-01-28 12:48 UTC, poiu694 submitted a review, later dismissed
LGTM :)

다시보는데도 글이 너무 좋네요! 고생하셨습니다

2022-01-31 14:27 UTC, LeeMir commented
아이코 저도 저번에 읽어 놓고 이제 코멘트 남기는 건데, 글 너무 잘 써주신 것 같아요!!

일단 아래 링크는 실제 블로그에 글이 올라갔을 때 어떻게 올라가는 지 제 로컬 환경에서 캡쳐한 것입니다!
[이미지 링크](https://user-images.githubusercontent.com/42960217/151808411-87f1d0c7-6d65-4d57-ab62-6d19ec18c2e6.png)

보시면 중간에 JWT 예시가 ` ``` ``` ` 코드 블럭 안에 들어가 있어서 가로 스크롤이 생기면서 이게 뭔지 직관적으로 알기 힘든 부분이 있는데, `.` 기준으로 줄바꿈을 한다든지 이것도 이미지 캡처로 바꾸든지 해주셔서 최대한 스크롤이 안생기게, 그리고 이것이 JWT의 예시임을 드러내주시면 더 좋을 것 같아요!

그 외에는 너무 완벽해서 한 가지 숟가락만 얹자면 글 중간 중간 가독성 있게 진하게라든지 색깔을 입힌다든지(블로그에서는 ` `` `이 안에 글을 넣으면 분홍색이 입혀집니다!) 잘 해주셨는데 특히 글 뒷부분이 잘 안돼있더라구요! 이것만 보충해주시면 정말 완벽 그 자체인 글이 되지 않을까 조심스레 코멘트 남겨봅니다!

2022-01-31 14:27 UTC, LeeMir requested changes
아이코 저도 저번에 읽어 놓고 이제 코멘트 남기는 건데, 글 너무 잘 써주신 것 같아요!!

일단 아래 링크는 실제 블로그에 글이 올라갔을 때 어떻게 올라가는 지 제 로컬 환경에서 캡쳐한 것입니다!
[이미지 링크](https://user-images.githubusercontent.com/42960217/151808411-87f1d0c7-6d65-4d57-ab62-6d19ec18c2e6.png)

보시면 중간에 JWT 예시가 ` ``` ``` ` 코드 블럭 안에 들어가 있어서 가로 스크롤이 생기면서 이게 뭔지 직관적으로 알기 힘든 부분이 있는데, `.` 기준으로 줄바꿈을 한다든지 이것도 이미지 캡처로 바꾸든지 해주셔서 최대한 스크롤이 안생기게, 그리고 이것이 JWT의 예시임을 드러내주시면 더 좋을 것 같아요!

그 외에는 너무 완벽해서 한 가지 숟가락만 얹자면 글 중간 중간 가독성 있게 진하게라든지 색깔을 입힌다든지(블로그에서는 ` `` `이 안에 글을 넣으면 분홍색이 입혀집니다!) 잘 해주셨는데 특히 글 뒷부분이 잘 안돼있더라구요! 이것만 보충해주시면 정말 완벽 그 자체인 글이 되지 않을까 조심스레 코멘트 남겨봅니다!

2022-02-02 13:33 UTC, JihamSong commented
> 아이코 저도 저번에 읽어 놓고 이제 코멘트 남기는 건데, 글 너무 잘 써주신 것 같아요!!
> 
> 일단 아래 링크는 실제 블로그에 글이 올라갔을 때 어떻게 올라가는 지 제 로컬 환경에서 캡쳐한 것입니다! [이미지 링크](https://user-images.githubusercontent.com/42960217/151808411-87f1d0c7-6d65-4d57-ab62-6d19ec18c2e6.png)
> 
> 보시면 중간에 JWT 예시가 `` ``` ``` `` 코드 블럭 안에 들어가 있어서 가로 스크롤이 생기면서 이게 뭔지 직관적으로 알기 힘든 부분이 있는데, `.` 기준으로 줄바꿈을 한다든지 이것도 이미지 캡처로 바꾸든지 해주셔서 최대한 스크롤이 안생기게, 그리고 이것이 JWT의 예시임을 드러내주시면 더 좋을 것 같아요!
> 
> 그 외에는 너무 완벽해서 조금만 욕심을 더 내자면 글 중간 중간 가독성 있게 진하게라든지 색깔을 입힌다든지(블로그에서는 `` `` ``한 단어짜리 코드 블럭에 글을 넣으면 분홍색이 입혀집니다!) 잘 해주셨는데 특히 글 뒷부분이 잘 안돼있더라구요! 이것만 보충해주시면 정말 완벽 그 자체인 글이 되지 않을까 조심스레 코멘트 남겨봅니다!

2022-02-02 14:02 UTC, LeeMir approved these changes
LGTM :)

2022-02-02 14:03 UTC, merged