Post/happiesoo41
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #183
Opened 2022-01-24 04:42 UTC by happiesoo41

DATA/ML팀 1월 블로그입니다

2022-01-25 11:44 UTC, ms9648 commented
이미지가 안올라왔어요..!
![image](https://user-images.githubusercontent.com/43836180/150971040-f3e2e73f-87f5-4ea1-b1b0-e773d3760d3a.png)
이미지도 같이 커밋해주세요.

2022-01-30 13:01 UTC, YubeenSon requested changes
피드백과 질문사항들이 있습니다! 
보완과 답변 부탁드립니다!

2022-01-30 13:01 UTC, YubeenSon commented on _posts/2022-01-23-object-detection.md
> +3)	남은 box 중 가장 큰 p를 갖는 박스를 고른다 => output
1, 2, 4번과 같이 말 끝부분 맞춰주세요!

2022-01-30 13:01 UTC, YubeenSon commented on _posts/2022-01-23-object-detection.md
> +예를 들어 2by2 feature를 추출한다면 ROI feature map이 2by2로 적절히 나누어지도록 하기 위해 왼쪽 그림처럼 나누고 각 부분마다 가장 큰 값을 고릅니다.
혹시 이 부분의 왼쪽 그림이 무엇인가요?? 이미지를 가리키는 말을 바꾸거나 이미지를 추가해주세요!

2022-01-30 13:01 UTC, YubeenSon commented on _posts/2022-01-23-object-detection.md
> +물체 위치 상당히 정확하게 예측하는 결과를 보여주었습니다.
이 부분 안에 단어들이 끊겨 조사가 빠진 부분들이 있는데 이 부분 보완 부탁드려요!

2022-01-30 13:01 UTC, YubeenSon commented on _posts/2022-01-23-object-detection.md
> +물체 위치 상당히 정확하게 예측하는 결과를 보여주었습니다.
+ 추가로 나열된 단어들 사이 컴마도 부탁드려요..!

2022-01-30 13:01 UTC, YubeenSon commented on _posts/2022-01-23-object-detection.md
> +왼쪽 가운데 오른쪽과 같이, 입력의 위치가 바뀌어도 결과는 같은 동상이라고 인식하는 것을 의미합니다.
이해가 안 되어서 질문 드리는데 translation invariant가 faster-rcnn의 특성이라는 뜻인가요??
별개의 내용처럼 느껴져 질문드립니다!

2022-01-30 13:01 UTC, YubeenSon commented on _posts/2022-01-23-object-detection.md
> +즉 pyramid 형식의 anchor라고 볼 수 있습니다.
이 부분도 위의 질문과 같이 faster-rcnn의 특성과 관련되어있는 것인가요?

2022-01-30 13:02 UTC, YubeenSon commented
추가로 File Changed에 이미지 파일들이 안 올라와 있어요
경로는 잘 설정되어 있던데 해당 경로에 폴더 생성하고 이미지도 같이 올려주세요!

2022-02-03 11:47 UTC, YubeenSon requested changes
수연님 이미지 파일들은 images/post-블로그 글 제목/no.png 형태의 파일구조로 부탁드려요!
지금 보면 images안에 파일들이 다 들어가있어요!

2022-02-06 08:17 UTC, YubeenSon approved these changes
수고많으셨습니다:)!!

2022-02-09 02:27 UTC, ms9648 approved these changes

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +# Object Dection
Object Detection으로 치시다 오타난 것 같아요!

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +먼저 Object dection은 Classification과 Regression(물체의 위치를 찾는 문제) 2개의 문제로 이루어져 있습니다.
여기도 수정 해야할 것 같습니당

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +먼저 1-stage는 분류와 위치 문제를 한번에 해결하는 방식으로 대표적인 알고리즘으로 yolo가 있습니다.
```suggestion
먼저 1-stage는 분류와 위치 문제를 한 번에 해결하는 방식으로 대표적인 알고리즘으로 yolo가 있습니다. 
```

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +4)	3)에서 나온 박스들 중 IoU가 0.5이상인 어떤 박스가 있다면 모두 버립니다.
```suggestion
4)	3)에서 나온 박스들 중 IoU가 0.5 이상인 어떤 박스가 있다면 모두 버립니다.
```

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +R-CNN은 CNN을 이용하여 각 Region의 class를 분류하는 가장 기본이 되는 아키텍처 입니다.
```suggestion
R-CNN은 CNN을 이용하여 각 Region의 class를 분류하는 가장 기본이 되는 아키텍처입니다.
```

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +또 SVM, Regressor 모듈이 분리되어 있어서 SVM과 바운딩 박스 regression으로 CNN을 업데이트하는 것이 불가능 합니다. 즉 end-to-end 방식으로 학습할 수 없습니다.
```suggestion
또 SVM, Regressor 모듈이 분리되어 있어서 SVM과 바운딩 박스 regression으로 CNN을 업데이트하는 것이 불가능합니다. 즉 end-to-end 방식으로 학습할 수 없습니다.
```

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +Fast R-CNN은 R-CNN과 달리 이미지를 CNN에 한번만 넣어서 Feature map을 생성합니다.
```suggestion
Fast R-CNN은 R-CNN과 달리 이미지를 CNN에 한 번만 넣어서 Feature map을 생성합니다.
```

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +한장의 image를 convolution layer에 넣어서 feature map을 만들고
```suggestion
한 장의 image를 convolution layer에 넣어서 feature map을 만들고
```

2022-02-09 02:27 UTC, ms9648 commented on _posts/2022-01-23-object-detection.md
> +image: ../assets/images/post-object-detection/thumbnail.png
썸네일 사진이 누락되었나봐요. 다른 이미지는 잘 올라오니 썸네일 사진만 추가해주시기 바랍니다.

2022-02-09 02:28 UTC, merged