solbat
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #197
Opened 2022-02-20 10:42 UTC by solbat

2022-02-23 09:28 UTC, YubeenSon requested changes
피드백 사항이 많지 않습니다!
수정 부탁드려요:>

2022-02-23 09:28 UTC, YubeenSon commented on _posts/2022-02-20-Named-Entity-Recognition.md
> +논문[]에서 딥러닝 기반 개체명 인식(NER) 모델의 구조를 다음과 같이 세 단계로 나누어 설명한다.
혹시 이 부분 대괄호가 비어있어 미완성된 것 같습니다!

2022-02-23 09:28 UTC, YubeenSon commented on _posts/2022-02-20-Named-Entity-Recognition.md
> +1. **자동으로 feature들을 추출하기 때문에 비용이 감소한다.**
여기부터 ~습니다서 ~이다 로 바꼈는데 글 전체 어미 통일해주세요:)

2022-02-23 09:28 UTC, YubeenSon commented on _posts/2022-02-20-Named-Entity-Recognition.md
> +1. https://arxiv.org/abs/1812.09449
이 부분이 로컬에서 돌려보면 하이퍼링크로 살아있지 않아요. 다른 포스트 보고 이거 링크 살려서 수정해주세요!

2022-02-24 09:18 UTC, YubeenSon approved these changes
수고많으셨습니다:>!!

2022-03-01 04:34 UTC, ms9648 approved these changes
고생하셨습니다!

2022-03-01 04:35 UTC, merged