BE 2월 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #198
Opened 2022-02-21 07:21 UTC by iju1633

2022-03-01 08:13 UTC, suin0730 requested changes
REST API에 대해서 이렇게 깊게 들어간 자료를 보는 것은 처음이네요..! 저도 해당 영상을 볼 필요를 크게 느꼈습니다. 좋은 글 감사합니다!!!
일부 글 형식에 대한 commet를 남겼는데, 수정하실 때 가볍게 맞춤법 검사기도 돌려보시는 것 추천드려요! 너무 늦게 리뷰를 남겨 죄송합니다ㅠㅠ

2022-03-01 08:13 UTC, suin0730 commented on _posts/2022-02-21-Rest-Api.md
> +
이 아래 세 단락이 조금 더 잘 이어질 수 있을 것 같아서 "그럼 이제 어떻게 해야할까"를 조금 더 구체적인 제목으로 바꾸는 것 제안드립니다! 아래는 간단하게 생각해 본 예시입니다.

## 현재 상황에서 개발자가 할 수 있는 것
- HTTP API를 구현합니다.
- REST API가 아닌 것을 REST API라 부릅니다. (현재 상황)
- 아래 사항들을 만족시켜 REST API를 온전히 구현합니다.
    - self-descriptive
    - HATEOAS
## Self-descriptive와 HATEOAS를 만족시키는 방법
{중략}
## 그럼 REST API로 ....{중략}

2022-03-01 08:13 UTC, suin0730 commented on _posts/2022-02-21-Rest-Api.md
> +<br/>
html 태그가 마크다운 문서 내부에 들어가면 안된다는 markdownlint 규칙이 있었던 것 같습니다..! MD033 참고 부탁드려요!

2022-03-01 08:13 UTC, suin0730 commented on _posts/2022-02-21-Rest-Api.md
> +        - ex. 웹 페이지를 변경했다고 웹 브라우저를 업데이트할 필요가 없습니다.
ex. 를 e.g. 으로 변경 부탁드립니다!

2022-03-01 08:13 UTC, suin0730 commented on _posts/2022-02-21-Rest-Api.md
> +## REST가 웹의 독립적 진화에 도움을 주었나
REST가 어떤 면에서 웹의 독립적인 진화에 도움을 주었다고 할 수 있는가..? 와 같이 하위 내용을 포괄할 수 있는 제목도 좋을 것 같아요! 현재 제목은 O, X로 대답할 수 있을 것 같아서요..!!

2022-03-01 08:13 UTC, suin0730 commented on _posts/2022-02-21-Rest-Api.md
> +- Media type 변경
125, 126, 127, 128, 141 줄 표기를 Media type, 미디어 타입, 미디어 type 중 한 표기로 통일하면 더 읽기 쉬울 것 같습니다.

2022-03-01 09:26 UTC, iju1633 commented on _posts/2022-02-21-Rest-Api.md
> +
적절한 예시까지 정말 감사드립니다!

2022-03-01 09:26 UTC, iju1633 commented on _posts/2022-02-21-Rest-Api.md
> +<br/>
피드백 감사드립니다. 태그 모두 제거했습니다.

2022-03-01 09:26 UTC, iju1633 commented on _posts/2022-02-21-Rest-Api.md
> +        - ex. 웹 페이지를 변경했다고 웹 브라우저를 업데이트할 필요가 없습니다.
피드백 감사드립니다. 수정 했습니다!

2022-03-01 09:27 UTC, iju1633 commented on _posts/2022-02-21-Rest-Api.md
> +## REST가 웹의 독립적 진화에 도움을 주었나
덕분에 블로그 문맥이 좀 더 매끄러워진 것 같습니다. 피드백 감사드립니다!

2022-03-01 09:27 UTC, iju1633 commented on _posts/2022-02-21-Rest-Api.md
> +- Media type 변경
감사합니다! 표현 통일 완료했습니다!

2022-03-01 09:34 UTC, suin0730 submitted a review, later dismissed

2022-03-01 09:34 UTC, suin0730 commented
@iju1633 빠른 수정 감사합니다! 고생 많으셨어요 :+1:

2022-03-02 13:49 UTC, suin0730 approved these changes

2022-03-02 15:53 UTC, ms9648 approved these changes
고생하셨습니다!

2022-03-02 15:53 UTC, merged