DA/ML팀 3월 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #208
Opened 2022-03-20 07:26 UTC by ms9648

추천 시스템 알고리즘 중 sgd를 병렬로 처리하여 최적화하는 방식인 FPSGD 알고리즘을 중심으로 소개하였습니다.

2022-03-22 13:22 UTC, happiesoo41 reviewed
고생 많으셨습니당!!

2022-03-22 13:22 UTC, happiesoo41 commented on _posts/2022-03-18-FPSGD.md
> +[추천시스템 학회](https://recsys.acm.org/)를 둘러보다가 <b>A fast parallel SGD for matrix factorization in shared memory systemss</b>라는 논문을 읽어봤습니다.
논문 제목 마지막에 s가 하나 더 들어갔어요

2022-03-22 13:22 UTC, happiesoo41 commented on _posts/2022-03-18-FPSGD.md
> +아래 그림에서 R은 사용자와 아이템으로 이루어진 rating matrix입니다. 이는 M명의 사용자가 N개의 아이템에 대해 평가한 데이터를 포함하고 있는 2차원 행렬입니다. 행렬의 각 원소는 사용자가 아이템에 대해 평가한 평점만을 가지고 있으며, 그 외의 값은 결측치로 이루어져있습니다.
마지막 부분 띄어쓰기 확인해주세요~

2022-03-24 15:47 UTC, custardcream98 requested changes
정말 고생 많으셨습니다!

2022-03-24 15:47 UTC, custardcream98 commented on _posts/2022-03-18-FPSGD.md
> +2. Memory Discontinuity
이부분 한 줄을 1번처럼 띄워주어야 제대로 나오네요!

2022-03-25 12:50 UTC, ms9648 commented
에고 지금 봤네요..! 수정해서 올리도록 하겠습니다!

2022-03-30 01:37 UTC, custardcream98 approved these changes
고생하셨습니다!ㅎㅎㅎ

2022-03-30 01:37 UTC, custardcream98 commented on _posts/2022-03-18-FPSGD.md
> +2. Memory Discontinuity
수정 확인했습니다!

2022-03-31 13:40 UTC, merged