7월 프론트 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #225
Opened 2022-07-23 15:14 UTC by pasly0920

7월 프론트 블로그 포스팅 작성했습니다.

2022-07-28 10:48 UTC, LeeMir requested changes
[미리 보기](https://user-images.githubusercontent.com/42960217/181487046-a7ccf57f-739c-4be9-84f6-c74da2239b67.png)

잘 읽었습니다! 모순적이게도 객체 자체는 굉장히 자유로운 개념 같은데 사람들은 얘를 보수적으로 동결시키고 밀봉하네요 😅
JS의 내부 작동이면 `prototype`도 다뤄야하는데 글 하나 더 써주시나요? 🤣🤣

오탈자랑 중간에 `~이다.` `~입니다.` 섞인 부분만 통일해주시면 될 것 같아요! 고생하셨어요 👍

2022-07-28 10:48 UTC, LeeMir commented on _posts/2022-07-23-PropertyAttribute.md
> +프로포타입에 대해서는 추후 19장에서 다루도록 하겠습니다.
👀

2022-07-28 10:48 UTC, LeeMir commented on _posts/2022-07-23-PropertyAttribute.md
> +프로퍼티 정의란 새로운 프로퍼티를 추가하면서 프로퍼티 어트리뷰트를 명시적으로 정의하거나, 기존 프로퍼티의 프로퍼티 어트리뷰트를 재정의하는 것을 의미합니다. 예를 들얼 프로퍼티 값을 갱신 가능하도록 할 것인지 등에 대한 정의를 하는 것입니다. 이를 통해 객체의 프로퍼티가 어떻게 동작해야 하는지를 명확히 정의할 수 있습니다.
👀

2022-07-28 10:48 UTC, LeeMir commented on _posts/2022-07-23-PropertyAttribute.md
> +> value
얘도 Value로 통일해주는게 어떨까용

2022-07-29 02:35 UTC, pasly0920 commented
수정했습니다! 긴 글인데 읽어주셔서 감사합니다

2022-07-29 06:28 UTC, LeeMir commented
@pasly0920 comment 달려있는 부분도 확인해주세요~

2022-07-29 07:11 UTC, poiu694 reviewed
딥다이브.. 마저 읽어야 하는데..ㅎ...

간단하게 남겨보았습니당

2022-07-29 07:11 UTC, poiu694 commented on _posts/2022-07-23-PropertyAttribute.md
> +Object.getOwnPropertyDescriptor 메서드가 반환한 프로퍼티 디스크립터 객체를 살펴보면 value 프로퍼티의 값은 'Lee'로 이것은 프로퍼티 어트리뷰트 [[Value]]의 값이 'Lee'임을 의미한다. writeable, enumerable, configurable 모두 true인 것은 [[Writeable]], [[Enumerab
```suggestion
Object.getOwnPropertyDescriptor 메서드가 반환한 프로퍼티 디스크립터 객체를 살펴보면 value 프로퍼티의 값은 'Lee'로 이것은 프로퍼티 어트리뷰트 [[Value]]의 값이 'Lee'임을 의미한다. writeable, enumerable, configurable 모두 true인 것은 [[Writeable]], [[Enumerable]], [[Configurable]]이 모두 true임을 의미한다. 이처럼 프로퍼티가 생성될 때 [[Value]]의 값은 프로퍼티 값을 초기화되며 [[Writeable]], [[Enumerable]], [[Configurable]]은 true로 초기화된다. 이는 프로퍼티를 동적 추가해도 동일하게 적용된다. 데이터 프로퍼티의 속성 정리는 위의 속성 정리를 참고하면 된다.
```

2022-07-29 07:11 UTC, poiu694 commented on _posts/2022-07-23-PropertyAttribute.md
> +description: "JS는 어떻게 내부적으로 작동하는가?"
description 을 조금 더 구체화 시키는것은 어떨까요?

내부적으로 동작이라고 하면, 프로퍼티 부분말고도 다룰 수 있는 부분이 너무 많아보여서요!

2022-07-29 07:11 UTC, poiu694 commented on _posts/2022-07-23-PropertyAttribute.md
> +프로포타입에 대해서는 추후 19장에서 다루도록 한다.
```suggestion
프로토타입에 대해서는 추후 19장에서 다루도록 한다.
```

오타도 있긴 한데, 19장에서 다룬다는 거는 다음 글도 바로 올라온다는 얘기일까요?_?

2022-07-29 07:29 UTC, pasly0920 commented on _posts/2022-07-23-PropertyAttribute.md
> +프로포타입에 대해서는 추후 19장에서 다루도록 한다.
제 개인 책 공부하는 데서 가져오다 보니 수정이 덜 됬네요 ㅜㅜ 수정하겠습니다.

2022-07-29 07:33 UTC, pasly0920 commented
수정했습니다!

2022-07-29 08:01 UTC, LeeMir commented on _posts/2022-07-23-PropertyAttribute.md
> +프로퍼티 정의란 새로운 프로퍼티를 추가하면서 프로퍼티 어트리뷰트를 명시적으로 정의하거나, 기존 프로퍼티의 프로퍼티 어트리뷰트를 재정의하는 것을 의미합니다. 예를 들얼 프로퍼티 값을 갱신 가능하도록 할 것인지 등에 대한 정의를 하는 것입니다. 이를 통해 객체의 프로퍼티가 어떻게 동작해야 하는지를 명확히 정의할 수 있습니다.
@pasly0920 이것도 좀 봐주세요 엉엉

2022-07-29 12:51 UTC, poiu694 submitted a review, later dismissed
LGTM :)

2022-07-31 11:13 UTC, LeeMir requested changes
@pasly0920 

comment 달았던 부분 아직 수정 안된 것 같은데 부탁드립니다~

2022-07-31 11:43 UTC, pasly0920 commented on _posts/2022-07-23-PropertyAttribute.md
> +Object.defineProperty 메서드를 사용하면 프로퍼티의 어트리뷰트를 정의할 수 있다. 인수로는 객체의 참조와 데이터 프로퍼티의 키, 프로퍼티 디스크립터 객체를 전달한다.
@LeeMir 이 부분 수정 추가로 해달라는 말씀이실까요? 혹시 어떤 부분이 부족한 지 한 번만 더 알려주시면 바로 수정하도록 하겠습니다 감사합니다.

2022-08-01 12:43 UTC, LeeMir commented on _posts/2022-07-23-PropertyAttribute.md
> +Object.defineProperty 메서드를 사용하면 프로퍼티의 어트리뷰트를 정의할 수 있다. 인수로는 객체의 참조와 데이터 프로퍼티의 키, 프로퍼티 디스크립터 객체를 전달한다.
😃 
```suggestion
프로퍼티 정의란 새로운 프로퍼티를 추가하면서 프로퍼티 어트리뷰트를 명시적으로 정의하거나, 기존 프로퍼티의 프로퍼티 어트리뷰트를 재정의하는 것을 의미한다. 예를 들어 프로퍼티 값을 갱신 가능하도록 할 것인지 등에 대한 정의를 하는 것이다. 이를 통해 객체의 프로퍼티가 어떻게 동작해야 하는지를 명확히 정의할 수 있다.

Object.defineProperty 메서드를 사용하면 프로퍼티의 어트리뷰트를 정의할 수 있다. 인수로는 객체의 참조와 데이터 프로퍼티의 키, 프로퍼티 디스크립터 객체를 전달한다.
```

2022-08-01 12:55 UTC, pasly0920 commented on _posts/2022-07-23-PropertyAttribute.md
> +Object.defineProperty 메서드를 사용하면 프로퍼티의 어트리뷰트를 정의할 수 있다. 인수로는 객체의 참조와 데이터 프로퍼티의 키, 프로퍼티 디스크립터 객체를 전달한다.
왜 제가 이걸 못 봤을 까요
ㅜㅜㅜ 수정했습니다

2022-08-01 13:02 UTC, LeeMir approved these changes
LGTM ㅎㅎ

2022-08-05 04:04 UTC, ms9648 approved these changes

2022-08-05 04:04 UTC, merged