6월 BE 블로그 포스팅입니다
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #229
Opened 2022-07-24 12:37 UTC by qf9ar8nv

2022-07-25 00:14 UTC, iju1633 commented on _posts/2022-07-24-websocket.md
> +WebSocket의 특성 상 한번 연결이 될 때 HTTP protocol을 사용하기 때문에 인증, 인가를 해당 url에 맞춰서 적용해주면 됩니다. 그럼 정상적으로 인증이 되지만 이 후 커넥션이 끊어지지 않는다면 따로 인증 과정을 수행하지 않습니다. 커넥션이 연결될 따 이미 인증이 끝난 상태로 가정하기 때문에 중복해서 인증 할 필요가 없다고 가정합니다.
"커넥션이 연결될 따" -> "커넥션이 연결될 때"
오타가 있어 수정해주시면 감사하겠습니다!

2022-07-25 00:21 UTC, iju1633 commented on _posts/2022-07-24-websocket.md
> +SSE는 Server에서 발생하는 이벤트를 Client에 제공하기 위한 방법입니다. Client에서 Server로 먼저 Request를 보내면 streaming을 위한 연결이 생성됩니다. 이를 통해 Server에서 이벤트가 발생할 때 마다 연결된 Client에게 데이터를 전달 할 수 있습니다.
"전달 할 수 있습니다." -> "전달할 수 있습니다."

수정 부탁드리겠습니다^^ 대부분 잘 지켜지고 있지만, 맞춤법 검사기 한 번 돌려보시는 거 추천할게요!

2022-07-25 00:23 UTC, iju1633 requested changes
웹소켓으로 채팅창을 구현하는 것에 흥미가 있던 차라 매우 흥미롭게 잘 읽었습니다. 잘 몰랐던 SSE나 WebRTC에 대해서도 잘 설명해주셔서 감사합니다.

2022-07-25 12:53 UTC, qf9ar8nv commented on _posts/2022-07-24-websocket.md
> +WebSocket의 특성 상 한번 연결이 될 때 HTTP protocol을 사용하기 때문에 인증, 인가를 해당 url에 맞춰서 적용해주면 됩니다. 그럼 정상적으로 인증이 되지만 이 후 커넥션이 끊어지지 않는다면 따로 인증 과정을 수행하지 않습니다. 커넥션이 연결될 따 이미 인증이 끝난 상태로 가정하기 때문에 중복해서 인증 할 필요가 없다고 가정합니다.
넵 수정하겠습니다!

2022-07-25 12:54 UTC, qf9ar8nv commented on _posts/2022-07-24-websocket.md
> +SSE는 Server에서 발생하는 이벤트를 Client에 제공하기 위한 방법입니다. Client에서 Server로 먼저 Request를 보내면 streaming을 위한 연결이 생성됩니다. 이를 통해 Server에서 이벤트가 발생할 때 마다 연결된 Client에게 데이터를 전달 할 수 있습니다.
넵 제가 신경쓰지 못한 부분이 있네요. 검사기 돌리고 commit 하겠습니다!

2022-08-01 12:26 UTC, ms9648 approved these changes

2022-08-01 12:27 UTC, merged