10월 BE 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #235
Opened 2022-10-19 05:56 UTC by iju1633

2022-10-27 05:07 UTC, seunghb320 requested changes
사소하거긴 한데 38번 라인의 오른쪽 'Print문'만 다른 라인과 다르게 P가 대문자인데 의도하신걸까요??
56번 라인 '쓰레드 별로 -> 쓰레드별로'가 맞는것 같습니다..!

2022-10-27 05:46 UTC, iju1633 commented
의도한 건 아니었네요ㅎㅎ P는 소문자로 고치고 문법도 수정 완료했습니다!

2022-10-29 06:08 UTC, seunghb320 approved these changes
고생하셨습니다! 테크톡을 통해 심화된 의견을 나눠본 주제를 모두에게 공유해주신 정말 좋은 글인것 같습니다!!

2022-11-09 17:23 UTC, SSUHYUNKIM commented
![재욱](https://user-images.githubusercontent.com/43875264/200898251-8c5cc854-a2ee-436f-8694-db423018fb87.JPG)
1. 혹시 예상한 부분과 다르게 된 부분이 있으면 확인 후 수정 부탁드립니다.
2. 확인하셨을 수 있지만 맞춤법 검사기 한번 쭉 돌려서 수정해주시면 좋을 것 같습니다.
3. (선택) 주요 단어에 강조 표시를 넣으면 좀 더 눈에 잘 보일 것 같습니다.

2022-11-10 08:02 UTC, iju1633 commented
확인 완료하였고 수정 사항 없습니다!

2022-11-10 13:42 UTC, merged