10월 DA/ML 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #240
Opened 2022-10-30 11:34 UTC by hjm507

잘못 병합되었다고 하여 다시 PR 날립니다!

2022-10-31 04:04 UTC, paulben0410 submitted a review, later dismissed
크롤링이나 자연어 전처리에 유용할거 같네요! 유용한 내용이었습니다 🙃

2022-10-31 08:59 UTC, 00HS approved these changes, later dismissed
정규 표현식 항상 헷갈렸는데 예시 덕분에 이해가 잘되네요!

2022-10-31 23:49 UTC, beautifulchoi requested changes
포스팅 잘봤습니다. 수정 전보다 예시부분 가독성이 더 좋아진 것 같아요 ! 고생하셨습니다

2022-10-31 23:49 UTC, beautifulchoi commented on _posts/2022-10-22-regular-expression.md
> +여기서 **정규 표현식**을 사용하면, 아래와 같이 우리가 원하는 정보를 간단하게 추출해낼 수 있습니다.
정규표현 라이브러리 설명이 들어가면 좋을 것 같습니다

2022-11-01 13:27 UTC, yurishin929 reviewed
잘 봤습니다. 다음 블로그 작성에도 많은 도움이 될 것 같아요!

2022-11-09 17:45 UTC, SSUHYUNKIM commented
![진민](https://user-images.githubusercontent.com/43875264/200902579-9c5c1de9-2128-45dc-9597-00db7c0f4ff7.JPG)
1.혹시 의도한 부분과 다르게 보이는 부분이 있으면 수정 부탁드립니다.
2.모든 수정 후 맞춤법 검사 한번 부탁드립니다.

2022-11-11 16:55 UTC, hjm507 commented on _posts/2022-10-22-regular-expression.md
> +여기서 **정규 표현식**을 사용하면, 아래와 같이 우리가 원하는 정보를 간단하게 추출해낼 수 있습니다.
너무 늦게 확인했네요. 죄송합니다 ㅜㅜ
해당 부분 추가적으로 파이썬 re 라이브러리 활용했다고 명시하여 수정했습니다!

2022-11-19 08:33 UTC, merged