daeyeongko
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #241
Opened 2022-11-03 13:36 UTC by airtic21

포스트 작성

2022-11-04 02:12 UTC, paulben0410 approved these changes, later dismissed

2022-11-04 02:15 UTC, yurishin929 approved these changes, later dismissed

2022-11-09 17:51 UTC, SSUHYUNKIM commented
![대영](https://user-images.githubusercontent.com/43875264/200903440-0839d446-5c69-40c1-8e25-79a3eabd552c.JPG)

1. 커버 이미지를 추가하지 않으셔서 커버 이미지 추가 부탁 드립니다.

![대영 - 마크다운 문법 오류](https://user-images.githubusercontent.com/43875264/200903512-f308a95e-c537-4018-90e6-e7156334ccba.JPG)

2. 코드를 삽입하실 경우 코드 위 아래에 ```html ``` 이런식으로 남겨야 해서 수정 부탁 드립니다. 이해가 안 가시면 다른 분들이 작성하신 부분 참고해주시면 됩니다.
3. 모든 수정을 마친 후 맞춤법 검사 부탁 드립니다.

2022-11-17 14:43 UTC, hjm507 commented
수현님이 말씀해주신 대로 코드 부분 markdown 수정이 필요할 것 같고, 코드 결과에 대한 이미지가 포함된다면 좋을 것 같습니다!

2022-11-17 14:46 UTC, hjm507 requested changes
수현님이 말씀해주신 대로 코드 부분 markdown 수정이 필요할 것 같고, 코드 결과에 대한 이미지가 포함된다면 좋을 것 같습니다!

2022-12-16 09:15 UTC, closed without merging