11월 DATA/ML 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #245
Opened 2022-11-20 05:47 UTC by daehoidar

2022-11-21 14:47 UTC, paulben0410 approved these changes, later dismissed

2022-12-16 12:15 UTC, beautifulchoi requested changes
죄송합니다,, 리뷰가 좀 늦어졌네요... 고등학생때부터 오토인코더를 사용해보셨다니 ㄷㄷ 대단하신 것 같습니다 ,,, !
실습내용과 시각화 부분도 깔끔해서 쉽게 잘 정리 된 것 같습니다. 고생하셨습니다

2022-12-16 12:15 UTC, beautifulchoi commented on _posts/2022-11-20-VAE.md
> +&nbsp;위에서 모델을 만들 때 활성화 함수로 Leaky ReLU가 쓰였는데 leaky ReLU는 x가 0보다 작으면 0을 y로갖는 상수 함수이고 0보다 크면 항등 함수인 일반 ReLU와 달리 x값이 0보다 작을 때 기울기가 0.001으로 작은 음수값을 가진다는 차이점이 존재합니다.
LeakyRELU의 특성이 음의 영역에서 0을 y로 갖는 상수함수라고 읽혀질 여지가 있어, 끊어서 relu와의 차이를 설명하면 좋을 것 같습니다

2022-12-16 12:15 UTC, beautifulchoi commented on _posts/2022-11-20-VAE.md
> +&nbsp;그 다음, 숫자에 따라 색을 구분하여 산점도를 그려보겠습니다. 모델에게 해당 사진 데이터에 해당하는 숫자 레이블을 입력해주지 않았음에도 AE는 자연스럽게 비슷한 숫자를 잠재 공간의 같은 영역에 모은 것을 볼 수 있습니다.
AE의 결과와 문제점을 분리하면 좋을 것 같습니다.(비슷한 숫자를 같은 공간안에 클러스터 해주는건 장점에 속하는데, 단점처럼-단점이 될수도 있으나 읽히는 것 같습니다)

2022-12-16 12:32 UTC, 00HS approved these changes, later dismissed

2022-12-16 14:25 UTC, yurishin929 approved these changes, later dismissed

2022-12-17 06:52 UTC, hjm507 reviewed
이상 탐지 관련해서 오토인코더 이용해보려고 했으나 쉽지 않을 것 같아 시간 상 포기했었던 경험이 있는데 대단하시네요.. 실제 코드 및 이미지와 함께 설명이 잘 되어 있어 좋았습니다!

2022-12-17 06:52 UTC, hjm507 commented on _posts/2022-11-20-VAE.md
> +&nbsp;인코더와 디코더를 동시에 훈련시키기 위해서는 데이터가 언코더를 지나 디코더로 나오는 하나의 모델을 만들어야 합니다. 다음 코드와 같이 오토 인코더 모델의 입력을 인코더의 입력으로 하고 디코더의 입력은 인코더의 출력으로 한 뒤 오토 인코더 모델의 출력을 디코더의 출력을 하여 AE 모델을 만듭니다.
> 언코더 -> 인코더

오타 수정해야 할 것 같습니다.
이외에도 자잘한 문법 오류 등은 맞춤법 검사기 등을 이용해 전체 내용에 대해 한 번 체크해주시고 수정해 주셨으면 좋겠습니다.

2022-12-17 06:52 UTC, hjm507 commented on _posts/2022-11-20-VAE.md
> +AE = Autoencoder(
사용한 라이브러리나 환경 등에 대해서 간략하게 안내해주거나 설명해주었으면 좋을 것 같습니다.

2023-01-14 22:15 UTC, daehoidar commented on _posts/2022-11-20-VAE.md
> +&nbsp;위에서 모델을 만들 때 활성화 함수로 Leaky ReLU가 쓰였는데 leaky ReLU는 x가 0보다 작으면 0을 y로갖는 상수 함수이고 0보다 크면 항등 함수인 일반 ReLU와 달리 x값이 0보다 작을 때 기울기가 0.001으로 작은 음수값을 가진다는 차이점이 존재합니다.
수정했습니다. 감사합니다!

2023-01-14 22:16 UTC, daehoidar commented on _posts/2022-11-20-VAE.md
> +&nbsp;그 다음, 숫자에 따라 색을 구분하여 산점도를 그려보겠습니다. 모델에게 해당 사진 데이터에 해당하는 숫자 레이블을 입력해주지 않았음에도 AE는 자연스럽게 비슷한 숫자를 잠재 공간의 같은 영역에 모은 것을 볼 수 있습니다.
결과와 문제점으로 영역을 나누었습니다. 자세한 리뷰 감사드립니다!

2023-01-14 22:16 UTC, daehoidar commented on _posts/2022-11-20-VAE.md
> +&nbsp;인코더와 디코더를 동시에 훈련시키기 위해서는 데이터가 언코더를 지나 디코더로 나오는 하나의 모델을 만들어야 합니다. 다음 코드와 같이 오토 인코더 모델의 입력을 인코더의 입력으로 하고 디코더의 입력은 인코더의 출력으로 한 뒤 오토 인코더 모델의 출력을 디코더의 출력을 하여 AE 모델을 만듭니다.
오타와 맞춤법 수정했습니다. 감사합니다!

2023-01-14 22:17 UTC, daehoidar commented on _posts/2022-11-20-VAE.md
> +AE = Autoencoder(
말씀하신 내용 간략하게 추가했습니다. 리뷰 감사드립니다!

2023-01-19 13:04 UTC, hjm507 approved these changes

2023-01-19 14:24 UTC, beautifulchoi approved these changes

2023-02-09 05:12 UTC, merged