docs: backend 11월 포스팅 추가
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #246
Opened 2022-11-20 06:12 UTC by marsboy02

## 변경사항
- docker와 관련된 내용으로 백엔드 팀 11월 포스팅을 추가했습니다.

2022-11-21 15:40 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +## docker의 인스톨 과정
[Nit] 인스톨 -> 설치 과정이 더 가독성이 좋은 것 같은데 어떠신가요?

2022-11-21 15:46 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +돌아가게 만들고 이러한 여러개의 멀티 컨테이너 환경을 통해서 프로그램을 안전하게 작동시키는 것이 도커의 원리인 것입니다.
맞춤법 수정이 필요해보입니다.

여러개의 -> 여러 개의

또한, 전체적인 표현이 어색해서 수정이 좀 필요해보입니다.
e.g. 즉, 도커를 실행하면 이미지들을 통해서 컨테이너를 돌아가게 하며 여러 개의 멀티 컨테이너 환경을 통해 프로그램을 안전하게 작동시키는 것이 도커의 원리입니다.

2022-11-21 15:48 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +하이퍼바이저를 구현하는 방법은 두가지로 나뉘게 됩니다.
어법 수정 및 어미 수정이 필요해보입니다.

두가지로 나뉘게 됩니다 -> 두 가지로 나뉩니다.

2022-11-21 15:49 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +따라서 VM의 방식은 훨씬 복잡하고 무거운 부피를 가지고 있습니다.
어법 수정이 필요해보입니다.

실행해야합니다 -> 실행해야 합니다.

2022-11-21 15:50 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +따라서 VM의 방식은 훨씬 복잡하고 무거운 부피를 가지고 있습니다.
전체적으로 맞춤법 검사기 한 번 돌리시는 거 추천드립니다^^

2022-11-21 15:52 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +OS까지 가상화하여 맥에서 윈도우를 까는 등의 방법은 비교적 사용법이 간단할 수 있으나 굉장히 느립니다.
구어체가 사용되어 문어체로의 수정이 필요해보입니다.

-> 예로, OS까지 가상화하며 맥 환경에서 윈도우를 설치하는 방법은 비교적 사용법이 간단할 수 있으나 굉장히 느립니다.

2022-11-21 15:54 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +어떤 어플이 사용량이 너무 많다면 그 어플리케이션 같은 것을 C group에 집어 넣어서 CPU와 메모리 사용 제한 가능
표현의 통일이 필요해보입니다.
`Cgroup`, `C Group`, C group`

2022-11-21 15:55 UTC, iju1633 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +어떤 어플이 사용량이 너무 많다면 그 어플리케이션 같은 것을 C group에 집어 넣어서 CPU와 메모리 사용 제한 가능
표현이 어색하여 수정이 필요해보입니다.

e.g. 특정 어플의 사용량이 너무 많다면 해당 어플을 C Group에 넣어 CPU와 메모리 사용 제한 가능

2022-11-21 15:57 UTC, iju1633 requested changes
스크럼에서도 자주 언급해주셨던 도커에 대해 정리해주셔서 감사하고, 예시도 많이 제시해주셔서 이해하기 좋았습니다 👍

2022-11-22 04:17 UTC, seunghb320 requested changes
글 전체에서 '도커' 'docker'를 혼용해서 쓰고 계신데 기준이 있으실까요? 큰 문제는 아니지만 개인적으로 소제목만이라도 통일이 이루어지면 좋을것 같습니다..!
추가로 도커에 대해 잘 작성해주신것 같습니다. 덕분에 흥미롭게 읽었습니다!!

2022-11-22 04:17 UTC, seunghb320 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +## docker의 인스톨 과정
14줄에 다운로드 하면-> 다운로드하면

2022-11-22 04:17 UTC, seunghb320 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +돌아가게 만들고 이러한 여러개의 멀티 컨테이너 환경을 통해서 프로그램을 안전하게 작동시키는 것이 도커의 원리인 것입니다.
47번 줄의 문장의 경우 주어와 서술어의 호응이 어색한것 같습니다. 
위 사진은 백엔드 아키텍쳐를 nodejs, redis, mongoDB를 사용하여 구성하였는데 ---> 위 사진은 백엔드 아키텍쳐를 nodejs, redis, mongoDB를 사용하여 구성한 것을 보여주는데
정도로 수정하면 어떨까 합니다.

2022-11-22 04:17 UTC, seunghb320 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +어떤 어플이 사용량이 너무 많다면 그 어플리케이션 같은 것을 C group에 집어 넣어서 CPU와 메모리 사용 제한 가능
view file을 해보면 118번 줄과 119번 줄이 분리가 되어있지 않습니다. '.'을 추가해 주시거나 확실하게 줄을 분리하면 좋을것 같습니다!

2022-11-22 04:17 UTC, seunghb320 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +따라서 VM의 방식은 훨씬 복잡하고 무거운 부피를 가지고 있습니다.
84줄 실행 하기 위해서 -> 실행하기 위해서

2022-11-22 04:17 UTC, seunghb320 commented on _posts/2022-11-17-why-do-we-use-docker.md
> +OS까지 가상화하여 맥에서 윈도우를 까는 등의 방법은 비교적 사용법이 간단할 수 있으나 굉장히 느립니다.
93줄 시키는 지 -> 시키는지
로 바꾸면 좋을것 같습니다!

2022-12-07 03:38 UTC, iju1633 submitted a review, later dismissed

2022-12-07 07:13 UTC, seunghb320 submitted a review, later dismissed

2022-12-31 07:34 UTC, dghg commented
도커 ( 크게 보면 container runtime ) 을 이용하는 이유는 말씀해주신 `어떤 프로그램을 다운로드하는 과정을 간단하게 만들기 위해서` 도 있겠지만 그보다는 글에서도 언급되고 있는 resource isolaiton이나, overhead 없는 virtualized 환경에서의 system call, immutable하게 프로세스를 관리하기 위한게 더 커요 ~ 지나가다 남깁니당

2023-01-09 08:50 UTC, merged