author 정보 수정 및 적용
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #25
Opened 2020-09-29 04:12 UTC by MOBUMIN

* author에 테스트용으로 욱재님, 유현님, 저 이름 추가 및 avatar에 깃헙.png 추가
* avatar를 잘 적용시키기 위해 base.url/ 이부분 삭제
* gravater 안쓰니까 삭제
* 제 이름으로 링크되는 웹 확인하려고 post 하나 김수빈으로 바꿈(잘됨)
resolve #12

2020-09-29 06:59 UTC, Enoch-Kim commented on _data/author.yml
>  sal:
```suggestion
yuhyeon
```

2020-09-29 07:08 UTC, Enoch-Kim requested changes

2020-09-29 07:08 UTC, Enoch-Kim commented on _data/author.yml
>  john:
```suggestion
유현:
```

2020-09-29 09:02 UTC, MOBUMIN commented on _data/author.yml
>  sal:
아 그거 바꾸면 post에 있는 것 까지 다 바꿔야해서 일단 안바꾸고 나뒀어요!( 사진이 적용되나 안되나 보려고 기존의 키값은 유지시킨채로 내용물만 바꿨습니다! )
한글 테스트는 제 이름으로 author 하나 만들어서 post author 김수빈으로 바꾸고 테스트 해봤어요!(잘 됩니당) 저도 동명이인인 것 때문에 어떻게 할지 고민했는데 그냥 subin1 subin2 괜찮을 것 같네용

2020-09-29 14:30 UTC, Enoch-Kim approved these changes
아 혹시 저희 author.web의 경우 github이 아니라 각자 웹사이트 넣기로 했었나요??

2020-09-29 15:04 UTC, Enoch-Kim requested changes
*web 부분 github으로 할 것인가 개인 선호로 할 것인가? (욱재님과 있을 때, github으로 하기로 했던 것 같아요)
*twitter관련 부분 삭제 요청
*description관련 부분 삭제 요청

2020-09-29 15:04 UTC, Enoch-Kim commented on _data/author.yml
> -  twitter: https://twitter.com/wowthemesnet
제가 코드 찾아보니 twitter 관련 코드들이 남아있어서요 그부분 수정해주시면 더 좋을 것 같습니다.

2020-09-29 15:04 UTC, Enoch-Kim commented on _data/author.yml
> +  web: https://kiju23.tistory.com/
web은 각자 개인 웹사이트 하기로했었나요?? 
만약 개인 웹사이트로 한다면 웹사이트 없는 사람들을 위해서 author.web 나오는 부분을 if 분기 쳐야할 것 같아요.
그게 아니면 github으로 통일하거나 아니면 개인 선호도를 조사해야할 것 같습니다.

2020-09-29 15:04 UTC, Enoch-Kim commented on _data/author.yml
> +  description: "한글 이름과 웹 테스트할게요"
저번에 description 빼기로 했으니 post.html 에 있는 author.description 부분 제거해주시면 좋을 것 같습니다!

2020-09-30 01:21 UTC, MOBUMIN commented on _data/author.yml
> +  description: "한글 이름과 웹 테스트할게요"
description 빼기로 했었나요??

2020-09-30 01:22 UTC, MOBUMIN commented on _data/author.yml
> +  web: https://kiju23.tistory.com/
그 부분은 author 내용채우는 issue에서 다뤄야할 것 같습니당!

2020-09-30 01:22 UTC, MOBUMIN commented on _data/author.yml
> -  twitter: https://twitter.com/wowthemesnet
오홍 알겠습니당

2020-09-30 10:33 UTC, jeongukjae reviewed
유저 key는 github username으로 하면 어떨까요??

2020-09-30 10:37 UTC, Enoch-Kim commented
> 유저 key는 github username으로 하면 어떨까요??

오 좋은 것 같아요!!

2020-10-01 12:34 UTC, Enoch-Kim submitted a review, later dismissed
LGTM

2020-10-11 04:30 UTC, jeongukjae approved these changes
:+1:

2020-10-11 04:31 UTC, merged