12월 모바일 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #256
Opened 2022-12-21 13:00 UTC by hfjxjjd123

2022-12-30 01:14 UTC, iju1633 commented on _posts/2022-12-21-how-to-release-mobile-app.md
> +* keystore: 인증서 & 암호화에 사용되는 보안 인증서(개인키 등등)를 저장하는 공간이다.
어미 통일을 시키는 건 어떨까요?

e.g. 저장하는 공간이다. -> 저장하는 공간

2022-12-30 01:15 UTC, iju1633 commented on _posts/2022-12-21-how-to-release-mobile-app.md
> +* ProGard: 자바 코드를 최적화하고 난독화하는 도구이다. 
오타 수정 부탁드립니다. (ProGard -> ProGuard)

2022-12-30 01:17 UTC, iju1633 requested changes
android와 ios의 배포 방법을 모두 설명해주셔서 비교도 되고 좋았습니다 :)

흥미롭게 읽었어요 !!

2023-01-01 13:58 UTC, hfjxjjd123 commented on _posts/2022-12-21-how-to-release-mobile-app.md
> +* keystore: 인증서 & 암호화에 사용되는 보안 인증서(개인키 등등)를 저장하는 공간이다.
넵!

2023-01-01 13:59 UTC, hfjxjjd123 commented on _posts/2022-12-21-how-to-release-mobile-app.md
> +* ProGard: 자바 코드를 최적화하고 난독화하는 도구이다. 
앗..

2023-01-02 07:43 UTC, hoqn commented on _posts/2022-12-21-how-to-release-mobile-app.md
> +* ProGaurd: 자바 코드를 최적화하고 난독화하는 도구 
앗.. 다시 오타가 있습니다..! `ProGaurd` -> `ProGuard`.

2023-01-03 00:56 UTC, hfjxjjd123 commented on _posts/2022-12-21-how-to-release-mobile-app.md
> +* ProGaurd: 자바 코드를 최적화하고 난독화하는 도구 
앗 ㅋㅋㅋ 수정하겠습니다

2023-01-21 14:52 UTC, iju1633 submitted a review, later dismissed

2023-02-15 05:20 UTC, merged