12월 백엔드 포스트
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #258
Opened 2022-12-31 07:51 UTC by dghg

2023-01-02 01:37 UTC, iju1633 commented on _posts/2022-12-31-spring-mvc-resolver.md
> +가장 핵심이 되는 인터페이스는 `HandlerMethodArgumentResolver` 이다. 해당 인터페이스는 두가지 method의 구현을 필요로 한다.
[Nit] 두가지 -> 2 가지로 수정하시면 가독성이 더욱 좋을 것 같습니다.

2023-01-02 01:40 UTC, iju1633 commented on _posts/2022-12-31-spring-mvc-resolver.md
> +	override fun    addArgumentResolvers(resolvers:MutableList<HandlerMethodArgumentResolver>) {
`fun`과 `addArgument` 사이에 불필요한 공백이 있어 수정 부탁드립니다.

2023-01-02 01:44 UTC, iju1633 requested changes
글을 읽으며 객체 파라미터를 주입받는 방법 중, 잘 몰랐던 handler나 resolver에 대해서도 어떻게 작동하는 지 알 수 있었네요! 좋은 글 감사합니다 :)

2023-01-23 14:24 UTC, seunghb320 approved these changes, later dismissed
앞서 말씀해주신 부분 외에는 저는 수정 관련해서는 딱히 요청할게 없습니다. 좋은 글 정말 감사드립니다:)

2023-01-29 13:45 UTC, iju1633 approved these changes

2023-01-29 13:46 UTC, iju1633 approved these changes
LGTM 👍

2023-02-14 05:54 UTC, merged