1월 백엔드 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #259
Opened 2023-01-21 15:43 UTC by iju1633

2023-01-24 13:31 UTC, simpack0513 reviewed
MVC, MVP, MVVM의 의미를 알고 각각의 장점을 확실히 알 수 있어서 좋았습니다! 좋은 글 써주셔서 감사합니다 :)

2023-01-24 13:31 UTC, simpack0513 commented on _posts/2023-01-21-Pattern.md
> +![archieve](../assets/images/post-Pattern/mvc.png)
제 환경에서만 그럴 수도 있는데 사진이 보이지 않습니다. 사진을 누르면 404에러가 나오고 master 안에 없다는 이야기가 보입니다

2023-01-24 13:31 UTC, simpack0513 commented on _posts/2023-01-21-Pattern.md
> +MVC에서는 컨트롤러가 모델과 뷰를 선택하면 뷰가 해당 모델을 바탕으로 UI를 그렸다고 볼 수 있는데, 이는 컨트롤러가 뷰를 정확히 인지할 수 있다는 의미이다. MVP에서는 뷰와 컨트롤러의 이 밀접한 관계를 끊고 서로 인지할 수 없게 만드는 것이 목표라고 생각하면 된다.
사소한거지만 뷰와 컨트롤러의 이 밀접한 관계 -> 뷰와 컨트롤러의 밀접한 관계가 조금 더 문장이 매끄러운거 같습니다! 원래도 괜찮긴 해요 ㅎㅎ

2023-01-25 15:55 UTC, hfjxjjd123 requested changes
각 디자인 패턴의 장점과 함께 패턴들을 알아볼 수 있어서 좋았습니다!
이후 디자인 패턴을 사용해 볼 때 도움이 많이 될 것 같아요~

2023-01-25 15:55 UTC, hfjxjjd123 commented on _posts/2023-01-21-Pattern.md
> +뷰와 뷰모델 사이의 양방향 데이터 바인딩을 발견할 수 있다. 뷰 모델 안에서 그리고 뷰에게 수정사항들을 자동으로 이동시킨다. 뷰모델에서 변화를 주기 위해서, 뷰모델은 옵저버 패턴을 사용한다.
옵저버 패턴이 무엇인지 간단한 설명이 있으면 이해하기 더 쉬울 것 같아요!

2023-01-25 15:55 UTC, hfjxjjd123 commented on _posts/2023-01-21-Pattern.md
> +그래서 지금부터 애플리케이션을 개발할 때 고민해야 할 MVC, MVP, MVVM 패턴에 대해 제가 정리한 부분을 공유하고자 한다.
'제가'라는 표현과 '한다'라는 어체가 같이 쓰이니 조금 어색한 거 같아요!
'제가' 자체를 빼도 괜찮을 것 같아요

2023-01-26 00:50 UTC, iju1633 commented on _posts/2023-01-21-Pattern.md
> +그래서 지금부터 애플리케이션을 개발할 때 고민해야 할 MVC, MVP, MVVM 패턴에 대해 제가 정리한 부분을 공유하고자 한다.
피드백 감사합니다 ! 수정했어요

2023-01-26 00:51 UTC, iju1633 commented on _posts/2023-01-21-Pattern.md
> +![archieve](../assets/images/post-Pattern/mvc.png)
블로그 팀에게 여쭤봤는데 잘 보인다고 하셔서 문제 없는 걸로 보입니다 !

2023-01-26 00:51 UTC, iju1633 commented on _posts/2023-01-21-Pattern.md
> +MVC에서는 컨트롤러가 모델과 뷰를 선택하면 뷰가 해당 모델을 바탕으로 UI를 그렸다고 볼 수 있는데, 이는 컨트롤러가 뷰를 정확히 인지할 수 있다는 의미이다. MVP에서는 뷰와 컨트롤러의 이 밀접한 관계를 끊고 서로 인지할 수 없게 만드는 것이 목표라고 생각하면 된다.
수정 이후가 가독성이 더 좋네요 ㅎㅎ 감사합니다

2023-01-26 00:51 UTC, iju1633 commented on _posts/2023-01-21-Pattern.md
> +뷰와 뷰모델 사이의 양방향 데이터 바인딩을 발견할 수 있다. 뷰 모델 안에서 그리고 뷰에게 수정사항들을 자동으로 이동시킨다. 뷰모델에서 변화를 주기 위해서, 뷰모델은 옵저버 패턴을 사용한다.
추가 완료했습니다 😀

2023-01-26 13:16 UTC, hfjxjjd123 approved these changes

2023-02-14 12:36 UTC, hfjxjjd123 approved these changes
😄

2023-02-21 12:36 UTC, simpack0513 approved these changes
확인했습니다 !

2023-02-27 05:22 UTC, merged