1월 Data/ML 포스트
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #260
Opened 2023-01-21 16:11 UTC by beautifulchoi

1월 Data/ML 팀 최초 포스트 pr입니다

2023-02-08 08:20 UTC, yurishin929 approved these changes, later dismissed

2023-02-08 14:46 UTC, hjm507 reviewed
Transformer 기반 모델이 CV에서도 SOTA 갱신하고 있다는 것과 그러한 Intro를 배경으로 자연스럽게 Transfromer 모델 설명을 이어가서 더 흥미로웠던 것 같습니다.

다만 주제 상 어쩔 수 없긴 하지만, 사실 제대로 이해하기에는 많은 양의 배경 지식을 요구하는 지라 최소한 Transformer에 대해 어느 정도 미리 알고 있지 않으면 다른 분들이 읽기가 쉽지는 않을 것 같아서 초반 부분에 이런저런 배경 지식을 알고 있으면 도움이 된다 정도 언급해 줘도 좋을 것 같습니다..!

2023-02-08 14:46 UTC, hjm507 commented on _posts/2023-01-22-what-is-vision-transformer.md
> +예시: **224 * 224** 이미지 사용한다고 가정
애매하긴 한데 위 절차에 대한 예시 부분의 경우에는 > 기호 등을 이용해서 인용절로 바꾸면 가독성이 좋지 않을까요...?

2023-03-03 15:02 UTC, beautifulchoi commented on _posts/2023-01-22-what-is-vision-transformer.md
> +예시: **224 * 224** 이미지 사용한다고 가정
수정하였습니다

2023-04-03 14:56 UTC, hjm507 approved these changes, later dismissed
저번 리뷰에 맞게 잘 수정해주신 것 같습니다!

2023-04-06 14:40 UTC, 00HS submitted a review, later dismissed
어려운 내용인데도 설명 깔끔하게 잘 해주셔서 이해가 쉽네요! 고생하셨습니다:)

2023-04-10 08:29 UTC, yurishin929 approved these changes, later dismissed

2023-05-05 15:05 UTC, hoqn requested changes
형식 부분에서 두 가지 문제가 보여서 리뷰합니다!

2023-05-05 15:05 UTC, hoqn commented on _posts/2023-01-22-what-is-vision-transformer.md
> +authors: [beutifulchoi]
깃허브 이름에 오타가 있네요!
```suggestion
authors: [beautifulchoi]
```

2023-05-05 15:05 UTC, hoqn commented on _posts/2023-01-22-what-is-vision-transformer.md
> +---
내용 중에 수식이 사용되는데, 제대로 렌더링되지 않고 있습니다. 수식을 이용하려면 프론트매터에 다음을 추가해주세요!
```suggestion
use_math: true
---
```

2023-05-19 15:33 UTC, beautifulchoi commented on _posts/2023-01-22-what-is-vision-transformer.md
> +---
피드백 해주신 부분 수정하였습니다. 수정 늦어진 점 죄송합니다...

2023-05-22 05:44 UTC, hoqn approved these changes
다 된 것 같습니다! 수고하셨어요!

2023-05-22 06:33 UTC, beautifulchoi commented
> 다 된 것 같습니다! 수고하셨어요!

최종 리뷰 해주셔서 너무 감사드립니다 !!

2023-06-05 14:40 UTC, merged