1월 백엔드 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #261
Opened 2023-01-22 18:42 UTC by qf9ar8nv

2023-01-23 07:31 UTC, seunghb320 requested changes
95줄에 '특정 상황(함수가 함수를 호출하는 경우)은' -> '특정 상황(함수가 함수를 호출하는 경우)에서는' 으로 수정하면 좋지 않을까 생각합니다..!
이번 프로젝트  진행하면서 정확한 원리는 모른 채 @Transactional 어노테이션 사용하고 있었는데 다른 방법들에 대해서 알게 되어 좋았습니다!! 좋은 글 감사합니다^-^

2023-01-24 11:20 UTC, iju1633 approved these changes, later dismissed
내부함수가 호출되는 경우에 @Transaction이 적용되지 않는 것은 잘 모르고 있었네요. 좋은 글 감사합니다 !
👍

2023-01-31 12:56 UTC, seunghb320 approved these changes

2023-02-03 06:51 UTC, iju1633 submitted a review, later dismissed
LGTM 👍

2023-02-14 12:41 UTC, seunghb320 approved these changes
수정 감사드립니다! 좋은 글 감사드려요ㅎㅎㅎㅎ

2023-02-14 12:43 UTC, seunghb320 approved these changes, later dismissed
죄송합니다 전의 approve를 commit에서 했네요...늘 스크럼에서 좋은 얘기 해주셔서 감사드리고 좋은 글 잘 읽었습니다:)

2023-02-16 09:09 UTC, SSUHYUNKIM commented
![현철 이미지 깨짐](https://user-images.githubusercontent.com/43875264/219319366-a223a9c3-8f36-4a2e-b8c0-c2884db311d7.JPG)

중간에 이미지가 깨지는 부분이 있어서 확인 부탁드립니다.

2023-04-15 06:05 UTC, qf9ar8nv commented
@SSUHYUNKIM 
수정하였습니다. 확인 부탁드립니다 🙏

2023-05-05 15:14 UTC, hoqn reviewed
필수는 아니지만, 코드에 언어 이름이 들어가면 좋을 것 같습니다!

2023-05-05 15:14 UTC, hoqn commented on _posts/2023-01-23-transaction.md
> +```
코드 하이라이팅이 되도록 언어 정보를 추가해주시면 더 좋을 것 같습니다.
```suggestion
```kotlin
```

2023-05-05 15:14 UTC, hoqn commented on _posts/2023-01-23-transaction.md
> +```
```suggestion
```kotlin
```

2023-05-05 15:14 UTC, hoqn commented on _posts/2023-01-23-transaction.md
> +```
```suggestion
```kotlin
```

2023-05-05 15:14 UTC, hoqn commented on _posts/2023-01-23-transaction.md
> +```
```suggestion
```kotlin
```

2023-05-05 15:14 UTC, hoqn commented on _posts/2023-01-23-transaction.md
> +```
```suggestion
```kotlin
```

2023-05-05 15:14 UTC, hoqn commented on _posts/2023-01-23-transaction.md
> +```
```suggestion
```kotlin
```

2023-06-21 18:00 UTC, merged