작성자 정보 추가
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #264
Opened 2023-02-03 06:41 UTC by SSUHYUNKIM

2023-02-03 06:45 UTC, iju1633 commented on _data/author.yml
>    member: true
member 값을 false로 해주시면 될 것 같습니다 ! 👍

2023-02-03 06:46 UTC, iju1633 requested changes
정리 감사드립니다 ! 👍 👍

2023-02-03 06:48 UTC, iju1633 approved these changes

2023-02-03 07:08 UTC, hoqn approved these changes
문제 없는 것 같습니다. 정말 정말 수고하셨습니다..! 😣

2023-02-06 03:46 UTC, dlalsrb0248 approved these changes
확인하였습니다. 정리 감사드립니다!!

2023-02-06 14:07 UTC, merged