2월 백엔드 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #268
Opened 2023-02-16 02:21 UTC by Relaxed-Mind

2023-02-20 06:33 UTC, seunghb320 requested changes
HTTPS란? 문단을 보면TLS는 transport layer의 보안 서비스라고 하셨는데 첨부된 사진 자료를 보면 하나의 계층인것으로 보입니다. 이에 관한 추가적인 설명이 있으면 좋을것 같습니다!
그리고 같은 문단에서 'TCP 위의 두 층의 프로토콜로 보안을 제공한다'고 하셨는데 그렇다면 transport layer에서 UDP를 사용할 경우 HTTPS 적용이 불가능한것인지 아니면 transport layer를 TCP로 잘못 입력하신 것인지 헷갈리는것 같습니다..! 사안에 따라 적절한 추가적인 언급이나 수정이 있으면 좋을것 같습니다:)
(제가 아직 컴통을 안들어서 잘 몰라서 그런것일 수도 있습니다ㅠㅠ)

2023-02-23 06:14 UTC, iju1633 requested changes
Https 에 대해 막연하게 보안이 더 좋은 것으로만 이해하고 있었는데, 좋은 정보 정말 감사드립니다 👍

2023-02-23 06:14 UTC, iju1633 commented on _posts/2023-02-16-https.md
> +HTTPS가 HTTP 아래층에(TCP 위층에) TLS 프로토콜을 덧붙여서 보안에 신경 쓴다는 것은 알겠는데, 그래서 뭘 보호하는데요??
좀 더 완곡한 표현이 좋을 것 같습니다 ! `그래서 어떤 것을 보호하는 것일까요??` 등의 표현은 어떨까요?

2023-02-23 06:14 UTC, iju1633 commented on _posts/2023-02-16-https.md
> +그럼 TLS란 무엇일까요?
[Nit] 줄바꿈이 있으면 가독성도 좋고 이후의 내용이 더욱 강조될 것 같아요 !

2023-02-23 06:14 UTC, iju1633 commented on _posts/2023-02-16-https.md
> +AWS는 이를 위해 서비스를 제공하는데, **AWS Certificate Manager(ACM)**가 TLS 인증서를 발급해줍니다.
view file로 파일을 봤을 때 볼드 처리가 되어 있지 않은데, 한 번더 확인 가능하실까요?
<img width="1033" alt="스크린샷 2023-02-23 오후 3 12 33" src="https://user-images.githubusercontent.com/43805087/220832788-56b66d40-4e7b-45cc-84b5-e9555bed8c09.png">

2023-02-28 02:42 UTC, Relaxed-Mind commented
수정 완료했습니다 :)

2023-02-28 02:56 UTC, iju1633 approved these changes
피드백 반영 감사합니다 👍 👍

2023-03-01 01:07 UTC, seunghb320 approved these changes
이해가 쉽게 잘 됩니다! 피드백 반영과 좋은 글 작성 감사드립니다!!

2023-03-02 14:41 UTC, merged