2월 모바일 팀 포스트
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #270
Opened 2023-02-22 06:38 UTC by simpack0513

2023-02-23 06:23 UTC, iju1633 commented on _posts/2022-2-21-qsortbsearch.md
> +이분탐색은 정렬된 배열에서 원하는 값이 어디 있는지, 있기는 한지 알아내기 위해 사용합니다.
[Nit]  `있기는 한지` 보단 `있는지` 는 어떨까요? 표현이 좀 더 완곡해질 것 같습니다

2023-02-23 06:23 UTC, iju1633 approved these changes, later dismissed
예시 함수의 출력 예시 및 용도도 함께 설명해주시니 내용이 더욱 풍부했습니다 👍

2023-02-23 08:02 UTC, hfjxjjd123 requested changes
c언어를 쓸 때 라이브러리를 이용한 알고리즘을 사용해본 적 없이 비효율적으로 했던 것 같은데
관련된 내용을 알 수 있어서 좋았습니다!

2023-02-23 08:02 UTC, hfjxjjd123 commented on _posts/2022-2-21-qsortbsearch.md
> ++ `width`는 한 정렬할 데이터 한 원소의 크기로, 예를들어 base가 int형 배열이라면 width는 sizeof(int)가 됩니다.
'한 정렬할 데이터 한 원소의 크기'가 눈에 잘 들어오지 않네요
'정렬할 데이터 값 하나의 메모리 크기'라거나.. 다른 워딩을 사용하면 더 좋을 것 같아요!

2023-02-23 08:02 UTC, hfjxjjd123 commented on _posts/2022-2-21-qsortbsearch.md
> +
위의 내용이랑은 무관한 얘긴데
알고리즘과 관련된 내용이니 만큼 어떤 코테문제/문제상황에서 이분탐색과 퀵정렬이 사용될 수 있는지에 대한 예시가 몇 가지 있으면 좋겠어요!

2023-02-28 05:03 UTC, simpack0513 commented on _posts/2022-2-21-qsortbsearch.md
> +이분탐색은 정렬된 배열에서 원하는 값이 어디 있는지, 있기는 한지 알아내기 위해 사용합니다.
더 좋은 표현 같습니다 감사합니다 ㅎㅎ!

2023-02-28 05:05 UTC, simpack0513 commented on _posts/2022-2-21-qsortbsearch.md
> ++ `width`는 한 정렬할 데이터 한 원소의 크기로, 예를들어 base가 int형 배열이라면 width는 sizeof(int)가 됩니다.
아 넵 다시 읽어보니 말이 애매했던거 같습니다.
'정렬할 배열 데이터 값 하나의 메모리 크기'로 수정하겠습니다!
감사합니다

2023-02-28 05:06 UTC, simpack0513 commented on _posts/2022-2-21-qsortbsearch.md
> +
좋은 의견 감사합니다 공간을 하나 더 만들어 추가해보겠습니다 !

2023-03-03 07:52 UTC, hfjxjjd123 approved these changes, later dismissed

2023-03-07 12:50 UTC, iju1633 approved these changes, later dismissed
수정사항까지 반영해주셔서 감사합니다
이분 탐색과 퀵정렬 관련해서 추가적으로 예시 적어주신 것도 잘 읽었습니다👍 👍

2023-04-30 04:35 UTC, hfjxjjd123 approved these changes, later dismissed

2023-05-07 15:12 UTC, SSUHYUNKIM commented
지금 파일 이름이 2022-2-21-qsortbsearch.md로 되어있는데 2023-02-21-qsortbsearch.md로 수정해주세요!

2023-05-09 15:55 UTC, iju1633 submitted a review, later dismissed
일자 변경 피드백 반영 감사합니다 !

2023-05-19 05:56 UTC, hoqn requested changes
블로그팀입니다. 현재 지호님의 포스팅이 렌더링되지 않고 오류가 발생하고 있습니다 :(

![image](https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/4702412/f6056110-defd-4981-94a5-c32d88803e1e)

찾아보니, 우리 블로그를 렌더링하는 데는 Jekyll을 사용하는데, 이 Jekyll에서 사용하는 템플릿 엔진인 Liquid의 문법과 충돌해 발생하는 Jekyll의 자체적인 버그 같습니다. (https://github.com/Shopify/liquid/issues/1491)

따라서 이를 해결하기 위해, 번거로우시겠지만 아래와 같이 `{{`, `}}`에  `{ {`, `} }`와 같이 공백만 추가해주시면 감사하겠습니다!

![image](https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/4702412/0d04f214-d49b-4759-87cb-9b25583da9c7)

(간단하게 스크린샷의 우측 상단에 있는 것처럼 Regex를 이용해 한번에 바꿀 수 있습니다)

2023-05-30 13:16 UTC, iju1633 approved these changes
피드백 반영 감사합니다 !

2023-07-07 12:23 UTC, hoqn approved these changes

2023-07-21 09:00 UTC, merged