2월 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #271
Opened 2023-02-23 04:49 UTC by choidongjune

늦어서 죄송합니다!

2023-02-25 11:39 UTC, hjm507 requested changes
Git Flow에 대해 핵심적인 내용을 잘 설명해주셔서 좋았습니다. 사실 이래저래 개인적으로도 git을 잘 활용하지 못하고 있는 것 같아 아쉬움이 있었는데 굉장히 도움이 된 것 같아요.

이미지 경로 수정이랑 글 전체 내용 맞춤법 검사기로 한번 돌려서 문법만 수정해주시면 될 것 같아요!

2023-02-25 11:39 UTC, hjm507 commented on _posts/2022-02-20-Git_Flow.md
> +![image](../assets/images/post-Git-Flow/git-flow_answer.png)
실제 파일 경로는 post-Git_Flow 인 것 같은데 마크다운에서는 post-Git-Flow로 잘못 적어서 이미지가 제대로 안 보이는 것 같습니다!

2023-02-25 11:39 UTC, hjm507 commented on _posts/2022-02-20-Git_Flow.md
> +image: assets/images/post-Git-Flow/git-flow_overall_graph.png
실제 파일 경로는 post-Git_Flow 인 것 같은데 마크다운에서는 post-Git-Flow로 잘못 적어서 이미지가 제대로 안 보이는 것 같습니다!

2023-02-27 00:30 UTC, yurishin929 reviewed
git에 대해 공부해야겠다고 생각해왔었는데 쉽게 정리된 글을 보니 큰 그림이 이해가 잘 가네요. 좋은 글 잘 봤습니다!

2023-03-03 15:30 UTC, beautifulchoi reviewed
평소 git 개념을 잘 모르고 그냥 툴로써 쓰는 기능들만 썼었는데 브랜치 관리라는 것을 처음 알게 되어 좋았습니다. 글 잘읽었습니다 : )

2023-03-03 15:30 UTC, beautifulchoi commented on _posts/2023-02-20-Git_Flow.md
> +&nbsp;가장 중요한 것은 깃의 명령어를 알고 이를 쓰는 것 또한 중요하지만 위에서도 말씀드렸듯이, 구조와 개념이 가장 중요하고 이를 모두 이해하는 것이 그 언어, 시스템을 의도에 맞게 100% 사용할 수 있기 때문에 깃에서 가장 중요한 개념인 local repository와 remote repository에 대해서 말하고자 합니다. 사용자들은 각각 l
개념을 헷갈리지 않아 찾아보거나 -> 이 부분에 , 넣어주면 좀 더 자연스럽게 읽힐 것 같습니다

2023-03-03 15:30 UTC, beautifulchoi commented on _posts/2023-02-20-Git_Flow.md
> +  + `master` 브랜치는 깃의 기본 브랜치로 배포준비된 코드를 커밋하여 해당 브랜치로 커밋이 생기면 자동으로 빌드하여 배포까지 되는 git hook 스크립트를 사용하기도 하여 자동 CI/CD를 구현하여 사용합니다.
CI CD 옆에 약어를 풀어 써주면 좋을 것 같습니다

2023-04-01 04:28 UTC, beautifulchoi approved these changes

2023-04-03 14:58 UTC, hjm507 approved these changes

2023-05-02 08:52 UTC, beautifulchoi approved these changes

2023-07-21 09:11 UTC, merged