FE팀 2월 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #272
Opened 2023-02-24 18:06 UTC by tnghd5761

늦어서 죄송합니다ㅠ

2023-02-26 17:10 UTC, custardcream98 requested changes
bun은 따로 찾아본적은 없었는데 리뷰하면서 docs 읽다보니 흥미가 생기네요 😁😁 좋은 글 감사합니다!!

2023-02-26 17:10 UTC, custardcream98 commented on _posts/2023-02-25-Bun.md
> +이 benchmark들을 보았을 때, Bun은 Node.js와 Deno보다 몇 배는 더 빠른 것으로 보여집니다. 실제로 테스트를 해보면서 시간을 비교해보고 싶었지만 시간상의 이유로 실제 테스트를 해보지는 못한 바, [Hello world performance: Bun vs Node.js | The JS runtimes](https://medium.com/
해당 글 첫부분에 최신 글을 올리셨다고 하는데, 혹시 내용 갱신해주실 수 있으실까요..??ㅜㅜ [해당 글](https://medium.com/deno-the-complete-reference/node-js-vs-deno-vs-bun-vs-go-a-re-look-at-the-hello-world-performance-d90b76ad61a5)

2023-02-26 17:10 UTC, custardcream98 commented on _posts/2023-02-25-Bun.md
> +이 benchmark들을 보았을 때, Bun은 Node.js와 Deno보다 몇 배는 더 빠른 것으로 보여집니다. 실제로 테스트를 해보면서 시간을 비교해보고 싶었지만 시간상의 이유로 실제 테스트를 해보지는 못한 바, [Hello world performance: Bun vs Node.js | The JS runtimes](https://medium.com/
추가로 이 글 렌더링해보니 마크다운 문법이 이상하게 꼬이더라구요!!

```md
[Hello world performance: Bun vs Node.js \| The JS runtimes](https://medium.com/deno-the-complete-reference/hello-world-performance-bun-vs-node-js-2c9d383b94c1)
```

이렇게 `|` 앞에 역슬래시 붙여서 escape char로 넣어주셔야 잘 나와요!

2023-02-27 11:00 UTC, tnghd5761 commented on _posts/2023-02-25-Bun.md
> +이 benchmark들을 보았을 때, Bun은 Node.js와 Deno보다 몇 배는 더 빠른 것으로 보여집니다. 실제로 테스트를 해보면서 시간을 비교해보고 싶었지만 시간상의 이유로 실제 테스트를 해보지는 못한 바, [Hello world performance: Bun vs Node.js | The JS runtimes](https://medium.com/
> 해당 글 첫부분에 최신 글을 올리셨다고 하는데, 혹시 내용 갱신해주실 수 있으실까요..??ㅜㅜ

앗,,, 제가 이런 부분을 놓쳤었네요 ㅠ 내용 갱신해서 올리도록 하겠습니다!


> 이렇게 | 앞에 역슬래시 붙여서 escape char로 넣어주셔야 잘 나와요!

수정하겠습니다! 감사합니다!

2023-02-28 09:39 UTC, custardcream98 approved these changes, later dismissed
감사합니당 고생 많으셨습니다 👍👍👍

2023-05-05 15:46 UTC, hoqn requested changes
늦게나마 리뷰합니다!

node.js와 deno 외에 Bun은 처음 들어봤는데, 어렵지 않고 흥미있게 읽었습니다! 저도 관심이 생기네요. 좋은 글 감사합니다!

아래 작은 오타만 수정해주시면 될 것 같습니다

2023-05-05 15:46 UTC, hoqn commented on _posts/2023-02-25-Bun.md
> +**응답 대기시간의 경우, 전반적으로 Node.js에 Bun과 Deno에 비해 느리고, 그 차이는 동시성 이 높아질수록 현저하게 늘어나고 있습니다.** Deno는 하위 25%의 대기시간, 즉 응답이 빠르게 도착하는 표본에서는 Bun보다 약간 빠른 모습을 보이지만, 다른 대부분의 표본에서는 Bun이 좀 더 좋은 모습을 보이고 있습니다.
여기 문장에 살짝 오류가 있는 것 같습니다. 아래의 의미로 쓰신 게 맞을까요?

```suggestion
**응답 대기시간의 경우, 전반적으로 Node.js는 Bun과 Deno에 비해 느리고, 그 차이는 동시성 이 높아질수록 현저하게 늘어나고 있습니다.** Deno는 하위 25%의 대기시간, 즉 응답이 빠르게 도착하는 표본에서는 Bun보다 약간 빠른 모습을 보이지만, 다른 대부분의 표본에서는 Bun이 좀 더 좋은 모습을 보이고 있습니다.
```

2023-05-19 07:57 UTC, tnghd5761 commented on _posts/2023-02-25-Bun.md
> +**응답 대기시간의 경우, 전반적으로 Node.js에 Bun과 Deno에 비해 느리고, 그 차이는 동시성 이 높아질수록 현저하게 늘어나고 있습니다.** Deno는 하위 25%의 대기시간, 즉 응답이 빠르게 도착하는 표본에서는 Bun보다 약간 빠른 모습을 보이지만, 다른 대부분의 표본에서는 Bun이 좀 더 좋은 모습을 보이고 있습니다.
네 맞습니다! suggestion 반영했습니다. 감사합니다!

2023-05-22 05:51 UTC, hoqn approved these changes

2023-06-05 14:41 UTC, merged