3월 모바일팀 블로그
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #275
Opened 2023-03-23 14:34 UTC by hfjxjjd123

3월 모바일팀 블로그

2023-04-01 03:13 UTC, iju1633 commented on _posts/2023-03-23-embedded-database.md
> +`SQLite`는 다른 관계형 데이터베이스 시스템과 마찬가지로 **SQL 쿼리**를 사용하여 데이터베이스를 조작할 수 있으며, 다양한 데이터 형식을 지원합니다.
공백 2개를 활용하여 줄바꿈이 필요해보입니다

e.g. `-**성능**` -> `-**성능**  `

2023-04-01 03:14 UTC, iju1633 commented on _posts/2023-03-23-embedded-database.md
> +이 때의 경험으로 위험성을 낮추고 데이터베이스 관리나 트랜잭션 관리를 위해서 내장 데이터베이스 시스템을 써서 데이터를 저장할 필요성을 느꼈고, 이후 리팩토링 하는 과정에서 내장 데이터베이스 시스템을 적극적으로 활용해 봐야겠다고 느꼈습니다.
표현 수정이 필요해보입니다. `리팩토링 하는` -> `리팩토링하는`

2023-04-01 03:18 UTC, iju1633 commented on _posts/2023-03-23-embedded-database.md
> +*이러한 상황 이외에도 앞서 설명한 `SQLite`와 `Realm`의 특성을 고려해서 개발 목적과 상황에 맞는 데이터베이스를 사용하시길 바랍니다
오타가 있는 것 같아요 ! `*이러한` -> `이러한`

2023-04-01 03:21 UTC, iju1633 commented on _posts/2023-03-23-embedded-database.md
> +[정리하며](#정리하며)
링크 연결해주신 거 너무 좋아요 👍

2023-04-01 03:22 UTC, iju1633 commented on _posts/2023-03-23-embedded-database.md
> +저는 개발활동을 하던 도중 다음과 같은 상황에 직면했습니다.
`저는`과 같은 표현은 빼고 좋을 것 같아요.

2023-04-01 03:23 UTC, iju1633 requested changes
저는 모바일 쪽에 내재된 DB라 하면 Room과 SQLite만 알았던 거 같은데 덕분에 Realm도 알아갑니다 👍 

또한, 맞춤법 검사기 한 번 돌려주시는 거 추천드릴게요 !

2023-04-02 13:33 UTC, hfjxjjd123 commented
좋은 피드백 감사합니다!! 😄

2023-04-02 13:55 UTC, hfjxjjd123 commented
1차 수정 했습니다.

2023-04-30 04:22 UTC, iju1633 approved these changes
피드백 반영 감사드려요 ! LGTM 👍

2023-06-12 07:02 UTC, merged