3월 백엔드 블로그 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #277
Opened 2023-03-31 11:42 UTC by Lee-Sang-Min1998

3월 백엔드 블로그 포스팅입니다.

2023-04-01 02:44 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +세션은 무엇인가? 세션에 대한 개념은 몰라도 한번쯤 들어온 적은 있을 것이다. 세션 불일치를 설명하기 전에 세션에 대해 알아보자.
표현 수정이 필요해보입니다. `들어온` -> `들어본`

2023-04-01 02:46 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +HTTP는 상태가 유지되지 않는(Stateless), 비연결지향(Connectionless) 프로토콜이다.
[Nit] 가독성을 위해 표현을 수정해봐도 좋을 것 같아요.  `비연결지향(Connectionless)` -> `비연결지향(Connectionless)적인`

2023-04-01 02:49 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +1. Scale-Up: 서버 자체의 성능을 향상시키는 방법. 이 방법을 이용하면 여전히 단일 서버 환경이다. 단일 서버 환경이기 때문에 세션 불일치가 발생하지 않아 좋을 것 같지만
Scale-out의 설명과 같은 형식이면 더욱 가독성이 좋을 것 같아요. `방법.` -> `방법이다.`

2023-04-01 02:50 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +모든 트래픽이 하나의 서버에 집중 되고 서버 장애가 발생할 시에 서버가 복구 될 때까지 모든 서비스가 중단된다.
표현 수정이 필요해보입니다. `집중 되고` -> `집중되고`, `복구 될` -> `복구될`

2023-04-01 02:51 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +위 그림처럼 유저의 로그인 요청이 서버1에 전달되고 서버1에 세션이 저장 되었다고 가정해보자.
아래의 설명에서 서버 2라고 되어있으므로 서버 1 혹은 서버 2를 서버2로 적는게 가독성이 더욱 좋을 것 같아요 !

2023-04-01 02:52 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +
필요 없는 공백은 없애주셔도 좋을 것 같아요 !

2023-04-01 02:53 UTC, iju1633 commented on _posts/2023-03-31-session-and-redis.md
> +2. 생성된 임의의 세선 ID 값이 응답 헤더 속의 쿠키에 잘 전달 된 것을 확인할 수 있다.
표현 수정이 필요해보입니다. `세선` -> `세션`

2023-04-01 02:54 UTC, iju1633 requested changes
세션 불일치 문제가 발생할 수 있는 예시도 제공해주셔서 이해하기 편했습니다 👍 

피드백 이외에 맞춤법 검사기 한 번 돌려보시는 거 추천드립니다 !

2023-04-01 10:19 UTC, seunghb320 requested changes
간단한 맺음말 정도가 있으면 더 좋지 않을까 합니다.ㅎㅎㅎ 볼륨이 큰 서비스를 제공하면 로드밸런싱이 필수라고 들었는데  그에 따른 부차적인 문제인 세션 불일치와 관련 개념들에 대해 쉽게 잘 설명해주신것 같습니다! 덕분에 이해가 쏙쏙 됐어요:) 좋은 글 감사합니다!

2023-04-01 10:19 UTC, seunghb320 commented on _posts/2023-03-31-session-and-redis.md
> +단점이 존재한다. 속도 VS 정보의 영구성 중 어떤 것이 중요한지 문제이다.
'중요한지 -> 중요한지의'로 수정하면 어떨까 합니다.

2023-04-01 12:58 UTC, Lee-Sang-Min1998 commented on _posts/2023-03-31-session-and-redis.md
> +위 그림처럼 유저의 로그인 요청이 서버1에 전달되고 서버1에 세션이 저장 되었다고 가정해보자.
혹시 리뷰해주신 부분에서 "서버 1 혹은 서버 2"가 어떤 부분일까요?

2023-04-01 14:00 UTC, Lee-Sang-Min1998 commented
리뷰해 주신 부분 반영 완료했습니다~!~!

2023-04-01 14:58 UTC, iju1633 commented
@Lee-Sang-Min1998 
반영 감사합니다 ! 다만, 리뷰하는 입장에선 어떤 부분이 반영이 된 건지 잘 모르기에, 앞으로는 comment에 반영된 부분은 이모지로 표시해주시면 더욱 좋을 것 같습니다 👍

2023-04-01 14:58 UTC, iju1633 approved these changes
LGTM 👍 👍

2023-04-02 02:30 UTC, Lee-Sang-Min1998 commented
> 

네넵~!

2023-04-02 02:39 UTC, seunghb320 approved these changes
고생하셨습니다!! 덕분에 좋은 지식 얻었습니다!

2023-06-12 07:04 UTC, merged