3월 FE팀 블로그
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #278
Opened 2023-04-04 14:01 UTC by SSUHYUNKIM

늦어서 죄송합니다..

2023-05-07 15:23 UTC, SSUHYUNKIM commented
이름에 - 추가하기 / 이미지 깨지는 문제 해결

2023-05-19 06:19 UTC, hoqn requested changes
평소에 접하기 어렵지만 흥미로운 내용 다뤄주셔서 감사합니다!

저도 전에 가볍게 Unity를 시도해봤지만 게임 개발이 웹이나 앱 개발과 상당히 달라서 포기했던 기억이 있습니다 ㅎㅎ
그런데 이 글을 통해 Unity에서 직접 다양한 학습 콘텐츠를 제공한다는 사실과 단순히 게임 엔진 이상의 활용도를 가지고 있다는 점을 알게 되었네요. 흥미로운 것 같습니다!

2023-05-19 06:19 UTC, hoqn commented on _posts/2023-03-21-what-is-unity.md
> +[유니티와 협업으로 진행된 <가상현실 프로그래밍 교육>, 생생한 후기 밀착 취재!](https://liberaledu.snu.ac.kr/board/blog/view/862)
![image](https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/4702412/456a34d7-3a6a-4e42-b88a-2c1f15e5bc60)

이 부분이 링크로 렌더링되지 않고 이상하게 렌더링되네요 :(
다음과 같이 수정해주시면 될 듯 합니다.

```suggestion
[유니티와 협업으로 진행된 \<가상현실 프로그래밍 교육\>, 생생한 후기 밀착 취재!](https://liberaledu.snu.ac.kr/board/blog/view/862)
```

2023-07-11 13:08 UTC, hoqn approved these changes

2023-07-21 09:12 UTC, merged