3월 DATA 블로그
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #279
Opened 2023-04-05 12:09 UTC by ha789ha

3월 Data/Ml 블로그 pr입니다

2023-04-08 00:37 UTC, beautifulchoi reviewed
데이콘 하며 정형데이터 분류문제에 간단한 알고리즘이지만 꽤나 상위권 코드들이 이 방법을 많이 사용하였기에 이전부터 공부를 해야겠다 생각했는데 쉽게 정리되어 있는 글을 보아서 좋았습니다 : ) 
글 작성하시느라 수고하셨습니다!

2023-04-08 00:37 UTC, beautifulchoi commented on _posts/2023-04-05-Gradient_boosting.md
> +우리는 Gradient Boosting을 알기 전에 우선 트리 기반 모델에 대해 알아볼 필요가 있습니다. 트리 기반 모델은 머신러닝에서 널리 사용되는 알고리즘 중 하나로, 데이터의 구조와 패턴을 학습하는 데 사용됩니다. 트리 기반 모델의 기본 단위는 의사결정트리(decision tree)로, 데이터를 분석하고 예측을 수행하는데 도움이 됩니다.
"우리는"은 빼도 될 것 같습니다 : )

2023-04-08 00:37 UTC, beautifulchoi commented on _posts/2023-04-05-Gradient_boosting.md
> +의사결정트리의 구조는 위의 사진과 같으면 크게 뿌리 노드(Root Node), 분기 노드, 리프 노드로 이루어져 있습니다.
위의 사진과 "같으면" -> 같으며 로 고쳐야 할 것 같아요!

2023-04-08 00:37 UTC, beautifulchoi commented on _posts/2023-04-05-Gradient_boosting.md
> +마지막으로는 Gradient Boosting 알고리즘의 대표적인 라이브러리 중 하나인 Xgboost의 적용 코드 예시를 작성하면서 마무리하겠습니다. Gradient Boosting을 실제 코드에 적용하려면 수많은 파라미터를 조절하는 과정이 필요한데요 오늘은 Gradient Boosting에 대해 이론적으로 설명하는 시간이라 기회가 된다면 파라미터 조절과
필요한데요 -> 필요한데요,  혹은 "필요합니다." 로 수정하면 좋을 것 같습니다.

2023-05-03 13:50 UTC, hjm507 commented on _posts/2023-04-05-Gradient_boosting.md
> +![image](../assets/images/post-Gradient_boosting/tree_example.png)
이미지 배경이 없어서 그런지 여기서 다크 모드에서는 잘 안보이는 것 같은데 이미지 수정 가능할까요?

2023-05-03 13:52 UTC, hjm507 requested changes
실습과 함께 어렵지 않게 설명되어 있어서 좋았습니다! 예전에 부스팅 기법 관련해서 봤어서 반갑네요 :) 이미지 부분만 확인 부탁 드려요...!

2023-05-08 03:12 UTC, hoqn commented on _posts/2023-04-05-Gradient_boosting.md
> +image: ![image](../assets/images/post-Gradient_boosting/machine_learning.jpg)
frontmatter 포맷 관련 오류가 나서 렌더링이 되지 않습니다! 다음과 같이 수정해주세요
```suggestion
image: ../assets/images/post-Gradient_boosting/machine_learning.jpg
```

2023-05-28 12:20 UTC, ha789ha commented
피드백 부분 수정하였습니다!

2023-05-28 16:53 UTC, yurishin929 approved these changes

2023-05-31 13:03 UTC, beautifulchoi approved these changes

2023-07-21 09:30 UTC, merged