4월 백엔드 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #280
Opened 2023-04-18 09:40 UTC by BackJiwan

4월 백엔드 블로그 포스팅 작성하여서 보냅니다.

2023-04-29 15:28 UTC, seunghb320 requested changes

2023-04-29 15:28 UTC, seunghb320 commented on _posts/2023-04-18-Exception.md
> +일반적인 상황에서, 특히 Java 언어를 사용한 개발 환경에서라면 Java가 제공하는 Exception을 잘 활용하는 것은 에러를 핸들링하기에 적합한 방법으로 보입니다. 하지만 Exception이 항상 에러를 처리하는 정답은 아니며 상황과 환경에 따라서 적절한 에러처리 기술을 잘 활용할 수 있어야 할 것 입니다.
'것 입니다->것입니다'로 바꾸는데 어떨까 합니다!!

2023-04-30 04:34 UTC, iju1633 commented on _posts/2023-04-18-Exception.md
> +	if ~~{
[Nit] ` if ~~{` 도 좋지만 `if (조건문) {` 이란 표현을 통해 예시를 더욱 가독성 있게 표현할 수 있을 것 같아요 !

2023-04-30 04:34 UTC, iju1633 requested changes
저도 별 생각없이 Exception을 주로 사용했던 것 같은데 좋은 글 정말 감사드립니다 !

2023-05-01 09:36 UTC, BackJiwan commented
피드백 감사합니다~
반영하여서 push 하였습니다!

2023-05-01 10:50 UTC, iju1633 approved these changes
피드백 반영 감사합니다 ! LGTM 👍

2023-05-05 05:53 UTC, seunghb320 approved these changes
피드백 반영 및 좋은 글 감사합니다!!

2023-07-21 09:50 UTC, merged