4월 모바일 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #281
Opened 2023-04-26 12:32 UTC by Sooyeon-Kwon

감사합니다 ㅎㅎ

2023-04-27 11:29 UTC, hfjxjjd123 approved these changes, later dismissed
포스트가 점검 체크리스트 형식이라 재밌게 읽혀요
평소에 UX를 별로 생각하고 지나갔는데 이번에 배워가는 것 같습니다~~

2023-04-27 11:29 UTC, hfjxjjd123 commented on _posts/2023-04-22-checklist.md
> +- [ ] 실수로 상호 작용을 전달할 수 있는 요소는 없는지 확인하기
일관되게 '상호 작용'>>'상호작용'이 좋을 것 같아요
그리고 저는 상호작용이라는 단어가 바로 와닿진 않는데, 상호작용이라는게 제공되는 앱 서비스를 유저가 이용하는 걸 말하는 건가요?
상호작용이 어떤 상호작용인지에 대한 한 줄 설명정도 있으면 좋을 것 같아요!

2023-04-27 11:29 UTC, hfjxjjd123 commented on _posts/2023-04-22-checklist.md
> +
2. 문단?에서 3. 문단으로 넘어갈 때(1->2, 3->4도), 공백간격을 충분히 넣으면 가독성이 더 좋아질 것 같아요

2023-04-30 04:07 UTC, iju1633 commented on _posts/2023-04-22-checklist.md
> +> 이는 목적성 관리와 의사결정을 방해한다는 단점이 있으나, 80/20 규칙을 통해 해결할 수 있습니다. 80/20 rule*은 80%의 benefit은 20%의 action에서 나온다는 규칙 입니다.<br><br><br>
80/20 rule* 이라고 표기가 되어있는데 볼드처리를 하고 *는 빼는 건 어떨까요?

`80/20 rule*은 80%의 benefit은 20%의 action에서 나온다는 규칙 입니다` -> `**80/20 rule**이란 80%의 benefit은 20%의 action에서 나온다는 규칙을 의미합니다.`

2023-04-30 04:15 UTC, iju1633 commented on _posts/2023-04-22-checklist.md
> +> 이는 목적성 관리와 의사결정을 방해한다는 단점이 있으나, 80/20 규칙을 통해 해결할 수 있습니다. 80/20 rule*은 80%의 benefit은 20%의 action에서 나온다는 규칙 입니다.<br><br><br>
또한, `<br><br><br>`에 의해 인용선이 필요 이상으로 길어진 것 같은데, 수정 부탁드리겠습니다 !

<img width="1024" alt="스크린샷 2023-04-30 오후 1 14 10" src="https://user-images.githubusercontent.com/43805087/235335208-6cd538ce-0475-4de1-9a64-46b862c5f96e.png">

2023-04-30 04:19 UTC, iju1633 commented
[Nit] 앱 체크리스트 부분에 1~4의 내용을 목차로 한 번에 보여주고 설명으로 들어가는 건 어떨까요?

2023-04-30 04:21 UTC, iju1633 requested changes
앱을 출시하기 전에 고려해야할 여러 사항들이 있는데, ux 측면에서 많은 조언 주셔서 감사합니다 !

2023-05-01 10:53 UTC, iju1633 commented
반영이 된 부분에 대해선 이모지로 확인 부탁드립니다 :)

2023-05-19 06:49 UTC, hoqn requested changes
마크다운 형식상 오류 관련해서 몇 가지 적었습니다 :)

2023-05-19 06:49 UTC, hoqn commented on _posts/2023-04-22-checklist.md
> +image: ../assets/images/post-list/1.jpg
이미지의 확장자가 잘못되어 렌더링되지 않습니다! 이미지 경로(.jpeg로 바꾸시면 될 것 같아요) 확인 부탁드립니다 :)

더불어서, 이미지가 `assets/images/post-list`에 존재하는데, 본 포스팅 파일 이름은 `checklist`라서 이왕이면 이미지가 있는 폴더 이름을 `post-checklist`로 변경해주시면 좋을 것 같습니다.

2023-05-19 06:49 UTC, hoqn commented on _posts/2023-04-22-checklist.md
> +명확해야 하며 clear, 즉각적이고 timely, 상황에 맞게 contextual, 실행 가능 actionable<br><br><br>
대부분의 마크다운 렌더러의 특성상, 2. 3.과 같이 1이 아닌 숫자로 리스트를 시작해도 무조건 1로 시작하도록 렌더링됩니다.

이 글에서의 경우, `1. 행동 유도성` 이후에 다른 줄들이 있어 리스트가 끝나고, `2. 일관성`은 새로운 리스트로 해석되어 아래와 같이 `1. 일관성`으로 렌더링됩니다.

![image](https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/4702412/a8ba9733-34dd-4bf6-8c40-4fc757bb769a)

따라서, 제가 제안하는 해결 방법은 다음의 세 가지가 있습니다!

1. **리스트가 유지되도록 조정**
    
    이 경우 `1. 행동 유도성` 과 `2. 일관성` 사이의 모든 줄을 들여쓰기(탭 또는 띄어쓰기 4자)를 해주면 해결됩니다. 이런 경우 들여쓰기된 줄들이 모두 `1. 행동 유도성`과 같이 첫번째 리스트 아이템으로 인식됩니다!

    ![image](https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/4702412/c850a2d1-a999-4239-b73f-b1cbc0f6906e)
    
2. **리스트로 해석되지 않도록 조정**

   또는 애초에 리스트를 사용하지 않는 방법이 있습니다. 이런 경우엔 `1. 행동 유도성`을 `### 1. 행동 유도성`과 같이 헤딩으로 바꾸거나, `**1. 행동 유도성**`과 같이 bold를 넣어주는 방법이 흔하게 사용됩니다.

3. **리스트의 시작 인덱스를 임의로 지정할 수 있습니다.**

    ```
    {:start="2"}
    2. 일관성
    ```
    _우리 블로그에서 사용되는 Kramdown 렌더러에서는 지원하는 문법입니다_

2023-05-22 17:11 UTC, iju1633 commented on _posts/2023-04-22-checklist.md
> +image: ../assets/images/post-list/1.jpg
@Sooyeon-Kwon 이 부분 반영 부탁드립니다 !

2023-05-24 06:55 UTC, iju1633 approved these changes
피드백 반영 감사합니다 ! 👍

2023-07-28 08:46 UTC, merged