4월 DA/ML 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #282
Opened 2023-04-26 16:08 UTC by 00HS

깃허브를 많이 안써봐서 잘 실행되는지 모르겠네요!
확인 부탁드립니다!

2023-05-03 14:19 UTC, hjm507 approved these changes, later dismissed
보안 쪽은 생각해보지 못한 주제라 흥미롭네요...! 공격은 오히려 손실을 최대화 시키는 쪽으로 학습시킨다는 발상이 재밌으면서 무섭네요. 적대적 방어 관련해서도 나중에 더 써주시면 좋을 것 같습니다!

2023-05-03 14:19 UTC, hjm507 commented on _posts/2023-04-27-Adversarial_attack.md
> +위의 예시에서처럼, 기존의 해킹 방법과는 다르게, 머신러닝 알고리즘이 내제하고 있는 취약점을 이용한 방법이 바로 적대적 공격입니다. 즉, 적대적인 공격은 미세하게 변경된 입력 데이터인 적대적 예제를 활용해 신경망의 정확도를 떨어뜨리는 행위입니다.
내제하고 있는 -> 내재하고 있는 오타인 것 같습니다!

2023-05-05 06:01 UTC, beautifulchoi reviewed
흥미로운 주제에 대해서 간결하게 잘 써주셔서 재미있게 읽었습니다. 글 작성하시느라 수고하셨습니다 : )

2023-05-05 06:01 UTC, beautifulchoi commented on _posts/2023-04-27-Adversarial_attack.md
> +image: 포스트 커버 이미지
포스트 커버 이미지 주소가 안들어가 있는 것 같습니다

2023-05-05 06:01 UTC, beautifulchoi commented on _posts/2023-04-27-Adversarial_attack.md
> +대표적인 적대적 공격인 FSGM에 대해 코드를 통해 살펴보도록 하겠습니다.
대해 -> 대하여 로 수정하는 것이 좋을 것 같습니다

2023-05-05 06:01 UTC, beautifulchoi commented on _posts/2023-04-27-Adversarial_attack.md
> +FSGM은 공격 목표를 정할 수 없는 non-targeted 방식이자, 대상 모델의 정보가 필요한 화이트박스 방식입니다.
위에서 영어로 white box라고 썼어서, 여기서도 white box라고 쓰는 것이 좋을 것 같습니다

2023-05-19 14:17 UTC, hoqn requested changes

2023-05-19 14:17 UTC, hoqn commented on _posts/2023-04-27-Adversarial_attack.md
> +image: ![deeplearning](../assets/images/post-Adversarial Attack/deeplearning.jpg)
프론트매터의 image에는 경로만 입력해주셔야 렌더링이 됩니다..!

```suggestion
image: ../assets/images/post-Adversarial Attack/deeplearning.jpg
```

2023-05-21 06:51 UTC, beautifulchoi approved these changes

2023-05-28 16:53 UTC, yurishin929 approved these changes

2023-06-02 19:19 UTC, hjm507 approved these changes

2023-07-28 08:53 UTC, merged