BiT 논문 리뷰 및 이미지 업로드 완료
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #283
Opened 2023-04-30 07:41 UTC by Yooonlee

BiT 논문 리뷰 및 이미지 업로드 완료

2023-05-03 14:50 UTC, hjm507 requested changes
어렵긴 하지만 전이 학습이 쉽게 접하지는 못하다 보니 흥미로웠습니다. 다만, 후반부부터는 단락 별로 주제가 많이 바뀌기도 하고, 내용이 길다 보니 쉽게 머리에 들어오지 않는 것 같습니다.

 맨 앞 부분에 목차나 배경 지식 등에 관해서 정리해서 미리 언급해주고 이런 순서대로 설명 드리겠다라고 하면 읽기 훨씬 좋을 것 같습니다.

2023-05-03 14:50 UTC, hjm507 commented on _posts/2023-04-29-BiT.md
> +입니다.
문장이 끊겨 있어서 붙여줘야 할 것 같습니다.

2023-05-04 02:21 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +입니다.
목차를 만들어 해당사항 수정하였습니다.

2023-05-05 06:50 UTC, beautifulchoi reviewed
흥미로운 논문에 대해 글을 작성해주셔서 재미있게 읽었습니다! 글 쓰느라 수고하셨습니다 : )

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +- 본 논문의 메서드는 이전까지 SOTA이상의 높은 정확도를 보입니다.
"이전까지의 SOTA 모델 이상의" 로 수정하는게 좋을 것 같습니다

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +- 보통 CIFAR-10의 경우 epoch 100~200 이 baseline(기본)인데 5~10번 정도로 해도 충분합니다.
이부분 오류인지 제 컴퓨터에서만 그렇게 보이는 건지는 모르겠는데,, 좀 이상하게 표현이 되는 것 같습니다

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +- 감마 : 스케일
이 부분도 감마와 베타의 설명이 같은 줄에서 표현이 되고 있어 감마에 대한 설명인 것 같습니다.

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +- 감마 : 스케일
감마와 베타를 묶어서 선형결합 파라미터라고 설명하는 것도 좋아보입니다.

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +- Batch Norm
위에서 BN은 Batch normalization 레이어를 넣지 않았다는 것 같은데, 밑에서 설명에 Batch Norm에 대해 설명하고 있어 혼동을 유발할 수 있을 것 같습니다.

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +## Upstream 사전에 좋은 특징 추출기를 만들기 위해 사용
Upstream 뒤에 : 를 붙이는 것이 메끄러울 것 같습니다

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +2. MixUp 2개의 데이터씩 pair로 묶어 2개의 정보를 묶어 사용합니다. (데이터 증진 기법)
Mixup에 대한 설명은 다음 문장에서 하는 것이 통일감 있을 것 같습니다

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +
Upstream과 downstream의 finetuning 차이가 간략히 설명되어 있으면 좋을 것 같습니다.

2023-05-05 06:50 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +
결론에 대해 간략하게 쓰면 좋을 것 같습니다

2023-05-11 03:29 UTC, hjm507 approved these changes, later dismissed

2023-05-19 07:00 UTC, hoqn requested changes

2023-05-19 07:00 UTC, hoqn commented on _posts/2023-04-29-BiT.md
> +[8.SSL(준지도학습)과 비교](#준지도학습-이란)
목차 걸어주신 거 정말 좋습니다 :)

다만, 의도했던 대로 작동하지 않는 문제가 있습니다.

각 헤딩의 id는 `(`, `)`, `[`, `]`와 같은 특수문자를 **제외**시킵니다! 따라서 링크에서 아래와 같이 이런 문자들을 다 없애시면 의도대로 작동할 것 같습니다.

```suggestion
[1.Representation Learning 소개](#representation-learning)

[2.전이 학습의 개요](#전이-학습transfer-learning의-개요)

[3.[배경지식] 전이 학습 구현 방식](#배경지식-전이-학습-구현-방식)

[4.[배경지식]  배치 정규화](#배경지식-배치-정규화)

[5.Upstream ](#upstream-사전에-좋은-특징-추출기를-만들기-위해-사용)

[6.Downstream ](#downstream-fine-tuning)

[7.Fine-tuning 비교 ](#fine-tuning-비교)

[8.SSL(준지도학습)과 비교](#준지도학습-이란)
```

2023-05-19 07:42 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +- 감마 : 스케일
수정하였습니다

2023-05-19 07:43 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +- 보통 CIFAR-10의 경우 epoch 100~200 이 baseline(기본)인데 5~10번 정도로 해도 충분합니다.
이 부분은 저도 이상하게 잘 수정이 안되는 것 같습니다..

2023-05-19 07:43 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +- 본 논문의 메서드는 이전까지 SOTA이상의 높은 정확도를 보입니다.
수정하였습니다.

2023-05-19 07:44 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +- Batch Norm
설명 문장을 넣었습니다.

2023-05-19 07:45 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +
위 189~204에서 설명되었다고 생각했습니다.

2023-05-19 07:48 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +
수정하였습니다.

2023-05-19 07:49 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +[8.SSL(준지도학습)과 비교](#준지도학습-이란)
그렇군요.. 몰랐던 사실을 알게해주셔서 감사합니다! 
수정하였습니다.

2023-05-20 04:19 UTC, beautifulchoi commented on _posts/2023-04-29-BiT.md
> +[4.[배경지식]  배치 정규화](#배경지식-배치-정규화)
여기 부분만 목차에서 링크가 안 걸려 있는 것 같습니다.

2023-05-21 05:54 UTC, Yooonlee commented on _posts/2023-04-29-BiT.md
> +[4.[배경지식]  배치 정규화](#배경지식-배치-정규화)
수정했습니다.

2023-05-21 06:47 UTC, beautifulchoi approved these changes

2023-06-02 19:21 UTC, hjm507 approved these changes

2023-07-30 04:01 UTC, merged