5월 백엔드팀 블로그
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #285
Opened 2023-05-25 12:34 UTC by seunghb320

2023-05-25 13:48 UTC, iju1633 requested changes
편리함을 쫓다보니 세션과 쿠키로만 사용자 관리를 주로 했었는데요, 덕분에 JWT에 대한 이해가 더 쉬웠고 처음 JWT 개념을 접해보시는 분에게 아주 도움이 되는 글이 될 거라 생각합니다 ! 수고하셨어요 👍

2023-05-25 13:48 UTC, iju1633 commented on _posts/2023-05-02-jwt.md
> +이 용도로 사용되는 것에는 JWT 외에도 쿠키와 세션이 있지만 이 글에서는 우리의 관심사인 JWT 토큰에 대해서 다뤄보도록 하겠습니다.
블로그 내용에서 코드를 제외하고 설명할 때의 jwt 표현을 통일하면 더 좋을 것 같습니다 ! (jwt or JWT)

2023-05-25 13:48 UTC, iju1633 commented on _posts/2023-05-02-jwt.md
> +jwt는 토큰을 서버에서 관리하지 않기에 발급한 토큰을 무효화할 수 없다는 단점이 있습니다.
`jwt` -> `jwt를 통한 사용자 관리는` 과 같이 추가적인 설명이 필요해보입니다.

2023-05-25 13:48 UTC, iju1633 commented on _posts/2023-05-02-jwt.md
> +(따라서 위의 jwt 예시에서도 페이로드에 jwt의 생성, 만료시간 외에 유저의 인덱스 정보밖에 없는걸 볼 수 있습니다.)
[Nit] `따라서 위의 사진에서도 페이로드 부분에는 생성, 만료시간 외에 유저의 인덱스 정보만 있는 것을 확인할 수 있습니다.` 등 과 같이 표현을 수정한다면 가독성이 좀 더 좋을 것 같습니다.

2023-05-26 07:52 UTC, pasly0920 commented on _posts/2023-05-02-jwt.md
> +이 용도로 사용되는 것에는 JWT 외에도 쿠키와 세션이 있지만 이 글에서는 우리의 관심사인 JWT 토큰에 대해서 다뤄보도록 하겠습니다.
저도 똑같이 생각했습니다! 수정하면 더 보기 좋을 것 같습니다.

2023-05-26 07:55 UTC, pasly0920 approved these changes, later dismissed
고생하셨습니다. 언급한 부분들에 대해서만 간단히 수정 바랍니다.

2023-05-26 07:55 UTC, pasly0920 commented on _posts/2023-05-02-jwt.md
> +그래서 서비스 제공자는 보관을 잘 할 필요가 있으며 학생 개발자들의 경우 실수로라도 시크릿 키를 깃허브 등의 오픈 플랫폼에 업로드해서는 안 됩니다.
시크릿 키를 어떻게 보관하는 지에 대한 예시가 있으면 더 좋을 것 같습니다.

2023-05-27 05:50 UTC, seunghb320 commented on _posts/2023-05-02-jwt.md
> +이 용도로 사용되는 것에는 JWT 외에도 쿠키와 세션이 있지만 이 글에서는 우리의 관심사인 JWT 토큰에 대해서 다뤄보도록 하겠습니다.
앗 제목과 소제목은 대문자로 하고 내용은 소문자로 하려 했는데 놓친 부분이 있었군요ㅠㅠ
말씀해주셔서 감사합니당! 수정하는 김에 통일성 있게 다 소문자로 수정했습니다!

2023-05-27 06:59 UTC, pasly0920 approved these changes
LGTM!

2023-05-30 12:37 UTC, iju1633 approved these changes
수정사항 반영 감사합니다 ! LGTM 👍

2023-07-30 04:11 UTC, merged