230526 한진형 블로그 글 업로드
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #286
Opened 2023-05-26 12:45 UTC by real-brother

230526 한진형 블로그 글 업로드

2023-05-29 05:55 UTC, hfjxjjd123 reviewed
내용 자체가 좋아서 오타 수정만 하면 될 것 같아요
작성한 코드들을 주석과 함께 올려주신 것도 좋았고,
프로젝트 과정에서 고민한 흔적을 같이 올려주셔서 재밌게 볼 수 있었습니다 👍🏻

2023-05-29 05:55 UTC, hfjxjjd123 commented on _posts/2023-05-26-Arcgis_map.md
> +최종적으로 링크들의 총 거리와, 경로 리스트들이
글이 끊긴 것 같아요

2023-05-29 05:55 UTC, hfjxjjd123 commented on _posts/2023-05-26-Arcgis_map.md
> +### 4. 출발, 도착 건물 번호를 입력하면 그 경로 사에 경로 노드 리스트 및 전체 거리 리턴하는 함수 구현
"경로 사" 쪽에 단어가 누락된 것 같아요

2023-05-29 05:55 UTC, hfjxjjd123 commented on _posts/2023-05-26-Arcgis_map.md
> +노드는 갈림길, 건물 통로, 꺾이는 길을 모두 이어절 수 있는 중간 기지 역할을 합니다.
"이어절"이 오타가 아닌가 싶습니다

2023-05-30 12:28 UTC, iju1633 commented on _posts/2023-05-26-Arcgis_map.md
> +이때 저희는  위치 정보를 고려한 시간표 계획과 캠퍼스 포트폴리오 관리를 동시에 할 수 있는 종합 학사관리 어플을 만들게 되었습니다.
필요 없는 공백이 보입니다 !

2023-05-30 12:30 UTC, iju1633 commented on _posts/2023-05-26-Arcgis_map.md
> +건물간 유저의 경로와 소요시간을 구하기 위해 꼭 필요한 내용인데 api로 구현할 수 없음을 확인했습니다. 그래서 다양한 방법을 고려하다가 직접 구현하기로 결정하였습니다
`지원하고있지만` -> `지원하고 있지만`
`결정하였습니다` -> `결정하였습니다.`
와 같이 어법 수정 부탁드립니다 ! 전체적으로 맞춤법 검사기 돌려보시는 것도 추천드려요 ㅎㅎ

2023-05-30 12:32 UTC, iju1633 commented on _posts/2023-05-26-Arcgis_map.md
> +### 4. 출발, 도착 건물 번호를 입력하면 그 경로 사이에 경로 노드 리스트 및 전체 거리 리턴하는 함수 구현
[Nit] 리턴보다는 반환이라고 표현하는 게 좀 더 가독성이 좋아보입니다 !

2023-05-30 12:33 UTC, iju1633 commented on _posts/2023-05-26-Arcgis_map.md
> +이때 출,도착점의 중간 지점을 지도의 초기 위치로 두었습니다.
출발/도착점이라고 표현하는 것 어떨까요?

2023-05-30 12:33 UTC, iju1633 commented on _posts/2023-05-26-Arcgis_map.md
> +이 코드로 네이버 지도에 출,도착 마커 및 경로를 추가하였습니다
위 comment와 동일합니다 !

2023-05-30 12:35 UTC, iju1633 commented on _posts/2023-05-26-Arcgis_map.md
> +(쉽게 말해, 전농관 옆 횡단보도에서 미래관 횡단보도 앞까지 1개의 노드로 구성이 되어있습니다)
[Nit] 괄호를 제거해도 되지 않을까 싶습니다 !

2023-05-30 12:35 UTC, iju1633 requested changes
코드에 친절한 주석 덕분에 이해가 더 쉬웠습니다. 앱 개발기를 간략하게 설명해주셔서 감사합니다 !

2023-05-31 11:30 UTC, real-brother commented
피드백 사항 완료하여, 다시 커밋했습니다!

2023-06-04 05:45 UTC, hfjxjjd123 approved these changes

2023-10-31 04:48 UTC, merged