5월 DA/ML 블로그 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #288
Opened 2023-06-02 19:17 UTC by hjm507

5월 DA/ML 블로그 포스팅입니다.

2023-06-15 02:37 UTC, beautifulchoi requested changes
중요한 테스크 중 하나인데, 쉽게 잘 설명해주신 것 같습니다. 예전에 딥러닝 스터디할 때 세미나에서 들었던 내용이어서 반가운 내용이네요 :)
바쁘신 와중에 글 작성하느라 수고하셨습니다!!

2023-06-15 02:37 UTC, beautifulchoi commented on _posts/2023-06-03-anomaly-detection.md
> +이상 탐지란, 일반적으로 대부분의 데이터에서 크게 벗어나거나 잘 정의된 정상적인 행동 양식을 따르지 않는 항목이나 사건을 식별하는 것을 의미합니다.
가독성이 조금 떨어지는 것 같습니다
"일반적으로 이상탐지란, 대부분의 데이터가 가지고 있는 특성에서 크게 벗어나거나 정상적인 행동 양식을 따르지 않는 항목이나 사건을 식별하는 것을 의미합니다" 라고 서술하는건 어떨까요??

2023-06-15 02:37 UTC, beautifulchoi commented on _posts/2023-06-03-anomaly-detection.md
> +> (환자의 비정상적인 건강 지표)
예시라고 명시하는 것이 좋을 것 같습니다

2023-06-15 02:37 UTC, beautifulchoi commented on _posts/2023-06-03-anomaly-detection.md
> +이러한 Undersampling 기법 중 하나인 SMOTE에 대해 알아보겠습니다.
여기 Oversampling을 설명하다 Undersampling 기법이 소개되었습니다. SMOTE는 오버샘플링 기법이기 때문에 Undersampling-> Oversampling으로 수정해야 할 것 같습니다.

2023-06-15 02:37 UTC, beautifulchoi commented on _posts/2023-06-03-anomaly-detection.md
> +
결론이 간략하게 있으면 좋을 것 같습니다

2023-07-08 15:25 UTC, hjm507 commented on _posts/2023-06-03-anomaly-detection.md
> +
결론 파트 추가하였습니다!

2023-07-08 15:25 UTC, hjm507 commented on _posts/2023-06-03-anomaly-detection.md
> +이상 탐지란, 일반적으로 대부분의 데이터에서 크게 벗어나거나 잘 정의된 정상적인 행동 양식을 따르지 않는 항목이나 사건을 식별하는 것을 의미합니다.
다시 읽어보니 저도 그게 맞는 것 같아서 해당 부분 말씀 대로 수정해주었습니다. 감사합니다 :)

2023-07-08 15:25 UTC, hjm507 commented on _posts/2023-06-03-anomaly-detection.md
> +이러한 Undersampling 기법 중 하나인 SMOTE에 대해 알아보겠습니다.
오타 수정했습니다.

2023-07-08 15:26 UTC, hjm507 commented on _posts/2023-06-03-anomaly-detection.md
> +> (환자의 비정상적인 건강 지표)
예시라고 해당 부분 모두 명시해 주었습니다.

2023-07-15 11:00 UTC, beautifulchoi approved these changes
수고하셨습니다 :)

2023-10-31 04:56 UTC, merged