front post July
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #289
Opened 2023-07-19 04:56 UTC by Seoyoung1108

프론트팀 7월 블로그 포스팅입니다!

2023-07-31 13:50 UTC, hoqn requested changes
늦은 리뷰 죄송합니다 ㅠ

ec2로 React 앱을 배포하는 방법에 대해 튜토리얼식으로 따라갈 수 있도록 쉽게 써주신 점이 인상깊습니다!
또한 실제 배포하였을 때 실제로 겪었던 백엔드 서버와의 통신 문제(CORS)와 그 해결 방법에 대해 적어주셔서 좋은 것 같습니다.

중간중간 등장하는 개념들의 보충 설명이 필요할 것 같기도 하지만, 한편으론 너무 복잡해지지 않는 선에서 적어주셔서 따라가기 수월한 점도 있다는 점에서 이 상태로도 좋은 것 같습니다 :)

아래 설명된 형식상의 오류 하나만 고쳐주시면 될 것 같습니다! 수고하셨어요!

2023-07-31 13:50 UTC, hoqn commented on _posts/2023-07-23-aws-ec2-nginx.md
> +</br>
`</br>` 부분이 아래와 같이 렌더링됩니다! 해당 부분을 지우시거나 `<br/>`로 고치시면 정상적으로 렌더링될 것 같아요
(개인적으로는 불필요한 개행 같아 지우시는 걸 추천드립니다!)

![image](https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/4702412/6040037f-6653-4d91-aeb6-be7a8f2e724b)

2023-07-31 16:45 UTC, Seoyoung1108 commented on _posts/2023-07-23-aws-ec2-nginx.md
> +</br>
리뷰 감사합니다!! 오류 수정 완료했습니다!

2023-08-01 13:58 UTC, hoqn approved these changes

2023-10-31 04:29 UTC, merged