7월 BE 포스팅
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #290
Opened 2023-07-19 14:41 UTC by pasly0920

2023-07-21 12:42 UTC, iju1633 commented on _posts/2023-07-19-oop-principle.md
> +규칙 9: 게터/세터/프로퍼티를 쓰지 않는다
<img width="1021" alt="스크린샷 2023-07-21 오후 9 41 03" src="https://github.com/GDSC-University-of-Seoul/gdsc-university-of-seoul.github.io/assets/43805087/45b2616a-54e6-4860-8a37-fe92f876a405">
위 사진과 같이 줄바꿈이 반영되어 있지 않습니다. 또한, 규칙 9에 여타 다른 규칙과 동일하게 `.`으로 마무리하는 건 어떨까요?

2023-07-21 12:46 UTC, iju1633 commented on _posts/2023-07-19-oop-principle.md
> +아래의 코드는 Map을 wrapping하고 Private 변수로 선언함으로서 Method로만 접근 가능하고 다양한 비즈니스 로직들을 같이 넣을 수 있도록 변경하였습니다.
어미의 통일이 필요합니다.
`~니다.` -> `~다.`

2023-07-21 12:49 UTC, iju1633 commented on _posts/2023-07-19-oop-principle.md
> +위의 코드 또한 어느 정도 정돈된 것으로 보이지만, isUserHaverOnlyOneTeam이나 isTeamNameLeast2Character 같은 validation 부분이 해당 Class 의 최하단에 private function으로 추가되어 기하급수적으로 Class의 길이가 늘어났다.
[Nit] 메서드명이나 일부 영어 표현의 경우 "'"로 감싸 가독성을 높일 수 있습니다.
e.g. isUserHaverOnlyOneTeam  -> `isUserHaverOnlyOneTeam `

2023-07-21 12:51 UTC, iju1633 commented on _posts/2023-07-19-oop-principle.md
> +.을 통해서 자주 내부의 property나 method를 불러와 사용하는 경우가 있다. 이 때 .을 통해 연결을 단 한 번만 하라는 것이다.
여기서 줄바꿈을 하는 건 어떨까요? 추가적으로 .말고 `.`을 통해 온점이라는 것을 더욱 명시할 수 있을 것 같습니다 !

2023-07-21 12:52 UTC, iju1633 requested changes
구체적인 예를 들어 객체지향 생활 체조 9가지 원칙에 대해 설명해주셔서 감사합니다 ㅎㅎ 이번 글을 통해 일급 컬렉션에 대해 더 자세히 알아가네요 !

2023-07-22 11:50 UTC, pasly0920 commented
@iju1633 긴 글 읽어주셔서 감사합니다 수정 완료했습니다.

2023-07-22 15:03 UTC, iju1633 commented on _posts/2023-07-19-oop-principle.md
> +예를 들면 `saveMeetingTeam이라는` naming보다는 `createEmptyMeetingTeam`이라는 naming이 조금 더 직관적이지 않을까 하는 생각이 들고,
`의 범위 수정 부탁드립니다 !
: `saveMeetingTeam이라는` -> `saveMeetingTeam`이라는

2023-07-22 15:05 UTC, iju1633 commented on _posts/2023-07-19-oop-principle.md
> +이를 `MeetingTeamUsers를` 통해 private collection 일급 콜렉션을 사용하여 직접 접근을 막고, 해당 콜렉션으로부터 의도를 가진 Method를 뽑아내어 사용할 수 있도록 했다.
동일하게 범위 수정 부탁드립니다 ! : `MeetingTeamUsers를` -> `MeetingTeamUsers`를

2023-07-23 02:54 UTC, pasly0920 commented
@iju1633  수정 완료했습니다!

2023-07-23 04:19 UTC, iju1633 approved these changes, later dismissed
LGTM 👍

2023-07-24 06:29 UTC, seunghb320 requested changes
글을 시작하실 때 높임의 통일을 위해 '제가'보다는 '내가'가 나을것 같습니다. 그 외에는 너무 좋습니다!

2023-07-24 10:06 UTC, pasly0920 commented
@seunghb320 수정 완료했습니다 감사합니다!

2023-10-31 05:01 UTC, merged