apply multiple author
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #32
Opened 2020-10-11 12:57 UTC by MOBUMIN

* author.yml에서 개인 web과 git을 분리
* authors 가 여러명일 때 포스트 내에서 여러명이 세로로 보이도록 함
* blog 아이콘 적용을 위해 fontawsome 버전 수정
* post 내의 author 색 검정색으로 변경
* post 내의 author 간격 수정
* contributing에 git web 변경사항 고지

2020-10-18 15:01 UTC, jeongukjae reviewed
나머지는 다 좋은 것 같아요!! 하지만 각각의 유저 밑에서 `git` 필드를 만들필요가 있을까?는 의문입니다. 원래 key값으로 github username을 쓰고 있었기 때문에 `https://github.com/{_____}` 이런 식으로 쓰는 것이 가능하지 않을까요??

2020-10-19 10:16 UTC, MOBUMIN commented
> 나머지는 다 좋은 것 같아요!! 하지만 각각의 유저 밑에서 `git` 필드를 만들필요가 있을까?는 의문입니다. 원래 key값으로 github username을 쓰고 있었기 때문에 `https://github.com/{_____}` 이런 식으로 쓰는 것이 가능하지 않을까요??

2020-10-26 07:22 UTC, Enoch-Kim requested changes
* contribute.md 파일 세부 내용 수정
* post 예시 캡쳐..부탁드립니다.

2020-10-26 07:22 UTC, Enoch-Kim commented on _includes/featuredbox.html
> +                                {% if post.authors %}
authors로 변경했다면 CONTRIBUTING.md 파일에 line 21 > author -> authors 로 바꾸고 설명을 추가해야될 듯 싶습니다.
그리고 브랜치에 포스트가 없어서 그런지 예시가 없어 어떻게 변했는지 변화를 보기 어렵습니다 ㅠㅠ

2020-10-26 08:00 UTC, MOBUMIN commented on _includes/featuredbox.html
> +                                {% if post.authors %}
예시 포스트 남아있는채로 머지하면 불편할 것 같아서 지웠는데,,, 다시 넣어두겠습니당

2020-10-26 09:05 UTC, Enoch-Kim commented on _includes/featuredbox.html
> +                                {% if post.authors %}
@MOBUMIN 예시 포스트를 넣기보단 캡쳐 가능할까요? 이 Comment에 달아주시면 좋을 것 같습니다.
* 예시 화면
* 예시 md Code

2020-10-26 15:13 UTC, MOBUMIN commented on _includes/featuredbox.html
> +                                {% if post.authors %}
![image](https://user-images.githubusercontent.com/57705512/97190518-275a9a00-17e9-11eb-8cff-8cf17f67622b.png)

`---
title: 여러 사람 확인용 샘플 포스트
authors: [MOBUMIN, jeongukjae,r4k0nb4k0n,beeetea,MOBUMIN, jeongukjae,r4k0nb4k0n,beeetea]
tags: [태그1, 태그2, 태그3]
image: assets/images/jumbotron.jpg
layout: post
featured: true
---

samples`

2020-10-26 16:06 UTC, Enoch-Kim commented on _includes/featuredbox.html
> +                                {% if post.authors %}
혹시 row 2개 먼저 채우고 다음 row로 가는 방식은 안될까요??사람이 4명일 때 덜 예쁠것 같아서요..ㅎㅎ

2020-10-27 13:45 UTC, MOBUMIN commented on _includes/featuredbox.html
> +                                {% if post.authors %}
아 제가 아마 column으로 했는데 그럼 이걸 row로 바꿔야겠네요...>! 노..력....예정....

2020-10-27 14:00 UTC, MOBUMIN commented on _includes/featuredbox.html
> +                                {% if post.authors %}
![image](https://user-images.githubusercontent.com/57705512/97311855-2b012600-18a8-11eb-83f5-00b1ff72a03e.png)

2020-10-30 15:01 UTC, jeongukjae approved these changes

2020-10-31 00:49 UTC, closed without merging

2020-10-31 00:52 UTC, Enoch-Kim commented
Close Unselected Branch
* issue27/new-multiple-author 가 대체