git 협업 포스트&이미지 업로드
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #38
Opened 2020-11-03 13:55 UTC by MOBUMIN

* git 협업 관련 포스트 업로드
* 관련 이미지 업로드

2020-11-03 15:01 UTC, Enoch-Kim requested changes
추가하거나 빼면 더 좋을 것들 적어뒀습니다.
그리고 의견을 묻는 부분도 있으니 눈치보지말고 의견을 적어주세요!

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +branch는 master에서 떨어져 나오는 아이입니다. master에서 잠깐 떼어내서 작업하고 다시 master랑 합칠 거에요!(merge) 2번에서 아주 약간 더 설명해드릴테니 일단 넘어가시죠..!
요즘 github이 master에서 main으로 기본 브랜치를 옮기는 추세인 것 같아요!
새로 레포 생성하면 main을 생성하도록 나오더라구요! 
이것 때문에 혼동될 수 있으니 master 혹은 main이라고 해주거나 다른 설명을 추가하면 어떨까 싶습니다.
![스크린샷 2020-11-03 오후 11 31 59](https://user-images.githubusercontent.com/60127664/97997874-c7897200-1e2c-11eb-96c2-3115d4b18b3e.png)

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +commit은 Git에 업로드한다는 느낌으로 이해하면 편합니다. 이전까지 작업은 Git에는 적용되지 않고, Local 환경에서만 바뀌었기 때문에 업로드를 해야 적용이 되겠죠?
업로드보다는 기록으로 설명하는게 어떨까요??
뒤에 나오는 업로드와 겹쳐 헷갈릴 수 있을 것 같다는 생각을 했습니다 ㅎ
Push 하는 과정을 업로드라고 하는게 더 이해가 쉽지 않을까 생각하는데 다른 분들은 어떤가요??

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +그래서 branch를 따로 만들 거에요. 현재의 master branch에서 잠깐 다른 줄기로 이동해서 작업을 하고, 다시 master branch와 합칠 거에요. 작업하는 사람들이 아닌 다른 사람들은 master branch의 모습만 보게 됩니다!
브랜치에 대한 사진과 함께 부연 설명이 있다면 더 좋겠어요!
만약 힘드시다면 그냥 링크라도 넣어주는게 어떨까요?

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +아, branch를 만들기 전에, 제 local에 있는 master branch가 업데이트가 안 되어 있을 수도 있으니까 Github Desktop에서 pull을 미리 해줍시다.
Github Desktop에서는 Pull을 어떻게 하나요? 
저는 안써봐서 쉽게 할 수 있는 건지 궁금해서요 ㅎㅎ

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +혹시 모르고 master branch에서 이미 작업한 내역이 있나요? 그렇다면 아래 빨간 박스로 되어 있는 부분을 눌러서 변경 내역을 가져와주세요!
이 부분은 괜히 넣어서 혼란을 줄 수 있지 않을까 하는 우려가 듭니다..

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +이제 해당 commit을 원격 repository로 push 해줄거에요. commit은 제 local에서만 저장하는 거라면, push는 조금 더 멀리 보내는 느낌입니다.
commit은 제 local에 기록을 남기는 거라면, push는 원격에 남긴 기록들을 업로드 하는 것으로 생각하시면 됩니다.
라고 쓰는 건 어떤가요..? 다른 분들은 어떤게 이해가 편할지 모르겠어요.. 의견 나눠주세요

또 commit 을 저장, 기록이라는 단어로 표현하면 좋을 것 같은데 어느게 나을까요?

2020-11-03 15:01 UTC, Enoch-Kim commented on _posts/2020-11-03-how-to-use-git.md
> +VScode를 사용하신다면, EXTENSIONS에서 markdownlint을 설치해주세요. 그러면 형식이 틀렸을 경우 노란 줄로 표시해줍니다!
캡쳐 하나만 첨부하면 완벽!

2020-11-04 12:37 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +commit은 Git에 업로드한다는 느낌으로 이해하면 편합니다. 이전까지 작업은 Git에는 적용되지 않고, Local 환경에서만 바뀌었기 때문에 업로드를 해야 적용이 되겠죠?
아아아ㅏ아 이거 제가 졸려서 헷갈린 것 같아요 push가 git에 업로드한다는 느낌이죠..!!!!!!

2020-11-04 12:38 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +아, branch를 만들기 전에, 제 local에 있는 master branch가 업데이트가 안 되어 있을 수도 있으니까 Github Desktop에서 pull을 미리 해줍시다.
버튼 하나만 누르면 됩니당...!!!!!

2020-11-04 12:38 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +혹시 모르고 master branch에서 이미 작업한 내역이 있나요? 그렇다면 아래 빨간 박스로 되어 있는 부분을 눌러서 변경 내역을 가져와주세요!
헉 이 두 줄 다요??

2020-11-04 12:40 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +이제 해당 commit을 원격 repository로 push 해줄거에요. commit은 제 local에서만 저장하는 거라면, push는 조금 더 멀리 보내는 느낌입니다.
위에서는 commit을 업로드라고 해놓고 여기선 저장이라고 하는 멍청이... push-업로드 commit-저장 요느낌으로 수정하는게 맞는것같아요!

2020-11-04 12:40 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +VScode를 사용하신다면, EXTENSIONS에서 markdownlint을 설치해주세요. 그러면 형식이 틀렸을 경우 노란 줄로 표시해줍니다!
아 ㅋㅋ 귀찮아서 업로드 안했는데 들켰네요.. ㅎㅎ

2020-11-04 12:41 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +branch는 master에서 떨어져 나오는 아이입니다. master에서 잠깐 떼어내서 작업하고 다시 master랑 합칠 거에요!(merge) 2번에서 아주 약간 더 설명해드릴테니 일단 넘어가시죠..!
오호 처음 알아가는 정보네요! 감사합니다!

2020-11-04 12:41 UTC, MOBUMIN commented on _posts/2020-11-03-how-to-use-git.md
> +그래서 branch를 따로 만들 거에요. 현재의 master branch에서 잠깐 다른 줄기로 이동해서 작업을 하고, 다시 master branch와 합칠 거에요. 작업하는 사람들이 아닌 다른 사람들은 master branch의 모습만 보게 됩니다!
브랜치에 대한 이해는 저도 얄팍해서 ;_; 링크 첨부가 나을 것 같네유

2020-11-04 14:23 UTC, Enoch-Kim approved these changes
LGTM!!

2020-11-06 08:51 UTC, jeongukjae approved these changes

2020-11-06 12:03 UTC, merged