Post 추가 및 Author 수정
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #45
Opened 2020-11-05 04:23 UTC by SHEELE41

Post 추가 및 Author 수정

2020-11-06 16:04 UTC, Enoch-Kim requested changes
중복된 리뷰는 달지 않았어요. 확인하시고 변경해주시면 감사하겠습니다!
* url 형식
* 포스트의 속성 추가
* 시작 이미지 제거
* 불필요한 줄바꿈 제거
* br 태그 제거
* 코드박스 언어 명시
* 헤더 룰 적용
* 문장 끝 띄어쓰기 제거
* 파일 끝 띄어쓰기 추가

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +
위의 image 에 등록했기 때문에 자동으로 들어가서 없어도 됩니다.
```suggestion
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _data/author.yml
> +  web: https://oasisfores.com/
끝에 슬래시는 빼주시는게 국룰!
```suggestion
  web: https://oasisfores.com
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +---
layout 속성을 명시해주지 않아 깨졌네요.. layout과 feature 속성 추가해줍시다!
```suggestion
---
layout: post
title:  "[ Kotlin ] Coroutine 기본 정리 및 Android에서의 사용 방법"
authors: [sheele41]
tags: ["Mobile"]
image: https://oasisfores.com/wp-content/uploads/2020/11/post_main.png
featured: true
---
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +# 시작하기 전에...
1. 시작하기 전에 나오는 말은 메인 타이틀이 아니기 때문에 # 보다는 ##을 넣고 ... 을 빼주세요
2. 첫번째 헤드의 경우 무조건 1개만 존재할 수 있어요. 이후의 헤드는 ## 부터하시고 순서대로 증가시켜야합니다.
3. 항상 헤드나 강조 다음에는 한줄 띄워줍니다.
```suggestion
## 시작하기 전에

```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +<br>
불필요한 줄바꿈은 제거해주세요. (html 요소는 사용하지 않는 것을 권장합니다.)
```suggestion
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +# Coroutine 사용을 위한 사전 준비
메인 헤드를 title로 지정했기 때문에 서브 헤드로 가져갑시다. 그리고 헤드 뒤에는 항상 한줄 띄워주세요.
```suggestion

## Coroutine 사용을 위한 사전 준비

```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +# Coroutine 만들기
이것도 ##으로
```suggestion
## Coroutine 만들기
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +![basic\_coroutine](https://oasisfores.com/wp-content/uploads/2020/11/basic_coroutine.png)
끝에 띄어쓰기 같은건 없애주세요 (VScode나 vim에서 markdownlint 설치하면 잡아줄거예요.
```suggestion
![basic\_coroutine](https://oasisfores.com/wp-content/uploads/2020/11/basic_coroutine.png)
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +1. **CoroutineContext**를 이용하여 Coroutine이 실행될 **CoroutineScope**를 만들고
번호와는 한줄 띄워주세요
```suggestion
우선 **전체적인 흐름**을 설명드리면

1. **CoroutineContext**를 이용하여 Coroutine이 실행될 **CoroutineScope**를 만들고
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +<br>
헤드는 차례로 증가하는게 권장됩니다. + br 제거
```suggestion
### **Context**로 **Scope**를 만들고, **Builder**를 이용하여 그 **Scope** 안에서 실행!  
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +# 첫 번째, CoroutineContext
줄은 두칸 띄우나 한칸 띄우나 동일하게 동작해요 + 헤드는 차례로 증가 -> 3개
```suggestion
### 첫 번째, CoroutineContext
```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +```
1. 코드 블럭은 위아래로 한줄씩 띄워줘야합니다. 표현이 안돼서 백쿼트 2개를 썼지만 3개 쓰시면 됩니다.
2. 그리고 {.lang:default .decode:true} 안먹습니다. bash script 니 bash를 명시해주세요.
```suggestion
간단히 **build.gradle (:app)** 파일에 다음 코드를 입력해줌으로써 Coroutine을 사용할 수 있습니다.

``bash
dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9'
}
``

```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +이상으로 글을 마치겠습니다. 감사합니다. \^\^
마지막은 한줄 띄워주세요. 그래야 파일이 끝났음을 알 수 있습니다.
```suggestion
이상으로 글을 마치겠습니다. 감사합니다. \^\^

```

2020-11-06 16:04 UTC, Enoch-Kim commented on _posts/2020-11-05-mobile-coroutine.md
> +**1. 사용자 지정 CoroutineScope**
번호는 강조보다는 헤더를 사용해주세요.
```suggestion
#### 1. 사용자 지정 CoroutineScope
```

2020-11-06 18:27 UTC, SHEELE41 commented on _posts/2020-11-05-mobile-coroutine.md
> +---
아 Contribution.md에 저 항목이 없길래 블로그에 글 올라가면 자동생성되는 요소인 줄 알았는데 아니었네요 😂

2020-11-06 18:44 UTC, SHEELE41 commented on _posts/2020-11-05-mobile-coroutine.md
> +<br>
음 이 경우는 헤드(소제목?)가 아니라 그냥 강조하고 싶어서 '글자 크기 키우고 굵게 할 수 있는 방법 없나... '해서 한건데 다른 방법은 없는걸까요?

2020-11-07 08:26 UTC, MOBUMIN commented on _posts/2020-11-05-mobile-coroutine.md
> +이상으로 글을 마치겠습니다. 감사합니다. \^\^
![image](https://user-images.githubusercontent.com/57705512/98436406-57296c00-211e-11eb-87f8-ab5242afe374.png)
저만 이렇게 보일까요? 일부러 이런 이모티콘을 사용하신건가요!? 아니면 ^^이 뭔가 명령어라서 적용되지 않도록 \이걸 붙이신건가요!?

2020-11-07 08:50 UTC, SHEELE41 commented on _posts/2020-11-05-mobile-coroutine.md
> +이상으로 글을 마치겠습니다. 감사합니다. \^\^
헉 제 블로그에서 먼저 작성한 글을 html 파일 그대로 md 형식으로 변환하면서 생겼나봐요...! ^^ 표시 맞습니다...! 
한 번 검토를 하긴 한건데 왜 제대로 보였던 걸로 기억이 날까요... 😂
덕분에 수정하면서 강조 제대로 안들어간것도 찾을 수 있었네요 리뷰 감사합니다!

2020-11-08 02:16 UTC, MOBUMIN approved these changes
저는 헤더룰은 잘 모르겠네요..ㅎㅎㅎ 그래서 LGTM 찍겠습니다! LGTM😊

2020-11-08 15:48 UTC, Enoch-Kim approved these changes
중요하지 않은 요소 빼고는 완벽하게 돼서 Approve 하겠습니다. (이는 다른 포스트들을 포함해서 추후 제가 정리할 예정)
LGTM!!!!!

2020-11-08 15:48 UTC, merged