fall-intro team 10월
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #49
Opened 2020-11-06 09:04 UTC by maybeluna

fall-intro team 10월 달에 진행했던 일을 블로그 형식으로 작성해보았습니다.

2020-11-07 08:36 UTC, MOBUMIN requested changes
contributing.md 에 명시된 대로 파일 제목과 내용을 수정해주세요!
vscode를 쓰신다면, markdownlint를 사용하는 걸 권장드립니다.

제목 관련해서는 내용이 없어서 추가합니다! 마크다운 파일 이름을 YYYY-MM-DD-제목.md 형식으로 수정해주세요!

2020-12-29 16:15 UTC, Enoch-Kim requested changes
Github 닉네임만 변경하시면 바로 머지해도 될 것 같아요!
(참고로 수빈님 레포의 author.yml 파일 제가 컨플릭트 방지하도록 변경했습니다...)

2020-12-29 16:15 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +authors: [Subin Kim]
자신의 이름이 아닌 github nickname을 적어주시면 됩니다!! 
```suggestion
authors: ["maybeluna"]
```

2020-12-29 16:15 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Nov.md
> +authors: [Subin Kim]
여기도 github nickname으로 변경해주세요
```suggestion
authors: ["maybeluna"]
```

2021-01-02 17:31 UTC, Enoch-Kim requested changes
내용 + 오타 + 설명 넣었습니다!
정말 열심히 하셨더라구요.. 감동입니다 ㅠㅠ

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +로컬 저장소(개인 컴퓨터)와 원격 저장소(중앙 관리 컴퓨터 환경)로 이루어져 있으며 앞으로 Git을 통해 채첨이된다.
오타났습니다! (채첨 -> 채점)
```suggestion
로컬 저장소(개인 컴퓨터)와 원격 저장소(중앙 관리 컴퓨터 환경)로 이루어져 있으며 앞으로 Git을 통해 채점이된다.
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +    그래서 강제로 pull(git -hard HEAD)도 해보고 유튜브에 git add -A를 해보라고 해서 해보기도 했지만 결과는... 여전히 이 상태 **error failred to push some refs to 'origin'**이 뜨면서 병합 불가!
* 작은 문법 수정이 필요할 것 같네요 (유튜브에 -> 유튜브에서)
* 저의 블로그 특성 상 `...`이 이쁘게 안나옵니다. `..`으로 바꾸는건 어떨까요?
```suggestion
    그래서 강제로 pull(git -hard HEAD)도 해보고 유튜브에서 git add -A를 해보라고 해서 해보기도 했지만 결과는.. 여전히 이 상태 **error failred to push some refs to 'origin'**이 뜨면서 병합 불가!
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +    후... ㅠ 애증의 git... !
여기도 `...` 대신 `..` 추천드려요!
```suggestion
    후.. ㅠ 애증의 git..!
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +문서 편집기로는 vscode를 사용하여 작업을 한다.
* 전체적으로 문단을 너무 자주 나눈다는 생각이 들어요. 이런경우 그냥 붙여쓰는 것이 좋습니다!
* 문장을 나눠주면 더 읽기 편할 것 같아요.
```suggestion
 코딩 초보자가 접근하기 쉽다는 python을 사용하여, 코딩이라는 것의 뼈대를 잡아가도록 하였다.
문서 편집기로는 vscode를 사용하여 작업을 한다.
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +```
통일성을 주면 더 좋을 것 같습니다. 모두 `-`로 나타내면 어떨까요?
```suggestion
- 문자 프린트

  ```python
  >>> print("Hello World!")
  Hello World
  
  >>> print("cake")
  >>> print("cookie")
  >>> print("tea")
  cake
  cookie
  tea
  ```

- 변수 프린트

  ```python
  >>> my_var = 10
  >>> print(my_var)
  10
  ```

- 연산

  ```python
  >>> print(5+5)
  >>> print(4-2)
  >>> print(2*8)
  >>> print(9/3)
  10
  2
  16
  3.0
  
  >>> print(8 ** 2)
  >>> print(53 // 7)
  >>> print(7 % 4)
  64
  7
  3
  ```
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +과제 1을 통해 배운 점
강조해주면 더 좋을 것 같아요!
```suggestion
### 과제 1을 통해 배운 점
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +input 명령어란 사용자가 입력한 값을 어떤 변수에 대입할 때 쓰는 명령어로 input에 입력되는 모든 것은 문자열(str) 취급하기 때문에 이를 주의해야한다.
콤마 추가해주면 더 잘 읽혀질 것 같습니다.
```suggestion
input 명령어란 사용자가 입력한 값을 어떤 변수에 대입할 때 쓰는 명령어로, input에 입력되는 모든 것은 문자열(str) 취급하기 때문에 이를 주의해야한다.
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +if문은 조건을 판단하고 그 조건에 맞는 상황이 오면 수행하는 기능을 가졌다. 여러가지 상황이 주어졌을 때 컴퓨터에서 이를 판단하고 정확한 수행을 하기 위해 쓰인다.
목적어가 빠진 것 같습니다!
```suggestion
if문은 조건을 판단하고 그 조건에 맞는 상황이 오면 if문 안의 코드를 수행하는 기능을 가졌다. 여러가지 상황이 주어졌을 때 컴퓨터에서 이를 판단하고 정확한 수행을 하기 위해 쓰인다.
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +과제 2를 통해 배운 점
이것도 헤드로 주면 더 좋을 것 같습니다!!
```suggestion
### 과제 2를 통해 배운 점
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +과제 3을 통해 배운 점
이것도 헤드!
```suggestion
### 과제 3을 통해 배운 점
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-11-06-Fall_intro-Oct.md
> +지난 한 달 동안 목표했던 과제 5까지 완수하지 못했다. 생각보다 시간이 없었고 게다가 시험기간이라 그런지 매일 밤새는게 일상이다보니 많이 해보지 못했던 것은 핑계일까...?
`...` 대신 `..`
```suggestion
지난 한 달 동안 목표했던 과제 5까지 완수하지 못했다. 생각보다 시간이 없었고 게다가 시험기간이라 그런지 매일 밤새는게 일상이다보니 많이 해보지 못했던 것은 핑계일까..?
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +   - Shell: 사용자 명령 쉘에 입력하고 해석 후 커널에게 전달하는 것으로 shell 종류는 다양해 사용자 취향에 맞는 shell을 선택 가능하다.
무슨말인지 의미가 정확히 전달이 안되는 것 같습니다.. 문장을 나누고, 내용을 구체화 해주실 수 있을까요??

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +     echo $ 0
이거 띄어쓰기하면 작동 안합니다..ㅎㅎ
`$`가 환경변수를 참조하는 기능을 하는데, 붙여쓰지 않으면 `$ 0` 라는 결과만 나와요
```suggestion
     echo $0
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +목적: 과제 4의 경우 두 환경(window, ubuntu)에서 진행되기 때문에 각 코드를 짜고 깃에 병합을 해야하므로 우분투에 git 환경을 구현해야한다!
헤더, 강조로 나타내면 더 좋을 것 같아요!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +***항상 pull을 하면 error가 떠서 늘 clone을 쓰고 있는데 왜 자꾸 에러가 뜰까?
이건 수정사항이 아닌 설명입니다.. ㅎㅎ 
git이 동작하기위해 `.git`파일을 사용하는데요, 이 깃파일에서 설정되어있는 저장소를 기준으로 명령을 실행합니다.
pull의 경우 .git 파일에 설정돼있는 원격(remote -> ex. origin) 저장소를 당겨오는 역할을 하는 명령어예요.
근데, 여기서 만약 .git파일이 없거나 .git 파일이 있더라도 remote가 등록되어있지 않다면 pull 명령어가 동작하지 않습니다.

git clone의 경우 해당 저장소의 인터넷 주소(?)를 기준으로 복제해오기 때문에 .git 파일 또한 가져와서 설정해줘요.
이때 기본으로 원격 저장소(origin)이 자동으로 설정되기 때문에 단순히 pull을 했을 때 동작이 되는 겁니다.

**추가로 말씀드리자면 `git pull` 이라고 치지 마시고 원하는 원격 저장소와 브랜치를 지정하는게 좋은 방식이에요. 예를들어 `git pull origin master` 이런 식으로 `git pull <remote> <branch>` 사용하는 것을 추천합니다.

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +***항상 pull을 하면 error가 떠서 늘 clone을 쓰고 있는데 왜 자꾸 에러가 뜰까?
이해 안되는 부분은 호준님 괴롭혀서 확실히 이해하고 넘어가시는 것을 추천합니다!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +- 사용 **불가능**한 코드 : `sort()`, `sorted()` 등의 내장 정렬 함수
불가능 보다는 사용 금지된 이라는 표현이 어떨까요??
```suggestion
- 사용이 **금지된** 코드 : `sort()`, `sorted()` 등의 내장 정렬 함수
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +  - 선택 정렬: 제자리 정렬 알고리즘의 하나로, 주어진 리스트 중 최솟값을 찾고 그 값을 맨 앞에 위차한 값과 교환한다. 맨 처음 위치를 뺀 나머지 리스트도 같은 방법으로 교체
오타 입니닷! (위차한 -> 위치한)
```suggestion
  - 선택 정렬: 제자리 정렬 알고리즘의 하나로, 주어진 리스트 중 최솟값을 찾고 그 값을 맨 앞에 위치한 값과 교환한다. 맨 처음 위치를 뺀 나머지 리스트도 같은 방법으로 교체
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +  "정렬 알고리즘을 이해하는 것 자체가 너무 어려웠으며 하나하나 수식을 따라가면서 이해하도록 노력했다. 이해하기 위해서 가시적인 자료가 필요했는데 아래의 동영상이 많이 도움이 되었다. "
아래의 동영상이 어디있죠??

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +- 사용 **불가능**한 코드 : `itertools`
이것도 사용이 금지된 으로 변경하는건 어떨까요?

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +- 사용 **불가능**한 코드 : `itertools`
선택사항입니다!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +- 사용 **불가능**한 코드 : `sort()`, `sorted()` 등의 내장 정렬 함수
선택사항 입니다!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +  ```
`-`를 빼는게 맞는 것 같은데 오타인가요?
```suggestion
  ```python
    print_hello()
  ```
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +```
들여쓰기 빠진 것 같습니다!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +  ```
여기도 -가 빠져야할 것 같습니다.

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +```
들여쓰기할지 말지 위에서부터 통일이 되어야할 것 같아요!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +  ```
이것도 - 제거!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-24-Fall_intro-Nov.md
> +Hint 💡 : 섭씨에서 화씨로 바꾸는 공식은... 검색해봐야겠죠?
`...` 보다는 `..` 선호합니다!
```suggestion
Hint 💡 : 섭씨에서 화씨로 바꾸는 공식은.. 검색해봐야겠죠?
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +  ```
`-` 제거해주시면 더 좋을 것 같습니다!
```suggestion
  ```python
  rock_only()
  ```
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +  ```
`-` 제거!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- ```phthon
* `-` 제거
* 오타 수정
```suggestion
  ```python
```

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +여욱은 숫자를 특이하게 비교하는 것으로 유명하다.
여욱이.. 뭐죠..?

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +t
오타인가요??

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- ```python
`-` 제거!

2021-01-02 17:31 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- 사용 **불가능**한 코드 : `itertools`
금지된 이라는 표현은 어떤가요?

2021-01-04 06:20 UTC, MOBUMIN requested changes
포스팅에 사용된 이미지는 혹시 따로 assets/images 내에 폴더를 만들어서 불러와주실 수 있을까요~?

2021-01-06 16:35 UTC, maybeluna commented on _posts/2020-12-25-Fall_intro-Dec.md
> +여욱은 숫자를 특이하게 비교하는 것으로 유명하다.
밤 늦게 남겨서 죄송해요ㅠ 여욱이는 사람 이름입니다 :)

2021-01-06 16:36 UTC, maybeluna commented on _posts/2020-12-25-Fall_intro-Dec.md
> +t
헉 맞습니다 고치겠습니다!

2021-01-06 16:41 UTC, maybeluna commented on _posts/2020-11-06-Fall_intro-Oct.md
> +로컬 저장소(개인 컴퓨터)와 원격 저장소(중앙 관리 컴퓨터 환경)로 이루어져 있으며 앞으로 Git을 통해 채첨이된다.
넵 수정했습니다 :)

2021-01-06 16:42 UTC, maybeluna commented on _posts/2020-11-06-Fall_intro-Oct.md
> +    그래서 강제로 pull(git -hard HEAD)도 해보고 유튜브에 git add -A를 해보라고 해서 해보기도 했지만 결과는... 여전히 이 상태 **error failred to push some refs to 'origin'**이 뜨면서 병합 불가!
헉 감사합니다!! 수정했습니다

2021-01-06 16:42 UTC, maybeluna commented on _posts/2020-11-06-Fall_intro-Oct.md
> +    후... ㅠ 애증의 git... !
넵!!

2021-01-06 16:43 UTC, maybeluna commented on _posts/2020-11-06-Fall_intro-Oct.md
> +문서 편집기로는 vscode를 사용하여 작업을 한다.
넵!! 😉

2021-01-06 16:43 UTC, maybeluna commented on _posts/2020-11-06-Fall_intro-Oct.md
> +```
이거는 작성할 때는 의미가 있어서 나눈 것 같은데 지금보니까 통일하는게 나을 것 같네요! 감사합니다 🙏

2021-01-06 16:44 UTC, maybeluna commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- ```phthon
수정했습니다!! 꼼꼼한 피드백 감사합니다!

2021-01-06 16:44 UTC, maybeluna commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- ```python
제거하였습니다!!  😊

2021-01-06 16:45 UTC, maybeluna commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- 사용 **불가능**한 코드 : `itertools`
앗 이건 문제에 있는 것을 그대로 가져온건데 보는사람 입장에서는 그게 더 좋을 것 같습니다! 고맙습니다! 수정했습니다!! 꼼꼼하게 봐주어서 감사합니다!!

2021-01-06 16:52 UTC, maybeluna commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- 사용 **불가능**한 코드 : `itertools`
밑에 수빈님이 언급하신 것까지 다시 수정했습니다 :) 나름 꼼꼼하게 확인해고 고쳤는데 틀린부분 있다면 바로 수정하겠습니다! 수빈님꺼는 댓글다는 법을 모르겠어서 일단 여기 남겨요!! 따숩게 다 코멘트 달아주셔서 고맙습니다! 느릿느릿 수정했는데 ㅠ 죄송해요. 😭

2021-01-06 17:22 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- 사용 **불가능**한 코드 : `itertools`
@mabeluna 음.. 이상하게 앞부분만 수정되었다고 나오네요,, 확인해봐 주실 수 있나요??

2021-01-11 02:36 UTC, Enoch-Kim commented on _posts/2020-12-25-Fall_intro-Dec.md
> +- ```phthon
오타 수정이 안됐어요 ㅋㅋㅋㅋ

2021-01-12 03:42 UTC, Enoch-Kim submitted a review, later dismissed
고생하셨습니다 ㅎㅎ LGTM!!

2021-01-12 03:59 UTC, Enoch-Kim submitted a review, later dismissed
컨플릭트 등 몇가지 수정했습니다! LGTM

2021-01-12 10:12 UTC, merged