CV _imgae classification 첫번째 Posting
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #52
Opened 2020-11-06 14:20 UTC by howtolivelikehuman

data/author.yml에 엄현식 추가
_post/2020-11-06-CNN.md 추가

표지 제외하고 이미지는 따로 url 빼서 사용했습니다!

2020-11-07 08:45 UTC, MOBUMIN requested changes
마크다운 형식에 대해서만 코멘트 달았습니다 :) 나머지는 다 좋은 것 같아요!

2020-11-07 08:45 UTC, MOBUMIN commented on _posts/2020-11-06-CNN.md
> +
문장과 문장 사이 줄바꿈은 한 줄을 권장드립니다. ( 더 띄워도 포스트 상에서는 차이가 없습니다. )

2020-11-07 08:45 UTC, MOBUMIN commented on _posts/2020-11-06-CNN.md
> +
문장과 문장 사이 줄바꿈은 한 줄을 권장드립니다. ( 더 띄워도 포스트 상에서는 차이가 없습니다. )

이 밑부분부터는 해당 issue 관련 리뷰는 생략하겠습니다.

2020-11-07 08:45 UTC, MOBUMIN commented on _posts/2020-11-06-CNN.md
> +* `kernel_size ` :  커널 크기
```suggestion
* `kernel_size` :  커널 크기
```
빈 칸이 존재합니다! 지워주세요.

2020-11-07 08:45 UTC, MOBUMIN commented on _posts/2020-11-06-CNN.md
> +- `stride`:  stride 크기
문장의 끝에 빈 칸을 지워주세요!

2020-11-07 08:45 UTC, MOBUMIN commented on _posts/2020-11-06-CNN.md
> +- `return_indices`: 최대 인덱스 반환 여부
문장의 끝에 빈 칸을 지워주세요!

2020-11-07 08:45 UTC, MOBUMIN commented on _posts/2020-11-06-CNN.md
> +https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html
링크는 <> 이걸로 감싸주세요!

\> <링크> 이런식으로 하면 포스트 상에서 왼쪽에 이쁜 초록줄도 생긴답니다 ㅎㅎ

2020-11-07 08:45 UTC, MOBUMIN commented on _data/author.yml
> +  email:
따로 개인 이메일이 없으신가요!?

2020-11-09 06:50 UTC, howtolivelikehuman commented on _data/author.yml
> +  email:
추가했습니다!

2020-11-09 06:51 UTC, howtolivelikehuman commented on _posts/2020-11-06-CNN.md
> +https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html
수정했습니다!

2020-11-09 06:51 UTC, howtolivelikehuman commented on _posts/2020-11-06-CNN.md
> +- `return_indices`: 최대 인덱스 반환 여부
수정했습니다!

2020-11-09 06:51 UTC, howtolivelikehuman commented on _posts/2020-11-06-CNN.md
> +- `stride`:  stride 크기
수정했습니다!

2020-11-09 06:51 UTC, howtolivelikehuman commented on _posts/2020-11-06-CNN.md
> +* `kernel_size ` :  커널 크기
수정했습니다!

2020-11-09 06:51 UTC, howtolivelikehuman reviewed
수정사항 반영해보았습니다!

2020-11-09 07:40 UTC, MOBUMIN submitted a review, later dismissed
LGTM!

2020-11-09 08:00 UTC, MOBUMIN approved these changes
LGTM!

2020-11-09 08:41 UTC, Enoch-Kim approved these changes
LGTM!
(TODO: 여러줄 띄워놓은게 있지만 이건 제가 나중에 추가하겠습니다!)

2020-11-09 08:42 UTC, merged