Web Team 미션 3 포스트 작성
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #57
Opened 2020-12-02 10:16 UTC by r4k0nb4k0n

처음 작성해서 `author.yml`에 제 정보를 추가한 뒤에 미션 3 포스트를 작성했습니다.

2020-12-02 10:38 UTC, MOBUMIN requested changes
정성스러운 포스트 잘 봤습니다! : - ) bb

2020-12-02 10:38 UTC, MOBUMIN commented on _posts/2020-12-02-WEB_Mission3.md
> +image: assets/images/post-WEB-Mission3/01.clone.png
```suggestion
image: assets/images/post-WEB-Mission3/01.intro.png
```
원래껄로하면 이미지가 없어용~!!!

2020-12-02 10:38 UTC, MOBUMIN commented on _posts/2020-12-02-WEB_Mission3.md
> +  ```json
markdownlint에서 코드블록을 사용할땐 위아래로 blank line이 필요하다고 합니다!
블로그 상에서 봤을 때 차이가 없어서 이 부분은 띄워주셔도 되고 놔둬도 될 듯하네요!

2020-12-02 11:42 UTC, r4k0nb4k0n commented on _posts/2020-12-02-WEB_Mission3.md
> +image: assets/images/post-WEB-Mission3/01.clone.png
아이고 제가 수정 안하고 커밋을 했네요 ㅠㅠ 꼼꼼하게 봐주셔서 감사합니다!

2020-12-02 11:43 UTC, r4k0nb4k0n commented on _posts/2020-12-02-WEB_Mission3.md
> +  ```json
일단 그대로 놔둬보도록 하겠습니다 ㅎㅎ 다음에는 꼭 markdownlint 사용해서 정리하도록 할게요!

2020-12-02 11:49 UTC, MOBUMIN approved these changes, later dismissed
LGTM 💯

2020-12-02 11:51 UTC, r4k0nb4k0n commented on _posts/2020-12-02-WEB_Mission3.md
> +  ```json
그냥 맘에 안들어서 markdownlint 깔아서 수정했습니다. 곧 코드 리뷰 제안 사항 커밋하겠습니다!

2020-12-02 11:55 UTC, r4k0nb4k0n reviewed
@MOBUMIN 님 꼼꼼하게 봐주셔서 감사합니다! 덕분에 제 커밋들이 더 완벽해졌어요!

2020-12-03 10:35 UTC, MOBUMIN approved these changes
왕 정성 멋져요,,!
LGTM!

2020-12-05 09:51 UTC, Enoch-Kim approved these changes
리뷰가 늦어져 죄송합니다 ㅠㅠ 깔끔하게 잘 만드셨네요 
LGTM!

2020-12-05 09:51 UTC, merged