dsc cv-fa-team 임호연 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #59
Opened 2020-12-20 11:22 UTC by hoyeon94

혹시 제가 올린 거에 문제 있다면 슬랙 개인챗으로 말씀해주시면 수정하겠습니다!!

2020-12-21 12:29 UTC, Enoch-Kim requested changes
한 가지만 수정되면 될 것 같아요 ㅎㅎ 감사합니다.

2020-12-21 12:29 UTC, Enoch-Kim commented on _posts/2020-12-20-image_data_augmentation.md
> +# image data augmentation
완벽합니다. 한 가지만 말씀드릴게요.. ㅠㅠ 저희가 기본적으로 head1을 사용하고 있어서 # 하나를 쓰는것보다 두개부터 사용하는 것을 권장드려요. 보시면 
![스크린샷 2020-12-21 오후 9 28 15](https://user-images.githubusercontent.com/60127664/102777191-741ab580-43d3-11eb-986d-d0cee8f9d657.png)
이런식으로 제목 중복되고 하니 `jekyll serve` 로 한번 확인해보시거나 그냥 # 두개부터 사용해주실 수 있을까요??
내용이랑 정말 완벽했습니다.

2020-12-22 14:51 UTC, MOBUMIN requested changes
이미지도 깔끔하고 가독성있게 글을 잘 쓰신 것 같아요 ㅠㅠㅠㅠ CV팀 멋있습니다...bbb
간단한 오타랑 양식?만 봤습니다~~

2020-12-22 14:51 UTC, MOBUMIN commented on _posts/2020-12-20-image_data_augmentation.md
> +### 1. data augmentation을 하는 이유
```suggestion
### 1. data augmentation을 하는 이유

```
헤더 양식(?) 에 맞췄습니당!(헤더 밑에 띄어쓰기)
아래 2. 두 가지 data augmentation은 ##인데 1번은 ###인 이유가 따로 있을까용?

2020-12-22 14:51 UTC, MOBUMIN commented on _posts/2020-12-20-image_data_augmentation.md
> +2. Dataset Generator에서 data augementation 기법을 이용하여 학습 데이터 셋에 변형된 데이터를 추가한다.
```suggestion
2. Dataset Generator에서 data augmentation 기법을 이용하여 학습 데이터 셋에 변형된 데이터를 추가한다.
```
data augementation 오타가 났습니다~

2020-12-22 14:51 UTC, MOBUMIN commented on _posts/2020-12-20-image_data_augmentation.md
> +위에서 제시한 것 처럼 프레임워크에서 대부분 data generator를 구현한 함수를 제공하지만, 상황에 따라서는 image data generator 함수를 직접 구현해야 하는 경우도 있습니다. 여러분들도 직접 augementation 코드를 구현해야 할 때, 이런 점을 고려해서 더 좋은 방법으로 구현하셨으면 좋겠습니다.
```suggestion
위에서 제시한 것 처럼 프레임워크에서 대부분 data generator를 구현한 함수를 제공하지만, 상황에 따라서는 image data generator 함수를 직접 구현해야 하는 경우도 있습니다. 여러분들도 직접 augmentation 코드를 구현해야 할 때, 이런 점을 고려해서 더 좋은 방법으로 구현하셨으면 좋겠습니다.
```
여기도 오타가 났습니다!

2020-12-22 15:02 UTC, Enoch-Kim commented on _posts/2020-12-20-image_data_augmentation.md
> +위에서 제시한 것 처럼 프레임워크에서 대부분 data generator를 구현한 함수를 제공하지만, 상황에 따라서는 image data generator 함수를 직접 구현해야 하는 경우도 있습니다. 여러분들도 직접 augementation 코드를 구현해야 할 때, 이런 점을 고려해서 더 좋은 방법으로 구현하셨으면 좋겠습니다.
크.. 꼼꼼한 체크..

2020-12-22 15:32 UTC, hoyeon94 commented on _posts/2020-12-20-image_data_augmentation.md
> +2. Dataset Generator에서 data augementation 기법을 이용하여 학습 데이터 셋에 변형된 데이터를 추가한다.
앗 감사합니다!!

2020-12-22 15:32 UTC, hoyeon94 commented on _posts/2020-12-20-image_data_augmentation.md
> +위에서 제시한 것 처럼 프레임워크에서 대부분 data generator를 구현한 함수를 제공하지만, 상황에 따라서는 image data generator 함수를 직접 구현해야 하는 경우도 있습니다. 여러분들도 직접 augementation 코드를 구현해야 할 때, 이런 점을 고려해서 더 좋은 방법으로 구현하셨으면 좋겠습니다.
감사합니다!!

2020-12-22 15:33 UTC, hoyeon94 commented on _posts/2020-12-20-image_data_augmentation.md
> +### 1. data augmentation을 하는 이유
아 헤더 양식을 다시 급하게 맞추다보니까 실수했습니다! 확인 감사드려요

2020-12-22 15:36 UTC, MOBUMIN submitted a review, later dismissed
LGTM :)

2020-12-22 19:11 UTC, Enoch-Kim approved these changes, later dismissed
LGTM

2020-12-24 12:35 UTC, MOBUMIN approved these changes, later dismissed
LGTM

2020-12-29 17:04 UTC, Enoch-Kim commented
새로운 브랜치의 PR로  대체

2020-12-29 17:04 UTC, closed without merging