모바일 팀 리뷰 포스트 입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #63
Opened 2020-12-22 19:23 UTC by Enoch-Kim

* 포스트 하나 추가

2020-12-29 18:07 UTC, MOBUMIN requested changes
글 잘봤습니다 !!! 글 읽는데 한 해 마무리 되는 기분 들면서 막 ㅠㅠ 벅차네요,, 흑흑 갓갓 유현님,,bb

2020-12-29 18:07 UTC, MOBUMIN commented on _posts/2020-12-22-dsc-miterm-review.md
> +DSC UOS가 9월에 시작된 후 벌써 4달이 흘러가네요.. 시간 빠릅니다. 혼자 공부하는 것이 심심해서 같이 공부할 사람을 찾아 지원하던게 엇그제 같은데.. 벌써 새해가 코앞입니다.
```suggestion
DSC UOS가 9월에 시작된 후 벌써 4달이 흘러가네요.. 시간 빠릅니다. 혼자 공부하는 것이 심심해서 같이 공부할 사람을 찾아 지원하던게 엊그제 같은데.. 벌써 새해가 코앞입니다.
```
간단한 오타네용!!! 진짜 벌써 새해가 코앞입니다 ㅠㅠ 항상 열심히 하는 유현님,, 존경..

2020-12-29 18:07 UTC, MOBUMIN commented on _posts/2020-12-22-dsc-miterm-review.md
> +1. 블로그 글을 멤버분들께 요청하고 이를 관리하면서, 블로그 운영진이 매~~~~~~~우 귀찮음을 무릅쓰고 요청하는 것인지 깨달았습니다.(나중에 회사에서 제때 제때 줘야겠습니다 ㅠ.ㅠ)
제가 이해력이 좀 부족한 탓인지,, 블로그 운영진이 매우 귀찮음을 무릅쓰고 '어떤것을 요청하는지' 모르겠습니다 !!!! ㅠㅠ

2020-12-29 18:07 UTC, MOBUMIN commented on _posts/2020-12-22-dsc-miterm-review.md
> +제 블로그를 만들기 위해 지원했지만, 제 목적 이상으로 얻은게 많은 시간이었습니다. (여러분 블로그 운영진 하세요^^)
ㅎㅎㅎ 근데 정말 DSC 팀블로그 운영진한건 후회 안 되는 것 같아요 ㅎㅎ

2020-12-30 08:05 UTC, Enoch-Kim commented on _posts/2020-12-22-dsc-miterm-review.md
> +DSC UOS가 9월에 시작된 후 벌써 4달이 흘러가네요.. 시간 빠릅니다. 혼자 공부하는 것이 심심해서 같이 공부할 사람을 찾아 지원하던게 엇그제 같은데.. 벌써 새해가 코앞입니다.
왜 뼈맞은 기분이죠.. 이게 살을주고 뼈를 취한다는 건가요?? ㅠ

2020-12-30 08:07 UTC, Enoch-Kim commented on _posts/2020-12-22-dsc-miterm-review.md
> +제 블로그를 만들기 위해 지원했지만, 제 목적 이상으로 얻은게 많은 시간이었습니다. (여러분 블로그 운영진 하세요^^)
음.. 이부분 고칠게 있는건 아닌거 맞죠?

2020-12-31 07:48 UTC, MOBUMIN commented on _posts/2020-12-22-dsc-miterm-review.md
> +제 블로그를 만들기 위해 지원했지만, 제 목적 이상으로 얻은게 많은 시간이었습니다. (여러분 블로그 운영진 하세요^^)
넵 그냥 블로그 댓글 달듯이 달아버렸네유 ㅋㅋㅋㅋ 혼란을 드려 죄송..

2020-12-31 07:49 UTC, MOBUMIN approved these changes
LGTM :>

2020-12-31 11:01 UTC, merged