CV - 이미지 분류팀 12월 Blog Post 입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #64
Opened 2020-12-24 20:20 UTC by GoonLee

문제점이나 수정할 사항 발생시 알려주시면 바로 수정하겠습니다.

2020-12-29 18:10 UTC, MOBUMIN submitted a review, later dismissed
LGTM :)

2020-12-31 01:13 UTC, Enoch-Kim reviewed
제 DM 확인 해주세요..ㅠ

2021-01-01 11:47 UTC, Enoch-Kim requested changes
내용이 알차고 좋네요 ㅎㅎ
문장만 조금 끊어주면 완벽합니다!!

2021-01-01 11:47 UTC, Enoch-Kim commented on _posts/2020-12-24-how-to-use-pretrained-model.md
> +Flask를 통해 구축한 서버의 모델은 사전 학습된 ResNet18 모델을 그대로 사용하고 있어, 강아지 사진을 업로드하면 품종을 파악, 그에 대한 정보를 알려주도록 서비스를 구체화한 우리 프로젝트에 그대로 사용하기에는 한계가 있었다.
문장이 끊어지면 더 좋을 것 같습니다. 제가 내용이 완전히 이해가 안가서 다음과 같이 예시 남깁니다.
```suggestion
Flask를 통해 구축한 서버의 모델은 사전 학습된 ResNet18 모델을 그대로 사용하고 있습니다. 그렇기에 강아지 사진을 업로드하면 품종을 파악하고, 그에 대한 정보를 알려주는 <프로젝트 이름>에 그대로 사용하기에는 한계가 있었다.
```

2021-01-01 11:47 UTC, Enoch-Kim commented on _posts/2020-12-24-how-to-use-pretrained-model.md
> +PyTorch는 이미지 분류, 객체 탐지, 영상 분류 등 다양한 목적에 맞는 사전 학습된 모델을 제공하고, 우리 프로젝트의 주제에 부합하는 이미지 분류용 사전 학습된 모델 리스트는 아래와 같다.
문장 끊어주면 더 이쁠 것 같습니다.
```suggestion
PyTorch는 이미지 분류, 객체 탐지, 영상 분류 등 다양한 목적에 맞는 사전 학습된 모델을 제공한다. 우리 프로젝트의 주제에 부합하는 이미지 분류용 사전 학습된 모델 리스트는 아래와 같다.
```

2021-01-01 11:47 UTC, Enoch-Kim commented on _posts/2020-12-24-how-to-use-pretrained-model.md
> +이때, 매개 변수로 `pretrained=True`를 사용하였는데, 이를 명시하지 않으면 구조는 동일하지만 weight가 무작위로 초기화된 모델을 반환하기 때문에 사전 학습된 모델을 사용하기 위해서는 반드시 명시해야 한다.
동일합니다.
```suggestion
이때, 매개 변수로 `pretrained=True`를 사용하였는데, 이를 명시하지 않으면 구조는 동일하지만 weight가 무작위로 초기화된 모델을 반환하게 된다. 그렇기 때문에 사전 학습된 모델을 사용하기 위해서는 반드시 `pretrained`를 `True`로 명시해야 한다.
```

2021-01-01 11:47 UTC, Enoch-Kim commented on _posts/2020-12-24-how-to-use-pretrained-model.md
> +위 과정을 통해 불러온 모델을 바로 사용할 수 있으면 좋겠지만 실제 프로젝트에 사용하기 위해서는 모델의 구조를 일부 수정한 뒤 weight를 사용할 dataset에 맞춰 다시 학습해야하는 경우가 대부분이다.
, 하나만 추가하면 어떨까요??
```suggestion
위 과정을 통해 불러온 모델을 바로 사용할 수 있으면 좋겠지만, 실제 프로젝트에 사용하기 위해서는 모델의 구조를 일부 수정한 뒤 weight를 사용할 dataset에 맞춰 다시 학습해야하는 경우가 대부분이다.
```

2021-01-01 11:47 UTC, Enoch-Kim commented on _posts/2020-12-24-how-to-use-pretrained-model.md
> +처음 전이 학습에 대해 조사를 하면서 이 3가지 방법 중 어떤 방법을 채택해야 할지 의문이였는데 다행히 데이터셋의 특징에 따라 일반적으로 어떤 방법을 채택하는 것이 유리한지 나타낸 아래 도표가 존재하여 참고하였다.
동일합니다.
```suggestion
처음 전이 학습에 대해 조사를 하면서 이 3가지 방법 중 어떤 방법을 채택해야 할지 의문이었다. 다행히 데이터셋의 특징에 따라 일반적으로 어떤 방법을 채택하는 것이 유리한지 나타낸 아래 도표가 존재하여 참고하였다.

||

처음 전이 학습에 대해 조사를 하면서 이 3가지 방법 중 어떤 방법을 채택해야 할지 고민하던 중, 데이터셋의 특징에 따라 일반적으로 어떤 방법을 채택하는 것이 유리한지 나타낸 아래 도표가 존재하여 참고하였다.
```

2021-01-01 11:47 UTC, Enoch-Kim commented on _posts/2020-12-24-how-to-use-pretrained-model.md
> +우리 프로젝트의 경우 사전 학습된 모델이 분류하는 클래스에 강아지가 있었고, 데이터셋 자체도 이미지 2만장 정도로 크지 않다고 판단하여 feature-based learning을 하기로 결정했고, 학습을 위한 모델 준비 최종 소스코드는 아래와 같다.
동일합니다.
```suggestion
우리 프로젝트의 경우 사전 학습된 모델이 분류하는 클래스에 강아지가 있었고, 데이터셋 자체도 이미지 2만장 정도로 크지 않다고 판단하여 feature-based learning을 하기로 결정했다. 학습을 위한 모델 준비 최종 소스코드는 아래와 같다.
```

2021-01-17 02:43 UTC, GoonLee commented
너무 늦어서 죄송합니다 ㅜㅠ
피드백 반영했고, 글의 문체를 경어체로 변경했습니다.

2021-01-17 09:43 UTC, Enoch-Kim approved these changes, later dismissed
LGTM!!

2021-01-18 09:25 UTC, Enoch-Kim approved these changes
LGTM!

2021-01-24 15:38 UTC, MOBUMIN approved these changes
LGTM!

2021-01-24 15:38 UTC, merged