dsc cv-fa-team 이상헌 포스팅입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #66
Opened 2020-12-28 09:18 UTC by lsh110600

CV-fa-team 두번째 포스팅

2020-12-29 17:20 UTC, Enoch-Kim requested changes
VSCode에서 markdownlint 설치한 후 워닝 뜨는 것 없애주실 수 있을까요?? 내용은 완벽합니다!!!
문법 워닝만 고쳐지면 되겠어요

2021-01-17 09:14 UTC, Enoch-Kim requested changes
와 레이아웃이 훨씬 이뻐졌습니다!
오타만 몇개 수정하고 이미지가 글에 붙은 것만 떼어내면 될 것 같아요!!

2021-01-17 09:14 UTC, Enoch-Kim commented on _posts/2020-12-24-Image-Translation-paper-review(vol1).md
> +    ![Capture](../assets/images/post-image-translation/paper2-1.png)
image file 명을 잘못 입력하셨습니다.
```suggestion
    ![Capture](../assets/images/post-image-translation/paper2_1.png)
```

2021-01-17 09:14 UTC, Enoch-Kim commented on _posts/2020-12-24-Image-Translation-paper-review(vol1).md
> +![Capture](../assets/images/post-image-translation/paper9.png)
한줄 띄어야 합니다.
```suggestion
- 입력 사진은 Generator에도 들어가고 VGG 네트워크에도 들어갑니다. VGG 네트워크에서는 High level feature를 추출해냅니다. Structure 특징을 뽑아내기 위한 loss는 아래와 같습니다.

![Capture](../assets/images/post-image-translation/paper9.png)
```

2021-01-17 09:14 UTC, Enoch-Kim commented on _posts/2020-12-24-Image-Translation-paper-review(vol1).md
> +    ![Capture](../assets/images/post-image-translation/paper2-2.png)
image file 명을 잘못 입력하셨습니다.
```suggestion
    ![Capture](../assets/images/post-image-translation/paper2_2.png)
```

2021-01-17 09:14 UTC, Enoch-Kim commented on _posts/2020-12-24-Image-Translation-paper-review(vol1).md
> +- F_rcs라는 random color shift algorithm을 제안했는데, 식은 아래와 같습니다.
* image file 명을 잘못 입력하셨습니다.
* 한칸씩 띄어주어야합니다.
```suggestion
- 즉 real world photo와 cartoon은 color와 luminance 정보로 너무 쉽게 판별이 가능하므로, 합쳐서 흑백 이미지로 만듬 + random하게 RGB를 섞는 과정을 진행합니다.

     ![Capture](../assets/images/post-image-translation/paper2_3.png)
     
- F_rcs라는 random color shift algorithm을 제안했는데, 식은 아래와 같습니다.
```

2021-01-17 09:50 UTC, Enoch-Kim requested changes
논문만 각주로 빼면 Perfect!!

2021-01-17 09:50 UTC, Enoch-Kim commented on _posts/2020-12-24-Image-Translation-paper-review(vol1).md
> +에 대해서 리뷰합니다.
논문을 각주로 넣는게 좋을 것 같아요.
```suggestion
2020 DSC-Vision team에서 Face2Cartoon 서비스를 만들 때 참고했던 [Image Translation 관련 논문](https://github.com/SystemErrorWang/White-box-Cartoonization/)입니다.  

> Wang, Xinrui, and Jinze Yu. "Learning to Cartoonize Using White-Box Cartoon Representations." Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2020.
```

2021-01-17 14:58 UTC, Enoch-Kim approved these changes
LGTM

2021-01-18 06:48 UTC, MOBUMIN approved these changes
LGTM !

2021-01-18 09:22 UTC, merged