CV - RPS팀 첫 포스트입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #67
Opened 2020-12-28 09:28 UTC by YubeenSon

가위바위보팀 첫 포스트 생성, author.yml 파일 수정하였습니다.

2020-12-29 17:24 UTC, Enoch-Kim requested changes
VSCode 의 markdownlint 플러그인 설치하셔서 워닝만 수정해주시면 될 것 같습니다!!

2020-12-30 02:28 UTC, YubeenSon commented
각주의 경우 markdown에서 지원하고있지 않아 html코드로 작성하였습니다. 그외의 에러는 모두 수정하였습니다!

2020-12-31 01:00 UTC, Enoch-Kim approved these changes
LGTM

2020-12-31 07:52 UTC, MOBUMIN approved these changes
LGTM :>

2020-12-31 07:52 UTC, merged