Origin/web 4 chapter1
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #78
Opened 2020-12-31 11:53 UTC by min6choi

2021-01-01 11:38 UTC, MOBUMIN requested changes
웹팀 고생하셨습니다~! 👍

2021-01-01 11:38 UTC, MOBUMIN commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +저희가 공부한 웹사이트 강의는 다음과 같습니다. (그러나 리엑트를 처음 접해보는 경우 이 강의를 바로 듣는 것을 추천하지 않습니다.)
```suggestion
저희가 공부한 웹사이트 강의는 다음과 같습니다. (그러나 리액트를 처음 접해보는 경우 이 강의를 바로 듣는 것을 추천하지 않습니다.)
```
react를 계속 리액트라고 쓰셨기 때문에 요기도 리액트로 바꾸는게 좋을듯 합니다~!

2021-01-03 14:05 UTC, MOBUMIN approved these changes, later dismissed
LGTM :>

2021-01-11 02:59 UTC, Enoch-Kim requested changes
고생하셨습니다!! 몇가지 수정사항 리뷰했으니 수정하시면 바로 PR 머지하겠습니다~

2021-01-11 02:59 UTC, Enoch-Kim commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +```js
들여쓰기 빠진 것 같습니다. 이부분 때문에 뒤의 내용에도 들여쓰기가 적용이 안되는 것 같아요 ㅠ
```suggestion
```js
  ```js
```

2021-01-11 02:59 UTC, Enoch-Kim commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +
이전까지는 설명이 있었으나 이 부분의 설명이 부족하다고 느껴집니다. 혹시 내용을 좀 더 추가해주실 수 있을까요??

2021-01-11 02:59 UTC, Enoch-Kim commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +       email: 'public.velopert@gmail.com'
벨로퍼트로 공부하셨군요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-01-11 02:59 UTC, Enoch-Kim commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +이외에 여러가지를 리액트의 기본적인 것에 대한 대부분을 배웠습니다. 리액트의 경우 JavaScript의 기초를 기반으로 진행되기 때문에 JavaScript의 공부가 선행되어야 하는데요. 리액트에 대해 관심이 있는 분들을 위해 제가 이 강의를 들으면서 함께 공부했던 다른 강의와 사이트들도 아래 첨부했습니다.
https://poiemaweb.com/ 이 사이트도 추천드립니다!

2021-01-14 03:25 UTC, min6choi commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +       email: 'public.velopert@gmail.com'
벨로퍼트에 대해 어떻게 생각하시나요 ㅠㅠㅠ

2021-01-14 03:26 UTC, min6choi commented
수정 제안 모두 반영했습니다. 확인부탁드려요!

2021-01-15 00:51 UTC, Enoch-Kim commented on _posts/2020-12-31-WEB_Mission4_Chapter1.md
> +       email: 'public.velopert@gmail.com'
쉽게 설명하여 좋습니다. 하지만 React 같이 공식문서가 좋은 경우는 공식문서를 보고 공부하는 것을 추천드려요 ㅎㅎ

2021-01-15 01:16 UTC, Enoch-Kim approved these changes
LGTM!!

2021-01-15 03:49 UTC, merged