Mobile - 모바일팀 12월 BlogPost입니다.
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #82
Opened 2021-01-13 12:57 UTC by LittleSamakFox

Mobile팀 12월 2번째 Post.

2021-01-14 14:11 UTC, Enoch-Kim requested changes
이 수정사항 말고도 vscode의 markdownlint 플러그인을 설치해 워닝을 제거해주세요!

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +디자인패턴은 아키텍처 설계에서 **반복해서 나오는 문제**들을 **패턴화**하여  또 발생하였을 때 **재사용**과 **재사용가능성**을 용이하게 할 수 있다.
문장의 의미가 모호합니다.

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +3. 비즈니스 로직만 이해해도 소프트웨어 구조 파악이 가능해, 용이한 유지보수
탭으로 넣어주세요

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +2. 객체 지향 위주 설계 및 구현
탭으로 넣어주세요

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +![img](../assets/images/post-mobile_repository/01_pattern.PNG)
메인에서 이미지가 이미 한번 나왔기 때문에 더 필요 없을 것 같아요!

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +#### 대표적인 디자인패턴 3형재! MVC, MVP, MVVM
오타 났습니다. (3형재 -> 3형제)
```suggestion
#### 대표적인 디자인패턴 3형제! MVC, MVP, MVVM

```

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +Model에 통해 가져온 데이터를 View에 전달
들여쓰기가 빠진 것 같습니다

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +사용자에게 보여주게 된다.
여기도 들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +3. 유지보수가 용이하다.
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +2. Model과 View 사이의 의존성이 높아, 클래스들이 많아 질수록 구조가 복잡해져 설계 시간이 오래걸린다.
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +Presenter는 View에서 요청한 정보로 Model을 가공해 View에게 전달해주는 역할
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +MVC와 동일한 모델을 가지나, 유저 입력을 View에서 받는다는 차이가 있고, View에서 받은 데이터는 Presenter를 통해 전달되어 Model과 상호작용한다. 이때, View와 Presenter 사이의 관계는 1 대 1 관계이다.
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +1. View와 Model 관계를 분리시켜 Presenter를 통해 상호작용 시켜 Model과 View 사이의 의존성을 해결하였다.
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +1. 역으로 View와 Presenter 사이의 의존성이 높아져 복잡해질수록 의존성이 강해지는 단점이 생기게 되었다.
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +View를 위한 Model
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +MVC와 MVP와 마찬가지로 Model과 View는 동일하다. 그대신 Controller나 Presenter대신에 ViewModel이 존재한다. ViewModel은 이름 그래도 View를 나타내주기위해 사용되는 Model인데, ViewModel은 View만을 위한 데이터를 가지고 있어 View와 Model사이의 관계를 분리시킨다. 이때, View와 Vie
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +3. 각 부분이 독립적이기에 모듈화가 가능하고 유닛테스트가 용이하다.
들여쓰기

2021-01-14 14:11 UTC, Enoch-Kim commented on _posts/2020-11-09-Repository.md
> +1. ViewModel의 설계가 어렵다.
들여쓰기

2021-01-15 09:55 UTC, MOBUMIN requested changes
거의 오타만 봤습니다!
4학년 전공중에 모바일 디자인패턴인가? 그게 듣고싶게 만들어지는 글이네요 ㅎㅎ

2021-01-15 09:55 UTC, MOBUMIN commented on _posts/2020-11-09-Repository.md
> +디자인패턴에서 *Repository* 가 쓰여야 하는가? 라는 논점에 대해 논하기에 앞서서 "**디자인 패턴**이 무엇인가? " 와 "왜 소프트웨어 개발을 할 때 디자인패턴을 사용해야하는가?"에 대해서 알아볼 필요가 있다.
```suggestion
디자인패턴에서 *Repository* 가 쓰여야 하는가? 라는 논점에 대해 논하기에 앞서서 "**디자인 패턴**이 무엇인가?" 와 "왜 소프트웨어 개발을 할 때 디자인패턴을 사용해야하는가?"에 대해서 알아볼 필요가 있다.
```
뒤의 큰 따옴표에는 마칠때 띄어쓰기가 없는데 앞에는 있어서 없는게 나을 듯 하네요!

2021-01-15 09:55 UTC, MOBUMIN commented on _posts/2020-11-09-Repository.md
> +![img](../assets/images/post-mobile_repository/01_pattern.PNG)
이미지 중복이 문제라면 메인 이미지를 다른 것을 사용하고 이 이미지는 요 위치에 있는게 좋은 것 같아요!

2021-01-15 09:55 UTC, MOBUMIN commented on _posts/2020-11-09-Repository.md
> +Model에 통해 가져온 데이터를 View에 전달
```suggestion
Model을 통해 가져온 데이터를 View에 전달
```

2021-01-15 09:55 UTC, MOBUMIN commented on _posts/2020-11-09-Repository.md
> +MVC와 MVP와 마찬가지로 Model과 View는 동일하다. 그대신 Controller나 Presenter대신에 ViewModel이 존재한다. ViewModel은 이름 그래도 View를 나타내주기위해 사용되는 Model인데, ViewModel은 View만을 위한 데이터를 가지고 있어 View와 Model사이의 관계를 분리시킨다. 이때, View와 Vie
```suggestion
MVC와 MVP와 마찬가지로 Model과 View는 동일하다. 그대신 Controller나 Presenter대신에 ViewModel이 존재한다. ViewModel은 이름 그대로 View를 나타내주기위해 사용되는 Model인데, ViewModel은 View만을 위한 데이터를 가지고 있어 View와 Model사이의 관계를 분리시킨다. 이때, View와 ViewModel 사이의 관계는 1 대 多 관계이다.

```

2021-01-15 09:55 UTC, MOBUMIN commented on _posts/2020-11-09-Repository.md
> +"3가지 대표적인 디자인패턴중에 어떤 것이 가장 좋나요? ""라고 물어본 답에는 답을 하기 어려운데, 그 이유는 각 패턴마다 서로 각각의 장단점이 존재하기 때문이다.
```suggestion
"3가지 대표적인 디자인패턴중에 어떤 것이 가장 좋나요?"라고 물어본 답에는 답을 하기 어려운데, 그 이유는 각 패턴마다 서로 각각의 장단점이 존재하기 때문이다.

```

2021-01-15 09:55 UTC, MOBUMIN commented on _posts/2020-11-09-Repository.md
> +
```suggestion
```

2021-01-25 14:16 UTC, closed without merging