[mobile] "React Native에 대해서" 포스트 작성
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #89
Opened 2021-01-27 06:02 UTC by koreanhole

2021-01-28 08:20 UTC, Enoch-Kim requested changes
하.. 너무 알차잖아요.. 리뷰하기 힘드네요..
몇가지 수정사항만 고쳐주시면 더 깔끔해질 것 같슴당!

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +
혹시 과거에서 오셨나요?? ㅋㅋㅋㅋㅋㅋ 지금은 2021년 입니다 순형님 ^^ (12월 포스트이니 12월 27일로 하면 안될까요?)

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +
문단을 나눠주거나 ' - ' 를 통해서 내용을 짤라주면 더 가독성 있을 것 같아요!
그리고 그림 앞뒤로 줄 띄워주는 것이 국룰입니당!
```suggestion

React Native는 React를 사용해서 iOS와 Android앱을 개발할 수 있는 프레임워크이다. JavaScript를 사용해서 앱 개발을 할 수 있다는것이 큰 이점이다. 기존에 React를 사용해서 웹 개발을 했던 분들이라면 더욱 쉽게 네이티브 앱 개발을 시작할 수 있다.

React Native는 facebook이 주도하는 오픈소스 프레임워크이다.
다음과 같은 앱들이 React Native로 작성되었다고 한다.

![Capture](../assets/images/post-about-react-native/react-native-apps.png)

React Native를 활용해서 모바일 앱 개발 뿐만 아니라 [Windows](https://github.com/microsoft/react-native-windows#readme), [macOS](https://github.com/microsoft/react-native-macos#readme) 그리고 [web](https://github.com/necolas/react-native-web#readme) 같은 다양한 플랫폼의 앱도 개발할 수 있다.

```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +
이미지 줄 띄워주기, 문단 나누기
```suggestion
![Capture](../assets/images/post-about-react-native/cross-platfrom-app-stat.png)

Shanhong Liu가 2020년 7월에 발표한 전세계 개발자가 사용하는 크로스 플랫폼 모바일 프레임워크 현황이다.  
차트를 보면 1위가 React Native이고, 그 다음으로 Flutter와 Cordova가 있다.

2019년과 2020년을 비교해보았을때 React Native의 점유율은 유지된 반면 Flutter의 점유율은 큰 상승이 있다.  
점유율의 큰 상승이 있었던 Flutter에 대해 잠시 간단하게 알아보겠다.

```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +Flutter는 구글이 만든 크로스 플랫폼 앱 개발 프레임워크이다. 여타 크로스 플랫폼 프레임워크와 마찬가지로 단 하나의 코드베이스를 통해 iOS, Android, Web 그리고 데스크톱의 앱을 개발할 수 있다. Flutter는 Dart라는 언어를 통해 개발할 수 있다. Dart도 Google이 만든 프로그래밍 언어이고 구글이 server side와 fr
* 문단 나눠주기
* 이고 -> 또한 인데,
```suggestion
Flutter는 구글이 만든 크로스 플랫폼 앱 개발 프레임워크이다. 여타 크로스 플랫폼 프레임워크와 마찬가지로 단 하나의 코드베이스를 통해 iOS, Android, Web 그리고 데스크톱의 앱을 개발할 수 있다.

Flutter는 Dart라는 언어를 통해 개발할 수 있다. Dart 또한 Google이 만든 프로그래밍 언어인데, 구글이 server side와 front-end 코드를 작성하는데 JavaScript보다 더 나은 언어를 원했기에 만들어졌다. Dart는 배우기 쉽고 친숙한 언어이고 Dart만으로 UX를 쉽게 작성할 수 있게 한다. UX를 작성하는데 markup language는 필요없다.
```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +성능의 차이가 나는 근본적인 이유로 React Native는 Native bridge를 통해 JavaScript코드가 Native side와 통신을 하기 때문에 bridge에서의 병목현상이 발생하는 반면 Flutter는 bridge를 사용하지 않고 실제 native코드로 컴파일되기 때문에 앞선 병목현상이 발생하지 않기 때문이다.
* 이미지 줄 띄워주기
* 문단 나눠주기
* Native bridge 추후에 설명 나온다 언급하면 더 좋을 것 같습니다.
```suggestion
![Capture](../assets/images/post-about-react-native/react-native-flutter-benchmark.jpeg)

React Native 앱, Flutter 앱 그리고 Native 앱들의 [벤치마크](https://medium.com/swlh/flutter-vs-react-native-vs-native-deep-performance-comparison-990b90c11433)를 보면 위와 같다. 대부분의 경우 Flutter가 React Native보다 빠르며 특히 CPU 집중 작업의 경우는 Flutter의 성능이 월등하다. 다른 [벤치마크](https://medium.com/swlh/flutter-vs-native-vs-react-native-examining-performance-31338f081980)에서도 마찬가지이다.

성능의 차이가 나는 근본적인 이유로 React Native는 Native bridge를 통해 JavaScript코드가 Native side와 통신을 하기 때문에 bridge에서의 병목현상이 발생하는 반면 Flutter는 bridge를 사용하지 않고 실제 native코드로 컴파일되기 때문에 앞선 병목현상이 발생하지 않기 때문이다.
```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +결국 Flutter에 비해 React Native가 갖고 있는 React와 JavaScript의 커뮤니티로 인해 React Native를 선택했다.
* 100% 뒤의 띄어쓰기
* 불필요한 접속사 제거
* 문단나눠주기
* 잇점 -> 이점
* 프레임워크간 -> 프레임워크 간
* 또한 중복 -> 물론 (?)
```suggestion
크로스 플랫폼 앱 개발 프레임워크를 선택하는데에 있어서 100% 정답은 없다. 결국 어떤 도구를 선택하는것은 전적으로 여러분의 생각이며 현재 상황에 맞는 가장 적합한 도구를 선택해야 한다. 필자가 처음 프레임워크를 선택하며 고민하는 과정의 생각을 쓰면 다음과 같다.

Flutter가 React Native에 비해 성능상의 이점을 갖는 것은 큰 이견이 없을것이다. 하지만 필자가 개발했던 앱과 같이 복잡한 비즈니스 로직이 들어가지 않는 소규모의 앱의 경우는 많은 CPU연산을 수행하지 않기 때문에 두 프레임워크 간의 성능 차이가 크지 않을 것이라고 예상했다.

또한, React Native는 이미 웹개발 영역에서의 큰 형님인 React를 사용하기 때문에 다양한 자료들이 이미 존재한다. Flutter의 [공식문서](https://flutter.dev/docs)를 보았을때 다양하고 친절한 문서들이 있지만 이미 형성되어있는 React 개발 커뮤니티는 이를 넘는 큰 장점이다. 물론 JavaScript의 여러가지 훌륭한 라이브러리도 사용할수 있다. 이외의 차이점은 프레임워크를 선택하는데 큰 문제가 되지 않는다고 생각했다.

결국 Flutter에 비해 React Native가 갖고 있는 React와 JavaScript의 커뮤니티로 인해 React Native를 선택했다.
```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +### React Native의 4가지 Thread
LGTM

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +3. React가 렌더링을 시작하면서 조정자(Reconciler)는 **diffing**을 시작하며 새로운 virtual DOM(layout)을 생성하며 변경점들을 다른 thread(Shadow Thread)로 보낸다.
문장 다듬기
```suggestion
3. React가 렌더링을 시작하면서 조정자(Reconciler)는 **diffing**을 시작한다. 새로운 virtual DOM(layout)을 생성하고 변경점들을 다른 thread(Shadow Thread)로 전달한다.
```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +> 컴포넌트 내에 스테이트가 변경된 경우 React는 해당 컴포넌트를 dirty하다고 표시하고 batch에 추가한다. 그리고 virtual Dom element와 실제 Dom element를 비교 순회하면서 dirty 체크가 되어있는 엘리먼트를 처리한다. 처리하는 과정에서 속성값만 변한 경우에는 속성값만 업데이트하고 해당 엘리먼트의 태그 혹은 컴포넌트가
* 문단 끊어주기(?) -> 선호하는 대로 하시면 됩니다.
* 맞춤법 (이 -> 을)
```suggestion
> 컴포넌트 내에 스테이트가 변경된 경우 React는 해당 컴포넌트를 dirty하다고 표시하고 batch에 추가한다. 그리고 virtual Dom element와 실제 Dom element를 비교 순회하면서 dirty 체크가 되어있는 엘리먼트를 처리한다.
>
> 처리하는 과정에서 속성값만 변한 경우에는 속성값만 업데이트하고 해당 엘리먼트의 태그 혹은 컴포넌트가 변경된 경우라면 해당 노드를 포함한 하위 모든 노드를 제거한 후 새로운 virtual dom으로 대체한다. 이러한 일련의 과정을 모두 마무리 한 후에 실제 Dom에 결과를 업데이트 한다.
```

2021-01-28 08:20 UTC, Enoch-Kim commented on _posts/2020-01-27-about-react-native.md
> +
사진 한장만.. 가능할까요..ㅠㅠ 너무 전문적인 부분이라 이해하기 힘들 것 같습니다.

2021-01-29 05:37 UTC, koreanhole commented on _posts/2020-01-27-about-react-native.md
> +
내용을 한 눈에 보여주는 사진을 못찾겠어서 유튜브로 대체했습니다

2021-01-29 08:42 UTC, Enoch-Kim approved these changes
LGTM!!

2021-01-31 10:45 UTC, MOBUMIN approved these changes
LGTM !!!!!! :)

2021-01-31 10:45 UTC, merged