2021.02.01 MV 01월 blog post
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #91
Opened 2021-02-01 15:52 UTC by howtolivelikehuman

mv (chatbot) 팀 01월 블로그포스트입니다!

markdownlint로 검사하긴 했는데, Latex 문법 부분에서 하나 경고가 뜨더라구요!

$$을 사용해서 Latex로 수식을 표현하긴 했는데, 아직 블로그에서는 불가능한지요 !?!?

혹시 수정해야 된다면 말씀해주세요!

항상 고생하십니다 : )

2021-02-26 13:17 UTC, MOBUMIN requested changes
네넵 수식 따로 처리해주셔야 할 것 같아요 :> 수식 제외하곤 LGTM 👍

2021-03-01 16:19 UTC, howtolivelikehuman commented
수정했습니다!

2021-03-22 04:35 UTC, MOBUMIN approved these changes
LGTM !

2021-04-27 13:27 UTC, Enoch-Kim approved these changes
LGTM!!!

2021-04-27 13:27 UTC, merged