Cv/hoyeon94
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #93
Opened 2021-02-23 14:34 UTC by hoyeon94

cv paper team 포스팅입니다! 감사합니다!

2021-02-26 13:28 UTC, MOBUMIN commented on _posts/2021-02-23-cv_fall_srgan.md
> +authors: [hoyeon94]
저희 author 여러명 지원합니다 :)
`authors: [hoyeon94, MOBUMIN]` 이런식으로 작성하시면 돼요!
제홍님의 author 정보가 없으셔서 author 파일에 등록하고 사용하셔야해요!

2021-02-26 13:28 UTC, MOBUMIN commented on _posts/2021-02-23-cv_fall_srgan.md
> +```
코드 블락인게 가독성이 좀 더 좋아보이긴 하지만, 얘네는 코드가 아니니까 코드 블락에서 빼주는 게 좋지 않을까요,,!?

2021-05-10 06:48 UTC, hoyeon94 commented on _posts/2021-02-23-cv_fall_srgan.md
> +authors: [hoyeon94]
아앗 넵 괜찮을 것 같아요! 확인해주셔서 감사합니다.

2021-05-10 06:51 UTC, hoyeon94 commented on _posts/2021-02-23-cv_fall_srgan.md
> +```
수정했습니다! 감사합니다!

2021-05-11 09:42 UTC, LeeMir requested changes
몇 개는 comment 달긴 했는데 VS Code에서 markdownlint 플러그인 설치하셔서 워닝 모두 제거 부탁드리겠습니다!
Trailing-spaces 같은 워닝이 자잘하게 총 12개정도 뜨네요..!

2021-05-11 09:42 UTC, LeeMir commented on _posts/2021-02-23-cv_fall_srgan.md
> +
```suggestion
```

2021-05-11 09:42 UTC, LeeMir commented on _posts/2021-02-23-cv_fall_srgan.md
> +## **Method**
heading이랑 bold를 같이 써도 변하는 게 없어서 bold는 빼셔도 될 것 같아요!
```suggestion
## Method
```

2021-05-11 09:42 UTC, LeeMir commented on _posts/2021-02-23-cv_fall_srgan.md
> +
```suggestion
```

2021-05-19 09:07 UTC, hoyeon94 commented on _posts/2021-02-23-cv_fall_srgan.md
> +
linter 적용했습니다! 확인해주셔서 감사해요!

2021-05-19 09:07 UTC, hoyeon94 commented on _posts/2021-02-23-cv_fall_srgan.md
> +## **Method**
수정했습니다!

2021-05-19 09:07 UTC, hoyeon94 commented on _posts/2021-02-23-cv_fall_srgan.md
> +
linter 적용했습니다!

2021-05-21 15:54 UTC, LeeMir approved these changes
확인했습니다!! LGTM 👍 👍 👍

2021-05-24 13:26 UTC, MOBUMIN approved these changes
LGTM :)

2021-05-24 13:26 UTC, merged