늦어서 죄송합니다....
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #94
Opened 2021-02-24 08:38 UTC by zeze1004

2021-02-28 14:42 UTC, MOBUMIN requested changes
양이 엄청 많네요. 고생하셨겠어요 ㅠㅠ!!

2021-02-28 14:42 UTC, MOBUMIN commented on _posts/2020-12-25-WEB_Mission4.md
> +        'node-sass' 라이브러리를 통해 Sass가 CSS로 변환되어 웹에서 컴파일 됩니다.
여백이 들어가서 그런지 해당 문장부터 2. CSS Module까지 코드박스가 적용됩니다. 수정 부탁드립니다!

2021-02-28 14:42 UTC, MOBUMIN commented on _posts/2020-12-25-WEB_Mission4.md
> +    ![blue_circle.png](../assets/images/post-WEB-Mission4/blue_circle.png)
```suggestion
    ![blue-circle.png](../assets/images/post-WEB-Mission4/blue_circle.png)
```
파일 명이 달라서 이미지를 불러오지 못합니다!

2021-02-28 14:42 UTC, MOBUMIN commented on _posts/2020-12-25-WEB_Mission4.md
> +![demo](https://www.youtube.com/watch?v=pH76lDisyUU&feature=youtu.be)
jekyll serve로 봤을 땐 깨져서 안 보입니다 ㅠㅠ,

2021-03-05 08:16 UTC, zeze1004 commented on _posts/2020-12-25-WEB_Mission4.md
> +        'node-sass' 라이브러리를 통해 Sass가 CSS로 변환되어 웹에서 컴파일 됩니다.
헉 지금 봤습니다. 수정하겠습니다.

2021-03-08 23:21 UTC, zeze1004 commented on _posts/2020-12-25-WEB_Mission4.md
> +![demo](https://www.youtube.com/watch?v=pH76lDisyUU&feature=youtu.be)
계속 깨져서 링크만 올렸습니다ㅠㅠ!

2021-03-08 23:22 UTC, zeze1004 commented on _posts/2020-12-25-WEB_Mission4.md
> +    ![blue_circle.png](../assets/images/post-WEB-Mission4/blue_circle.png)
수정했습니다!

2021-03-09 00:53 UTC, zeze1004 commented
헉헉 이 놈의 게으름...! 전부 수정하는데 일주일이 걸렸네요 흑흑
썸네일까지 추가했습니다!

2021-03-22 04:32 UTC, MOBUMIN requested changes
음 수정이 안 된걸로 나오는데 다시 확인해주실 수 있나요 ?

2021-05-12 13:49 UTC, zeze1004 commented
헐! 다른 브런치에서 수정했었네요..!

2021-05-12 13:50 UTC, closed without merging