WEB/mission5_websocket
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #95
Opened 2021-02-24 11:12 UTC by rxdcxdrnine

WEB 팀의 mission5_websocket post 를 작성하였습니다.

2021-04-29 15:22 UTC, MOBUMIN requested changes
창구님 authors에 등록이 안 되어 있으신데, 팀블로그 about page 등록 google form을 신청 안 하신 이유가 있으실까요?

2021-04-29 15:22 UTC, MOBUMIN commented on _posts/2021-02-24-WEB_Mission5_websocket.md
> +author: [rxdcxdrnine]
```suggestion
authors: [rxdcxdrnine]

```

2021-05-01 12:31 UTC, rxdcxdrnine commented on _posts/2021-02-24-WEB_Mission5_websocket.md
> +author: [rxdcxdrnine]
죄송합니다 ㅠㅠ 이제야 봤네요..

google form 을 작성해야 하는지 몰라 post 만 올렸던 것 같습니다!
혹시 링크를 알 수 있을까요..?

2021-05-02 06:11 UTC, MOBUMIN commented on _posts/2021-02-24-WEB_Mission5_websocket.md
> +author: [rxdcxdrnine]
ㅎㅎㅎ링크를 닫아놔서... 깃 닉네임, email, 개인 web 주소를 swit DM으로 보내주시겠어용?

2021-05-03 00:53 UTC, MOBUMIN approved these changes
LGTM :3


오노 request change 안고쳐놓으셨네요! 고쳐주세요

2021-05-05 14:30 UTC, MOBUMIN requested changes
authors로 고쳐주세요!

2021-05-05 17:10 UTC, rxdcxdrnine commented
미숙한 PR 사용법으로 고쳐놓지 않았네요 ㅠㅠ
수정했습니다!

2021-05-07 10:12 UTC, MOBUMIN approved these changes
LGTM :)

2021-05-11 15:23 UTC, min6choi approved these changes
LGTM !

2021-05-12 01:46 UTC, merged