회원가입, 로그인 구현 코드 리뷰
DSC-University-of-Seoul/dsc-university-of-seoul.github.io pull request #96
Opened 2021-02-24 13:00 UTC by zeze1004

2021-04-27 13:21 UTC, Enoch-Kim commented
markdownlint 플러그인 설치하셔서 워닝 제거해주시면 좋을 것 같아요.

2021-05-12 13:46 UTC, zeze1004 commented
늦어서 죄송합니다 확인 부탁드립니다!

2021-05-16 11:56 UTC, hyehyeonmoon reviewed
mongodb 또는 mongoDB 중 하나로 통일한다면 좋을 것 같아요!

2021-05-16 11:56 UTC, hyehyeonmoon commented on _posts/2021-02-24-WEB_Backend_Login.md
> +   `.findOne`(mongoDB 메소드)을 통해 DB에서 email을 찾는다
mongodb 또는 mongoDB 중 하나로 통일한다면 좋을 것 같아요! 너무 글을 잘 쓰셨어요!

2021-05-16 17:17 UTC, yuniwisdom requested changes
글을 너무 잘쓰셨어요😆 코린이는 이해하지 못하는 내용이었지만 열심히 읽어보았습니다. 맞춤법과 가독성을 위한 부분 위주로 리뷰드렸습니다!! (쓰다보니 너무 많이 남겨놨네요..😓)

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +이번 포스팅에서는 교재의 2-3장을 리뷰하겠습니다.
WEB팀을 맨 아래에서 쓰신 것처럼 대문자로 쓰면 좋을 것 같아요! React 아래의 교재로 리액트 공부한다는게 말이 중복인 것 같습니다. 교재 2-3장도 각각 2장과 3장으로 하면 좋을 것 같습니다! : )
```suggestion
WEB 팀의 4번째 미션은 아래의 교재로 React 공부를 하는 것입니다.

이번 포스팅에서는 교재의 2장과 3장을 리뷰하겠습니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +장에 맞춰서 리뷰하겠습니다.
```suggestion
교재의 각 장에 맞춰서 리뷰하겠습니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +    sass는 css와 상당히 유사한 문법을 가지고 있습니다. 지금부터 소개할 몇 가지 문법은 css와 다른 sass의 문법입니다.
Sass와 CSS 대소문자 통일해주시면 더 좋을 것 같아요! 몇 개 수정하다가 아래부분에는 수정을 comment를 안달아서 수정해주시면 좋을 것 같습니다 :)
```suggestion
    Sass는 CSS와 상당히 유사한 문법을 가지고 있습니다. 지금부터 소개할 몇 가지 문법은 CSS와 다른 Sass의 문법입니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +       변수 사용시 $변수명; 으로 사용합니다.
```suggestion
       CSS는 변수명 앞에 '$'를 붙이지 않는다는 차이점이 있습니다.
       Sass는 변수 사용 시 '$변수명;'을 사용합니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +       ```
여기서 h4 뒤 중괄호가 맨 밑 중괄호랑 세트로 인식되는 것 같은데 이게 맞나요..?!
+)확인해보니 css문법과 달라서 그런 것 같아요 scss로 변경해주시면 될 것 같습니다.
```suggestion
       ```scss
       div.container {
         h4 {
           color: blue;
         }
         p {
           color: green;
         }
       }
       ```
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +    styled-components는 js 안에 css(CSS in JS)를 작성할 수 있는 리액트 라이브러리 입니다.
```suggestion
    styled-components는 js 안에 css(CSS in JS)를 작성할 수 있는 리액트 라이브러리입니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +이번 장을 어떻게 리뷰해야할 지 고민이 많았어요.
```suggestion
이번 장을 어떻게 리뷰해야 할지 고민이 많았어요.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +    4. todoItem: 할일의 정보를 렌더링 해주는 컴포넌트. 체크 버튼 누르면 텍스트 색생이 연해지고 텍스트에 마우스를 올리면 휴지통 아이콘이 나타남. 휴지통 아이콘 누르면 항목 삭제됨.
```suggestion
    2. todoHead: 오늘의 날짜와 요일을 보여주고, 앞으로 해야 할 일이 몇 개 남았는지 보여줌.
    3. todoList: todos 배열을 map() 을 사용하여 여러 개의 TodoItem 컴포넌트를 렌더링.
    4. todoItem: 할 일의 정보를 렌더링 해주는 컴포넌트. 체크 버튼 누르면 텍스트 색상이 연해지고 텍스트에 마우스를 올리면 휴지통 아이콘이 나타남. 휴지통 아이콘 누르면 항목 삭제됨.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +1. Sass
2장의 소제목 3가지(Sass, CSS Module, styled-components)를 강조하면 가독성이 더 좋을 것 같아요!
```suggestion
### 1. Sass
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +2. CSS Module
```suggestion
### 2. CSS Module
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +3. styled-components
```suggestion
### 3. styled-components
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +1. 컴포넌트 만들기
3장도 소제목들을 강조하면 가독성이 좋을 것 같습니다 :)
```suggestion
### 1. 컴포넌트 만들기
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### App.js
3장 소제목을 ###으로 쓰면 그 하위 것들은 ####으로 써야될 것 같아요!
```suggestion
#### App.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 1. TodoTemplate.js
이것도 컴포넌트 만들기 하위라서 ####사용하면 좋을 것 같아요. 그리고 ###에서 쓰는 숫자랑 형식이 같아서 1) 이 형식을 사용하는건 어떨까요?
```suggestion
#### 1) TodoTemplate.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 2. TodoHead.js
```suggestion
#### 2) TodoHead.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 3. TodoList.js
```suggestion
#### 3) TodoList.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +TodoList 위에 할 일의 항목을 보여 줄 컴포넌트를 만들겠습니다.
```suggestion
#### 4) TodoItem.js

TodoList 위에 할 일의 항목을 보여줄 컴포넌트를 만들겠습니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 5. TodoCreate.js
```suggestion
#### 5) TodoCreate.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +1. Context API 를 활용한 상태 관리
```suggestion
### 2. Context API 를 활용한 상태 관리
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +Hook은 간단히 설명하자면 class를 사용하지 않고 function에서 state를 관리할 수 있는 기능힙니다.
```suggestion
먼저 Context가 무엇인지 소개드리겠습니다. 앞서 1-22에 Context API에 대해 설명 됐는데요.

간단히 설명드리자면 context는 다양한 레벨의 컴포넌트에게 props를 전달하는 것입니다.

일반적으로 react에서는 첫 번째 사진 처럼 부모가 자식에게 하향식으로 값을 전달하는데요. Context API를 이용하면 두 번째 사진처럼 트리의 모든 레벨에 값을 공유할 수 있습니다.

상위계층에서 하위계층으로 props를 넘기는 것이 아니라 필요한 컴포넌트가 데이터에 접근할 수 있기 때문에 전역적으로 데이터 관리가 가능합니다.

Context API를 알기 위해서는 먼저 Hook 개념을 이해하셔야 합니다.
Hook은 간단히 설명하자면 class를 사용하지 않고 function에서 state를 관리할 수 있는 기능입니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +   `TodoProvider` 함수에는 todo 들이 저장 되어 있는 `initialTodos`와 todo 기능인 `CRAET`, `TOGGLE`, `REMOVE`를 모아놓은 `todoReducer`를 컴포넌트들에 전달하여 컴포넌트들이 직접 렌더링 할 수 있게 합니다.
```suggestion
   `TodoProvider` 함수에는 todo 들이 저장되어 있는 `initialTodos`와 todo 기능인 `CRAET`, `TOGGLE`, `REMOVE`를 모아놓은 `todoReducer`를 컴포넌트들에 전달하여 컴포넌트들이 직접 렌더링 할 수 있게 합니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +3. 기능 구현하기
```suggestion
### 3. 기능 구현하기
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 1. TodoHead.js
```suggestion
#### 1) TodoHead.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 2. TodoList.js
```suggestion
#### 2) TodoList.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 3. TodoItem.js
```suggestion
#### 3) TodoItem.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +글을 삭제 시 TodoHead에서 TodoContext의 `useTodoState`함수를 이용해 아직 완수 되지 않은 todo의 개수를 바로 반영합니다.
```suggestion
글을 삭제 시 TodoHead에서 TodoContext의 `useTodoState`함수를 이용해 아직 완수되지 않은 todo의 개수를 바로 반영합니다.
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +### 4. TodoCreate.js
```suggestion
#### 4) TodoCreate.js
```

2021-05-16 17:17 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +WEB팀 멤버 분들에게 너무 송구합니다...😥
```suggestion
게으른 완벽주의자가 얼마나 해로운지 다시 한 번 깨달았습니다.

WEB 팀 멤버 분들에게 너무 송구합니다...😥
```

2021-05-17 00:05 UTC, yuniwisdom requested changes
로컬에서 깨져보이는 것들이 있어서 추가로 남깁니다!

2021-05-17 00:05 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +```javascript
코드 블럭 안에 react가 인식이 안예쁘게 돼서 javascript->react로 바꿔주시면 더 예쁘게 표현됩니다! 몇 개만 코멘트 달아놨는데 react 들어있는 것은 전부 바꿔주시면 됩니다!
```suggestion
```react
```

2021-05-17 00:05 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +```javascript
```suggestion
```react
```

2021-05-17 00:05 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +```javascript
```suggestion
```react
```

2021-05-17 00:05 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +```javascript
```suggestion
```react
```

2021-05-17 00:05 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +```javascript
```suggestion
```react
```

2021-05-18 08:53 UTC, yuniwisdom requested changes
수고하셨습니다ㅎㅎ 수정해주시면 머지할게요!

2021-05-18 08:53 UTC, yuniwisdom commented on _posts/2021-02-24-WEB_Backend_Login.md
> +   ```java script
```suggestion
   해싱된 password값이랑 일치되는지 비교한다

   ```javascript
```

2021-05-18 08:53 UTC, yuniwisdom commented on _posts/2021-02-24-WEB_Backend_Login.md
> +     ```json
왜인지 모르겠지만 json으로 쓰면 로컬에서 에러로 뜨네요! javascript로 바꾸면 에러가 안뜹니다
```suggestion
     ```javascript
     {
         "id": "1223034", // 사용자 unique id
         "exp": 21313,  // 토큰 만료기간
         ...,
         "CreditCardNum": 3242342 // 절대 X, 헤더와 페이로드는 암호화되지 않음
     }
     ```

#### 시그니쳐

- 헤더와 페이로드에 시크릿키를 추가한 채 저장

     ```javascript
```

2021-05-18 08:53 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +image: /assets/images/post-WEB-Mission4/todolist_8.png
```suggestion
image: assets/images/post-WEB-Mission4/todolist_8.png
```

2021-05-18 08:53 UTC, yuniwisdom commented on _posts/2020-12-25-WEB_Mission4.md
> +게으른 완벽주의자가 얼마나 헤로운지 다시 한 번 깨달았습니다.
```suggestion
게으른 완벽주의자가 얼마나 해로운지 다시 한 번 깨달았습니다.
```

2021-05-24 10:13 UTC, zeze1004 commented on _posts/2021-02-24-WEB_Backend_Login.md
> +   `.findOne`(mongoDB 메소드)을 통해 DB에서 email을 찾는다
수정했습니다!

2021-05-24 14:14 UTC, yuniwisdom commented
소정님 web mission4 글이 제가 코멘트 단 부분만 바뀌면서 마크다운린트가 (들여쓰기 등) 깨진게 많아졌어요..! 특히 코드블럭이 지금 적용이 제대로 안돼서 마크다운린트 다시 확인 부탁드려요!! 그리고 제가 코멘트 단 것 외에도 react로 코드 쓰신 것은 코드블럭 javascript->react로 바꿔주시면 오류표시가 안납니다 : )

2021-05-24 17:24 UTC, hyehyeonmoon reviewed
썸네일이 한글이어서 오류가 나는 부분이 있습니다. 영어이름으로 바꿔주시면 바로 merge 할 수 있을 것 같습니다!

2021-05-24 17:24 UTC, hyehyeonmoon commented on _posts/2021-02-24-WEB_Backend_Login.md
> +         ...,
이 부분은 // 를 넣는 게 좋을지 의도하신 대로 깔끔하게 ..., 를 하는 게 좋을지 사실 저는 잘 모르겠어서...(초보의한계) 다른 reviewer 분이 알려주셨으면 합니다!
```suggestion
         //...,
```

2021-05-24 17:24 UTC, hyehyeonmoon commented on _posts/2021-02-24-WEB_Backend_Login.md
> +image: assets\images\post-WEB-Login\썸네일.png
썸네일.png 가 한글이라서 오류가 납니다. 영어이름으로 바꿔주세요.
```suggestion
assets/images/post-WEB-Login/sumnail.png
```

2021-05-24 17:24 UTC, hyehyeonmoon commented on _posts/2021-02-24-WEB_Backend_Login.md
> +   ![토큰1](..\assets\images\post-WEB-Login\토큰1.png)
토큰1.png 도 한글이라서 오류가 납니다. 영어이름으로 바꿔주세요.
```suggestion
     ![토큰1](../assets/images/post-WEB-Login/token.png)
```

2021-05-30 09:19 UTC, zeze1004 commented
수정했습니다ㅠㅠ
못난 팀원 때문에 고생이 많으십니다....ㅇ<-<

2021-05-30 11:04 UTC, hyehyeonmoon approved these changes
LGTM!! 수정하시느라 수고하셨어요! WEB 팀 clone coding 재미있어 보여요!

2021-05-30 11:41 UTC, yuniwisdom approved these changes

2021-05-30 11:43 UTC, merged

2021-05-30 11:43 UTC, yuniwisdom commented
LGTM!! 수고하셨습니다!!